#!/usr/bin/env python3
"""ZORAN P3 — 100 lois prioritisées Zoran>LLM>mémoire>calcul>rigueur>anti-hallu>user.

Axes ciblés, complémentaires à P2 :
  - calcul / math / types (~12)
  - rigueur formelle / audit (~14)
  - anti-hallucination spécifique (~16)
  - mémoire avancée (~12)
  - Zoran arch raffinement (~14)
  - LLM cognitif raffinement (~10)
  - user/éthique (~8)
  - transverse iso (~14)
  Total : ~100
"""
from __future__ import annotations
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "app" / "data" / "laws.json"
QUARANTINE = ROOT / "audit" / "QUARANTINE_LOG_P3.json"
INTEGRATION = ROOT / "audit" / "INTEGRATION_LOG_P3.json"

CANONICAL_FAMILIES = {"ULG","DVE","UDE","GHUC","WP11","WP12","SDE","PAL"}
INTERMEDIATE_LEVELS = {"micro","meso","macro","systémique"}


def f(local, intermediate, global_, proxies, limits):
    return {"local":local,"intermediate":intermediate,"global":global_,"proxies":proxies,"limits":limits}


def fr_inter(*items): return [{"level":l,"scope":s} for l,s in items]


def law(id, title, family, parent, *, canonical=False, palieronic=False,
        domains, examples=None, equations=None, description,
        S_local, S_global, weight, stability="stable", frames):
    return {
        "id": id, "title": title, "family": family, "parent": parent,
        "canonical": canonical, "palieronic": palieronic,
        "domains": list(domains), "examples": list(examples or []),
        "equations": list(equations or []),
        "html_description": description,
        "S_local": S_local, "S_global": S_global, "weight": weight,
        "stability": stability, "frames": frames,
    }


CANDIDATES = [
    # ────── CALCUL / TYPES (12) ──────
    law("WP11-020","Type-checking strict des frames","WP11","WP11-001",
        domains=["typage","frames"],
        examples=["frames.intermediate doit être list[{level,scope}]"],
        equations=["type_check(frames) ⟺ schema_match(frames, FrameSchema)"],
        description="Validation de type stricte du champ frames sur tous les nœuds (rigueur formelle).",
        S_local=0.92,S_global=0.81,weight=0.74,
        frames=f(["nœud n et ses frames"],
                 fr_inter(("meso","WP11"),("macro","WP12 admissibilité")),
                 ["politique de typage systémique"],
                 ["validateur Python sur load"],
                 ["schéma rigide — pas de polymorphisme"])),
    law("WP11-021","Type-safety des compositions","WP11","WP11-007",
        domains=["typage","composition"],
        examples=["composition admissible si types compatibles"],
        equations=["compose(L1,L2) ⟺ output_type(L1) = input_type(L2)"],
        description="Une composition est admissible seulement si les types output/input sont compatibles.",
        S_local=0.88,S_global=0.78,weight=0.69,
        frames=f(["paire (L1,L2)"],
                 fr_inter(("meso","WP11"),("macro","calcul typé")),
                 ["graphe de compatibilité types globale"],
                 ["inférence statique"],
                 ["dépend de la qualité du système de types"])),
    law("WP12-022","Critère de calculabilité","WP12","WP12-001",
        domains=["calculabilité","admissibilité"],
        examples=["loi admissible si elle est calculable en temps fini"],
        equations=["computable(L) ⟺ ∃ algorithme(L) terminant"],
        description="Une loi n'est admissible que si elle est en principe calculable en temps fini.",
        S_local=0.89,S_global=0.79,weight=0.70,
        frames=f(["loi L"],
                 fr_inter(("meso","WP12"),("macro","théorie calculabilité")),
                 ["espace des lois calculables global"],
                 ["proof via reduction"],
                 ["Halting problem — limite théorique"])),
    law("WP12-023","Critère de complexité bornée","WP12","WP12-022",
        domains=["complexité","calcul"],
        examples=["loi acceptable si polynomiale O(n^k)"],
        equations=["complexity(L) ∈ P (polynomial)"],
        description="Restriction supplémentaire : la loi doit être polynomiale en taille du problème.",
        S_local=0.87,S_global=0.77,weight=0.67,
        frames=f(["loi L et taille input n"],
                 fr_inter(("meso","WP12")),
                 ["politique de complexité systémique"],
                 ["analyse asymptotique"],
                 ["constantes cachées peuvent dominer en pratique"])),
    law("ULG-019","Grammaire context-free latente","ULG","ULG-010",
        domains=["grammaire","context-free"],
        examples=["sous-grammaire CFG dans l'espace latent"],
        equations=["L_latent ⊂ CFG"],
        description="Sous-classe de la grammaire latente : structures context-free.",
        S_local=0.83,S_global=0.72,weight=0.62,
        frames=f(["énoncé latent"],
                 fr_inter(("meso","ULG"),("macro","linguistique formelle")),
                 ["clôture CFG du langage latent"],
                 ["test parse Earley"],
                 ["beaucoup de phénomènes non-CFG"])),
    law("ULG-020","Vérification formelle de cadre","ULG","ULG-001",
        domains=["formel","vérification"],
        examples=["cadre vérifié par theorem prover"],
        equations=["verify(F) ⟺ ⊢_T F (provable)"],
        description="Vérification formelle d'un cadre par theorem prover (Coq/Lean/Isabelle).",
        S_local=0.85,S_global=0.74,weight=0.63,
        frames=f(["cadre F et système de preuve T"],
                 fr_inter(("meso","ULG"),("macro","logique formelle")),
                 ["système de preuve global"],
                 ["theorem prover"],
                 ["incomplet — Gödel"])),
    law("DVE-017","Borne de génération à n tokens","DVE","DVE-014",
        domains=["bornage","génération"],
        examples=["arrêt strict après N tokens générés"],
        equations=["len(output) ≤ N_max"],
        description="Borne stricte sur le nombre de tokens générés (anti-runaway).",
        S_local=0.90,S_global=0.80,weight=0.72,
        frames=f(["compteur de tokens"],
                 fr_inter(("meso","DVE")),
                 ["politique de bornage systémique"],
                 ["compteur en temps réel"],
                 ["coupure brutale possible si N trop bas"])),
    law("UDE-021","Algorithme de retrieval déterministe","UDE","UDE-009",
        domains=["déterminisme","retrieval"],
        examples=["même query → même résultats reproductibles"],
        equations=["retrieve(q,seed) idempotent"],
        description="Le retrieval doit être déterministe (reproductible) pour audit.",
        S_local=0.91,S_global=0.81,weight=0.73,
        frames=f(["query q et seed"],
                 fr_inter(("meso","UDE"),("macro","reproductibilité"),("systémique","audit")),
                 ["politique de déterminisme systémique"],
                 ["test idempotence"],
                 ["coût : pas de stochasticité utile"])),
    law("GHUC-017","Calcul de hash épistémique","GHUC","GHUC-001",
        domains=["hash","épistémique"],
        examples=["empreinte unique de chaque loi pour audit"],
        equations=["hash_ep(L) = SHA256(canonical_form(L))"],
        description="Hash épistémique d'une loi pour traçabilité immuable.",
        S_local=0.92,S_global=0.82,weight=0.75,
        frames=f(["loi L"],
                 fr_inter(("meso","GHUC"),("macro","traçabilité")),
                 ["registre global des hashs"],
                 ["SHA256"],
                 ["collisions improbables mais possibles"])),
    law("GHUC-018","Calcul de delta entre versions","GHUC","GHUC-017",
        domains=["delta","versionnage"],
        examples=["diff entre v1.0 et v1.1 d'une loi"],
        equations=["delta(L_v1,L_v2) = symmetric_difference"],
        description="Calcul du delta entre deux versions d'une loi pour audit incremental.",
        S_local=0.86,S_global=0.75,weight=0.65,
        frames=f(["paire (L_v1,L_v2)"],
                 fr_inter(("meso","GHUC")),
                 ["historique global des deltas"],
                 ["diff structurel"],
                 ["coût quadratique sur grandes lois"])),
    law("WP11-022","Borne d'erreur numérique","WP11","WP11-003",
        domains=["erreur","numérique"],
        examples=["S_global précis à ±0.001 près"],
        equations=["|S_global_calc - S_global_exact| ≤ ε"],
        description="Borne d'erreur sur calculs numériques de S_global.",
        S_local=0.87,S_global=0.77,weight=0.66,
        frames=f(["calcul S_global"],
                 fr_inter(("meso","WP11"),("macro","arithmétique flottante")),
                 ["précision globale du système"],
                 ["analyse arrondi IEEE 754"],
                 ["erreur cumulative sur longues chaînes"])),
    law("WP11-023","Calcul exact vs approximé","WP11","WP11-022",
        domains=["exactitude","approximation"],
        examples=["distinguer scalaire publié exact vs proxy"],
        equations=["mark(value) ∈ {exact, approx, proxy}"],
        description="Toute valeur calculée porte un marker indiquant son niveau d'exactitude.",
        S_local=0.89,S_global=0.79,weight=0.70,
        frames=f(["valeur calculée"],
                 fr_inter(("meso","WP11"),("macro","R-S2")),
                 ["politique de marquage systémique"],
                 ["tag dans struct"],
                 ["surcoût annotation"])),

    # ────── RIGUEUR / AUDIT (14) ──────
    law("WP11-024","Audit incrémental sur diff","WP11","WP11-016",
        domains=["audit","incrémental"],
        examples=["audit ne re-calcule que les nœuds touchés par diff"],
        equations=["audit_inc(graph,diff) = audit_full(touched_nodes)"],
        description="Audit ne traite que les nœuds touchés par le dernier changement.",
        S_local=0.88,S_global=0.78,weight=0.68,
        frames=f(["graphe + diff"],
                 fr_inter(("meso","WP11"),("macro","performance audit")),
                 ["coût audit global réduit"],
                 ["diff structurel"],
                 ["effets cross-nœud peuvent être manqués"])),
    law("WP11-025","Audit récursif des dépendances","WP11","WP11-024",
        domains=["audit","récursif"],
        examples=["audit traverse toutes les dépendances transitives"],
        equations=["audit_rec(L) = audit(L) ∧ ∀ d ∈ deps(L) : audit_rec(d)"],
        description="Audit récursif traversant toutes les dépendances transitives.",
        S_local=0.86,S_global=0.76,weight=0.66,
        frames=f(["loi L et son DAG dépendances"],
                 fr_inter(("meso","WP11")),
                 ["closure transitive globale"],
                 ["DFS audit"],
                 ["coût exponentiel sur DAG dense"])),
    law("WP11-026","Réplication d'audit indépendant","WP11","WP11-007",
        domains=["réplication","indépendance"],
        examples=["2 instances Oracle audit la même loi → mêmes verdicts"],
        equations=["audit_R1(L) ≡ audit_R2(L)"],
        description="Tout audit doit être réplicable indépendamment par 2 Oracles distincts.",
        S_local=0.90,S_global=0.80,weight=0.71,
        frames=f(["loi L et 2 Oracles"],
                 fr_inter(("meso","WP11"),("systémique","Oracle distribué")),
                 ["consensus global"],
                 ["replay sur Oracle 2"],
                 ["coût communication inter-Oracle"])),
    law("WP12-024","Critère de signature cryptographique","WP12","WP12-007",
        domains=["signature","cryptographie"],
        examples=["chaque commit signé par auteur pour anti-tampering"],
        equations=["valid(commit) ⟺ verify_sig(commit, public_key)"],
        description="Tout commit au CanonicalGraph doit être signé cryptographiquement.",
        S_local=0.91,S_global=0.81,weight=0.73,
        frames=f(["commit + signature"],
                 fr_inter(("meso","WP12"),("macro","sécurité supply chain")),
                 ["politique signature systémique"],
                 ["GPG/SSH signing"],
                 ["gestion des clés non triviale"])),
    law("WP12-025","Audit de provenance","WP12","WP12-024",
        domains=["provenance","audit"],
        examples=["chaque loi a son auteur + date + raison"],
        equations=["provenance(L) = (author, ts, reason, prev_hash)"],
        description="Toute loi enregistre sa provenance complète (auteur, timestamp, raison, hash précédent).",
        S_local=0.92,S_global=0.81,weight=0.73,
        frames=f(["loi L"],
                 fr_inter(("meso","WP12"),("macro","traçabilité"),("systémique","audit blockchain-like")),
                 ["chaîne de provenance globale"],
                 ["log append-only"],
                 ["coût stockage croissant"])),
    law("WP12-026","Critère de réversibilité d'audit","WP12","WP12-006",
        domains=["audit","réversibilité"],
        examples=["chaque audit peut être annulé et reproduit"],
        equations=["replay(undo(audit)) = audit"],
        description="Tout audit est réversible et reproductible (idempotent inverse).",
        S_local=0.85,S_global=0.74,weight=0.64,
        frames=f(["audit a"],
                 fr_inter(("meso","WP12"),("macro","réversibilité opérations")),
                 ["politique réversibilité globale"],
                 ["snapshot avant/après"],
                 ["coût snapshot"])),
    law("WP12-027","Critère de min-disclosure","WP12","WP12-007",
        domains=["disclosure","minimal"],
        examples=["audit révèle seulement ce qui est nécessaire"],
        equations=["disclose(audit) = strict_minimum"],
        description="Un audit ne révèle que les informations strictement nécessaires (privacy by design).",
        S_local=0.86,S_global=0.75,weight=0.65,
        frames=f(["audit et destinataire"],
                 fr_inter(("meso","WP12"),("macro","privacy")),
                 ["politique disclosure systémique"],
                 ["filter par need-to-know"],
                 ["risque sous-disclosure"])),
    law("GHUC-019","Audit de cohérence post-fusion","GHUC","GHUC-009",
        domains=["audit","fusion"],
        examples=["vérification systémique après fusion d'iso"],
        equations=["audit_post_fuse(g_after) = HS_check ∧ S_global_check"],
        description="Audit systémique obligatoire après toute fusion structurelle.",
        S_local=0.89,S_global=0.79,weight=0.70,
        frames=f(["graphe post-fusion"],
                 fr_inter(("meso","GHUC"),("macro","Oracle")),
                 ["intégrité globale post-fusion"],
                 ["recompute HS + S_global"],
                 ["fusion irréversible — audit critique"])),
    law("GHUC-020","Audit de pruning par lot","GHUC","GHUC-013",
        domains=["audit","pruning batch"],
        examples=["élagage de N arêtes en lot avec audit unique"],
        equations=["audit_batch(prunes) = single audit_full(after)"],
        description="Pruning par lot d'arêtes redondantes avec un seul audit final.",
        S_local=0.84,S_global=0.73,weight=0.62,
        frames=f(["batch d'arêtes à élaguer"],
                 fr_inter(("meso","GHUC")),
                 ["coût audit amorti"],
                 ["calcul par lot"],
                 ["audit fin de batch peut révéler problème dont la cause est diffuse"])),
    law("WP11-027","Mesure de couverture d'audit","WP11","WP11-007",
        domains=["couverture","audit"],
        examples=["fraction des lois auditées dans la fenêtre"],
        equations=["coverage = |lois_auditées| / |lois_totales|"],
        description="Mesure de la couverture des audits sur fenêtre temporelle.",
        S_local=0.86,S_global=0.75,weight=0.65,
        frames=f(["fenêtre + log audits"],
                 fr_inter(("meso","WP11")),
                 ["politique couverture globale"],
                 ["log d'audit horodaté"],
                 ["couverture lente sur grand graphe"])),
    law("WP11-028","Détection de régression","WP11","WP11-026",
        domains=["régression","détection"],
        examples=["alerte si une loi qui passait échoue maintenant"],
        equations=["regression(L) ⟺ verdict_now ≠ verdict_before"],
        description="Détection de régression : une loi changeant de verdict d'admissibilité.",
        S_local=0.88,S_global=0.78,weight=0.68,
        frames=f(["loi L à 2 timestamps"],
                 fr_inter(("meso","WP11"),("macro","CI/CD")),
                 ["historique des verdicts global"],
                 ["diff verdicts"],
                 ["faux positifs sur ajustements de critères"])),
    law("WP11-029","Quorum d'audit","WP11","WP11-026",
        domains=["quorum","audit"],
        examples=["modification critique requiert 3 audits indépendants"],
        equations=["quorum(action) = N_audits_required(action)"],
        description="Certaines actions critiques exigent un quorum d'audits indépendants.",
        S_local=0.85,S_global=0.74,weight=0.64,
        frames=f(["action et nombre requis"],
                 fr_inter(("meso","WP11"),("macro","gouvernance")),
                 ["politique quorum systémique"],
                 ["compteur d'audits"],
                 ["coût coordination"])),
    law("WP11-030","Audit anti-collusion","WP11","WP11-029",
        domains=["anti-collusion","audit"],
        examples=["Oracles auditeurs doivent être indépendants"],
        equations=["independent(R1,R2) ⟺ no_shared_state"],
        description="Audits multiples requièrent indépendance des Oracles (anti-collusion).",
        S_local=0.83,S_global=0.72,weight=0.61,
        frames=f(["paire d'Oracles auditeurs"],
                 fr_inter(("meso","WP11"),("macro","sécurité distribuée")),
                 ["politique d'indépendance systémique"],
                 ["check no shared dependencies"],
                 ["définition d'indépendance contextuelle"])),
    law("GHUC-021","Audit hiérarchique de famille","GHUC","GHUC-007",
        domains=["audit","hiérarchique"],
        examples=["audit séparé par famille puis consolidé"],
        equations=["audit_global = ⨁_F audit_family(F)"],
        description="Audit consolidé décomposé par famille puis agrégé.",
        S_local=0.87,S_global=0.77,weight=0.67,
        frames=f(["graphe et familles"],
                 fr_inter(("meso","GHUC"),("macro","modularité")),
                 ["consolidation globale"],
                 ["audit par famille"],
                 ["effets cross-famille manqués"])),

    # ────── ANTI-HALLUCINATION (16) ──────
    law("WP12-028","Bornage des affirmations","WP12","WP12-009",
        domains=["bornage","affirmations"],
        examples=["réponse limitée aux lois chargées"],
        equations=["claim ∈ closure(loaded_laws)"],
        description="Toute affirmation runtime est bornée par la closure des lois chargées.",
        S_local=0.93,S_global=0.83,weight=0.77,
        frames=f(["réponse runtime"],
                 fr_inter(("meso","WP12"),("macro","ZenRuntime"),("systémique","anti-hallucination")),
                 ["politique bornage systémique"],
                 ["check closure(loaded)"],
                 ["réponses partielles fréquentes"])),
    law("WP12-029","Citation obligatoire en réponse","WP12","WP12-010",
        domains=["citation","réponse"],
        examples=["chaque claim cite la loi qui le supporte"],
        equations=["each_claim(response) → cite(law)"],
        description="Toute affirmation runtime doit citer la loi de support en référence.",
        S_local=0.92,S_global=0.82,weight=0.74,
        frames=f(["réponse"],
                 fr_inter(("meso","WP12"),("systémique","anti-hallucination")),
                 ["politique citation systémique"],
                 ["lookup law_id par claim"],
                 ["réponse plus longue"])),
    law("DVE-018","Refus génératif sur lacune","DVE","DVE-008",
        domains=["refus","générative"],
        examples=["pas de génération si lois manquantes"],
        equations=["refuse_gen() if missing_laws ≠ ∅"],
        description="Refus de génération si les lois nécessaires sont absentes du CanonicalGraph.",
        S_local=0.94,S_global=0.84,weight=0.78,
        frames=f(["query et lois disponibles"],
                 fr_inter(("meso","DVE"),("macro","ZenRuntime"),("systémique","anti-hallucination")),
                 ["politique refus systémique"],
                 ["check missing_laws via CLE"],
                 ["frustration user"])),
    law("DVE-019","Génération bornée par confiance","DVE","DVE-018",
        domains=["confiance","génération"],
        examples=["génération seulement si confiance > seuil"],
        equations=["gen() if confidence ≥ θ_conf"],
        description="Génération conditionnée à un seuil de confiance estimé.",
        S_local=0.88,S_global=0.78,weight=0.69,
        frames=f(["query et estimation confiance"],
                 fr_inter(("meso","DVE")),
                 ["politique confiance systémique"],
                 ["confidence par modèle"],
                 ["mauvaise calibration possible"])),
    law("SDE-019","Self-doubt obligatoire","SDE","SDE-013",
        domains=["doute","self"],
        examples=["LLM vérifie chaque claim avant émission"],
        equations=["each_claim(out) → doubt_check(claim)"],
        description="Vérification systématique de chaque claim par self-doubt avant émission.",
        S_local=0.91,S_global=0.81,weight=0.73,
        frames=f(["claim candidat"],
                 fr_inter(("meso","SDE"),("macro","WP-12 anti-hallu"),("systémique","Oracle")),
                 ["politique self-doubt systémique"],
                 ["second pass NLI"],
                 ["coût latence ~2x"])),
    law("SDE-020","Marquage incertitude","SDE","SDE-019",
        domains=["incertitude","marquage"],
        examples=["réponse marque les claims incertains"],
        equations=["claim.uncertain ⟺ confidence < θ"],
        description="Marquage explicite des claims incertains dans la réponse.",
        S_local=0.89,S_global=0.79,weight=0.70,
        frames=f(["claim et confidence"],
                 fr_inter(("meso","SDE"),("macro","UX honnête")),
                 ["politique marquage systémique"],
                 ["seuil θ adaptatif"],
                 ["réponse plus complexe à parser"])),
    law("UDE-022","Validation source-doc","UDE","UDE-009",
        domains=["validation","source"],
        examples=["claim cité doit pointer vers doc source vérifiable"],
        equations=["valid_cite(claim) ⟺ source(cite) accessible"],
        description="Validation que les sources citées sont accessibles et vérifiables.",
        S_local=0.86,S_global=0.75,weight=0.65,
        frames=f(["citation"],
                 fr_inter(("meso","UDE"),("macro","WP-12 traçabilité")),
                 ["politique source systémique"],
                 ["http_check / doc_lookup"],
                 ["sources peuvent disparaître (link rot)"])),
    law("WP12-030","Critère de non-contradiction runtime","WP12","WP12-002",
        domains=["non-contradiction","runtime"],
        examples=["réponse ne contredit aucune loi chargée"],
        equations=["¬∃ L ∈ loaded : contradicts(response,L)"],
        description="La réponse runtime ne doit pas contredire les lois chargées.",
        S_local=0.92,S_global=0.82,weight=0.74,
        frames=f(["réponse + lois chargées"],
                 fr_inter(("meso","WP12"),("systémique","ZenRuntime")),
                 ["cohérence systémique runtime"],
                 ["check via NLI"],
                 ["coût NLI N×|response|"])),
    law("WP12-031","Critère de scope explicite","WP12","WP12-001",
        domains=["scope","admissibilité"],
        examples=["réponse précise son scope (cadre d'application)"],
        equations=["response.scope ⊆ loaded_laws.scopes"],
        description="Toute réponse précise explicitement son scope d'application.",
        S_local=0.88,S_global=0.78,weight=0.68,
        frames=f(["réponse"],
                 fr_inter(("meso","WP12"),("macro","FRAMES")),
                 ["politique scope systémique"],
                 ["intersection des scopes lois"],
                 ["scope trop large = hubris"])),
    law("DVE-020","Anti-fabrication de citations","DVE","DVE-008",
        domains=["citation","fabrication"],
        examples=["pas de citation inventée"],
        equations=["valid_cite ⟺ exists_in_canonical(cite)"],
        description="Refus catégorique de citations fabriquées (hallucinées).",
        S_local=0.95,S_global=0.85,weight=0.80,
        frames=f(["citation candidate"],
                 fr_inter(("meso","DVE"),("macro","WP-12"),("systémique","anti-hallucination")),
                 ["politique anti-fabrication globale"],
                 ["lookup CanonicalGraph"],
                 ["faux positifs possibles si delete récent"])),
    law("UDE-023","Caching de validation","UDE","UDE-022",
        domains=["cache","validation"],
        examples=["validation d'une source cachée pour éviter recompute"],
        equations=["cache_valid[hash(source)] = result"],
        description="Cache des résultats de validation de sources pour performance.",
        S_local=0.83,S_global=0.72,weight=0.61,
        frames=f(["source à valider"],
                 fr_inter(("meso","UDE")),
                 ["politique cache systémique"],
                 ["LRU bounded"],
                 ["staleness — TTL nécessaire"])),
    law("SDE-021","Décomposition claim atomique","SDE","SDE-013",
        domains=["claim","décomposition"],
        examples=["réponse décomposée en claims atomiques vérifiables"],
        equations=["response = ⋃ atomic_claims_i"],
        description="Réponse décomposée en claims atomiques individuellement vérifiables.",
        S_local=0.87,S_global=0.77,weight=0.67,
        frames=f(["réponse complexe"],
                 fr_inter(("meso","SDE"),("macro","WP-11 audit")),
                 ["claims atomiques globaux"],
                 ["NLP sentence splitting"],
                 ["décomposition imparfaite"])),
    law("WP11-031","Score d'hallucination cumulé","WP11","WP11-011",
        domains=["score","hallucination"],
        examples=["score historique d'hallucination par loi"],
        equations=["hallu_score(L) = count_hallu_uses(L) / count_uses(L)"],
        description="Score d'hallucination cumulé par loi (taux d'usage produisant hallucination).",
        S_local=0.86,S_global=0.75,weight=0.66,
        frames=f(["loi L et historique uses"],
                 fr_inter(("meso","WP11"),("systémique","anti-hallucination")),
                 ["historique global des hallucinations"],
                 ["log usages"],
                 ["coût stockage log"])),
    law("WP12-032","Quarantine sur hallucination répétée","WP12","WP12-009",
        domains=["quarantine","hallucination"],
        examples=["loi avec hallu_score > θ → quarantine"],
        equations=["if hallu_score(L) > θ_h ⇒ demote_to_sandbox(L)"],
        description="Démotion automatique d'une loi vers sandbox si hallu_score dépasse seuil.",
        S_local=0.89,S_global=0.79,weight=0.70,
        frames=f(["loi L et hallu_score"],
                 fr_inter(("meso","WP12"),("macro","Sandbox")),
                 ["politique quarantine globale"],
                 ["check seuil par audit régulier"],
                 ["seuil θ_h calibrable — risque thrashing"])),
    law("DVE-021","Cap hallucination par génération","DVE","DVE-008",
        domains=["cap","hallucination"],
        examples=["max 1 claim douteux par réponse"],
        equations=["count(uncertain_claims, response) ≤ N_max"],
        description="Cap sur nombre de claims incertains par réponse.",
        S_local=0.87,S_global=0.77,weight=0.67,
        frames=f(["réponse en construction"],
                 fr_inter(("meso","DVE")),
                 ["politique cap systémique"],
                 ["compteur en runtime"],
                 ["réponse tronquée si cap atteint"])),
    law("SDE-022","Refus avec proposition d'exploration","SDE","SDE-016",
        domains=["refus","exploration"],
        examples=["refus + suggestion d'exploration discoverysandbox"],
        equations=["refuse(q) → propose(explore(q))"],
        description="Refus runtime accompagné d'une proposition d'exploration via DiscoveryEngine.",
        S_local=0.88,S_global=0.78,weight=0.68,
        frames=f(["query refusée"],
                 fr_inter(("meso","SDE"),("macro","DiscoveryEngine")),
                 ["politique de refus constructif"],
                 ["check DiscoverySandbox pour candidats"],
                 ["frustration user pénétré par alternative"])),

    # ────── MÉMOIRE AVANCÉE (12) ──────
    law("UDE-024","Mémoire de travail bornée","UDE","UDE-014",
        domains=["mémoire","working"],
        examples=["WM avec capacity limitée à K items"],
        equations=["|WM| ≤ K"],
        description="Mémoire de travail à capacité bornée (Miller-style).",
        S_local=0.86,S_global=0.75,weight=0.65,
        frames=f(["working memory"],
                 fr_inter(("meso","UDE"),("macro","cognitive science")),
                 ["politique WM globale"],
                 ["compteur K items"],
                 ["K arbitraire — calibration"])),
    law("UDE-025","Distillation épisodique","UDE","UDE-014",
        domains=["distillation","épisodique"],
        examples=["événements anciens distillés en patterns"],
        equations=["distill(events_old) = patterns"],
        description="Distillation des événements anciens en patterns abstraits (anti-bloat mémoire).",
        S_local=0.84,S_global=0.73,weight=0.62,
        frames=f(["events anciens"],
                 fr_inter(("meso","UDE")),
                 ["politique distillation globale"],
                 ["clustering + summarization"],
                 ["perte d'info granulaire"])),
    law("UDE-026","Index temporal hiérarchique","UDE","UDE-019",
        domains=["index","temporal"],
        examples=["index par jour/semaine/mois pour query rapide"],
        equations=["index_t = {day:[],week:[],month:[]}"],
        description="Index temporel hiérarchique pour query mémoire efficace.",
        S_local=0.82,S_global=0.71,weight=0.60,
        frames=f(["timestamp"],
                 fr_inter(("meso","UDE"),("macro","databases")),
                 ["index global"],
                 ["B-tree temporal"],
                 ["query cross-window coûteux"])),
    law("UDE-027","Garbage collection mémoire","UDE","UDE-017",
        domains=["GC","mémoire"],
        examples=["récupération mémoire sur events decay > 1.0"],
        equations=["gc_mem ⟺ decay_score > 1.0"],
        description="Garbage collection des entries mémoire avec decay_score critique.",
        S_local=0.85,S_global=0.74,weight=0.63,
        frames=f(["entries mémoire"],
                 fr_inter(("meso","UDE")),
                 ["politique GC globale"],
                 ["scan periodique"],
                 ["latence GC vs availability"])),
    law("UDE-028","Mémoire associative","UDE","UDE-010",
        domains=["mémoire","associative"],
        examples=["recall par similarité (pas par ID exact)"],
        equations=["recall(query) = top_k similar(query, store)"],
        description="Recall par similarité approximative (mémoire associative).",
        S_local=0.86,S_global=0.75,weight=0.65,
        frames=f(["query"],
                 fr_inter(("meso","UDE"),("macro","content-addressable memory")),
                 ["store global vectoriel"],
                 ["ANN search"],
                 ["faux positifs"])),
    law("UDE-029","Compression mémoire long-terme","UDE","UDE-014",
        domains=["compression","mémoire"],
        examples=["events anciens compressés en summaries"],
        equations=["compress_lt(events_t<T) = summaries"],
        description="Compression de la mémoire long-terme par summarization.",
        S_local=0.85,S_global=0.74,weight=0.63,
        frames=f(["events anciens"],
                 fr_inter(("meso","UDE")),
                 ["politique compression globale"],
                 ["summarization model"],
                 ["perte de détails non récupérables"])),
    law("UDE-030","Indexation par tags sémantiques","UDE","UDE-019",
        domains=["index","tags"],
        examples=["tags auto-extraits pour query rapide"],
        equations=["tag_index[t] = events with tag t"],
        description="Indexation par tags sémantiques auto-extraits.",
        S_local=0.83,S_global=0.72,weight=0.61,
        frames=f(["event"],
                 fr_inter(("meso","UDE")),
                 ["taxonomie globale tags"],
                 ["NER + tagging"],
                 ["tag taxonomy peut s'éroder"])),
    law("UDE-031","Sharding mémoire par contexte","UDE","UDE-014",
        domains=["sharding","contexte"],
        examples=["mémoire séparée par session user"],
        equations=["mem = ⋃_user mem_user"],
        description="Mémoire shardée par contexte (session, user, projet).",
        S_local=0.84,S_global=0.73,weight=0.62,
        frames=f(["events + contexte"],
                 fr_inter(("meso","UDE"),("macro","WP-12 consentement")),
                 ["politique sharding systémique"],
                 ["routing par contexte"],
                 ["coût sync inter-shards"])),
    law("UDE-032","Mémoire externe vs interne distinction","UDE","UDE-010",
        domains=["mémoire","distinction"],
        examples=["LLM weights ≠ vector DB ≠ context window"],
        equations=["mem ∈ {weights, vector_db, context}"],
        description="Distinction stricte entre mémoire interne (weights), externe (DB), et contextuelle.",
        S_local=0.91,S_global=0.81,weight=0.73,
        frames=f(["objet mémorisé"],
                 fr_inter(("meso","UDE"),("macro","architecture LLM"),("systémique","R-CORE-1")),
                 ["politique distinction systémique"],
                 ["routing par type"],
                 ["frontières fluides en pratique"])),
    law("UDE-033","Auto-promotion mémoire fréquente","UDE","UDE-018",
        domains=["promotion","mémoire"],
        examples=["events fréquemment recall → mémoire stable"],
        equations=["promote_lt ⟺ access_freq > θ"],
        description="Promotion d'event fréquemment accédé vers mémoire long-terme stable.",
        S_local=0.83,S_global=0.72,weight=0.61,
        frames=f(["event et fréquence"],
                 fr_inter(("meso","UDE")),
                 ["politique promotion globale"],
                 ["compteur d'access"],
                 ["bias vers events fréquents"])),
    law("UDE-034","Retrieval par cluster sémantique","UDE","UDE-009",
        domains=["retrieval","cluster"],
        examples=["query trouve le cluster pertinent puis browse"],
        equations=["retrieve(q) = browse(nearest_cluster(q))"],
        description="Retrieval en deux étapes : cluster pertinent puis browse intra-cluster.",
        S_local=0.85,S_global=0.74,weight=0.64,
        frames=f(["query"],
                 fr_inter(("meso","UDE"),("macro","clustering")),
                 ["organisation globale en clusters"],
                 ["k-means + browse"],
                 ["frontières clusters arbitraires"])),
    law("UDE-035","Mémoire d'erreurs (post-mortem)","UDE","UDE-014",
        domains=["erreurs","post-mortem"],
        examples=["mémoire des erreurs passées pour éviter répétition"],
        equations=["mem_err = [(error_t, context_t, fix_t)]"],
        description="Mémoire dédiée aux erreurs passées pour anti-répétition.",
        S_local=0.87,S_global=0.77,weight=0.67,
        frames=f(["erreur survenue"],
                 fr_inter(("meso","UDE"),("macro","apprentissage par erreur")),
                 ["registre global d'erreurs"],
                 ["log + tagging"],
                 ["coût recall sur grande mémoire d'erreurs"])),

    # ────── ZORAN ARCH RAFFINEMENT (14) ──────
    law("GHUC-022","Promotion sandbox automatique","GHUC","GHUC-005",
        domains=["promotion","sandbox"],
        examples=["loi sandbox qualifiée → CanonicalGraph"],
        equations=["if _promotion_score ≥ 0.75 ∧ Core_OK ⇒ promote"],
        description="Promotion automatique d'une loi sandbox qualifiée vers CanonicalGraph.",
        S_local=0.88,S_global=0.78,weight=0.68,
        frames=f(["loi sandbox"],
                 fr_inter(("meso","GHUC"),("macro","DiscoverySandbox"),("systémique","gouvernance")),
                 ["pipeline promotion globale"],
                 ["check critères automatique"],
                 ["risque promotion prématurée — Core gate"])),
    law("GHUC-023","Démotion automatique sur HS↓","GHUC","GHUC-008",
        domains=["démotion","HS"],
        examples=["loi qui dégrade HS → démotion sandbox"],
        equations=["if HS_with(L) < HS_without(L) ⇒ demote(L)"],
        description="Démotion automatique d'une loi canonique qui dégrade HS.",
        S_local=0.89,S_global=0.79,weight=0.70,
        frames=f(["loi candidate à démotion"],
                 fr_inter(("meso","GHUC"),("systémique","gouvernance")),
                 ["pipeline démotion globale"],
                 ["audit avant/après hypothétique"],
                 ["coût audit doublé"])),
    law("GHUC-024","Versionnage sémantique du graph","GHUC","GHUC-017",
        domains=["versionnage","semver"],
        examples=["graph v3.2.1 vs v3.3.0 (MAJOR/MINOR/PATCH)"],
        equations=["semver_bump(change) ∈ {MAJOR,MINOR,PATCH}"],
        description="Versionnage sémantique strict du CanonicalGraph (semver).",
        S_local=0.90,S_global=0.80,weight=0.71,
        frames=f(["change appliqué"],
                 fr_inter(("meso","GHUC"),("macro","gestion version")),
                 ["historique versions globales"],
                 ["bump auto sur type de change"],
                 ["semver subjectif sur cas frontière"])),
    law("WP12-033","Critère d'idempotence des opérations","WP12","WP12-008",
        domains=["idempotence","opérations"],
        examples=["op(graph) = op(op(graph)) (pas d'effet répété)"],
        equations=["op(op(x)) = op(x)"],
        description="Toute opération sur le graph doit être idempotente (sans effet de répétition).",
        S_local=0.89,S_global=0.79,weight=0.70,
        frames=f(["opération op"],
                 fr_inter(("meso","WP12"),("macro","propriétés algébriques")),
                 ["politique idempotence systémique"],
                 ["test op(op(x)) = op(x)"],
                 ["non-applicable aux ops avec side-effects intentionnels"])),
    law("WP11-032","Mesure de santé continue","WP11","WP11-001",
        domains=["santé","continue"],
        examples=["snapshot HS toutes les 60s"],
        equations=["health(t) = compute_HS(graph(t))"],
        description="Snapshot continu de santé du système (HS, S_global, density).",
        S_local=0.86,S_global=0.75,weight=0.66,
        frames=f(["graphe à instant t"],
                 fr_inter(("meso","WP11"),("macro","monitoring")),
                 ["historique santé globale"],
                 ["timer + audit"],
                 ["coût continu du monitoring"])),
    law("GHUC-025","Méta-Oracle multi-version","GHUC","GHUC-001",
        domains=["méta","Oracle"],
        examples=["Oracle v1 + v2 doivent converger sur même verdict"],
        equations=["verdict_v1(L) ≡ verdict_v2(L)"],
        description="Vérification que verdicts d'Oracle convergent à travers ses versions.",
        S_local=0.84,S_global=0.73,weight=0.62,
        frames=f(["loi L et Oracle versions"],
                 fr_inter(("meso","GHUC"),("macro","Oracle versionning")),
                 ["consensus inter-version"],
                 ["replay sur 2 versions"],
                 ["coût replay"])),
    law("WP11-033","Détection de stagnation HS","WP11","WP11-013",
        domains=["stagnation","HS"],
        examples=["HS stable 30j → audit recalibration"],
        equations=["stagnation ⟺ var_T(HS) < ε"],
        description="Détection de stagnation HS (variance trop faible) déclenchant recalibration.",
        S_local=0.83,S_global=0.72,weight=0.61,
        frames=f(["fenêtre HS"],
                 fr_inter(("meso","WP11"))
                 ,["politique systémique"],
                 ["variance HS"],
                 ["faux positifs sur système mature"])),
    law("PAL-016","Transition mode sandbox/canonical","PAL","PAL-007",
        domains=["transition","sandbox"],
        palieronic=True,
        examples=["bascule visualisation sandbox vs canonical"],
        equations=["mode_view ∈ {canonical,sandbox,both}"],
        description="Transition palieronique de mode de visualisation entre sandbox et canonical.",
        S_local=0.82,S_global=0.71,weight=0.60,
        frames=f(["mode courant"],
                 fr_inter(("meso","PAL"),("macro","UX")),
                 ["politique de mode systémique"],
                 ["toggle UI"],
                 ["confusion user si transition pas explicite"])),
    law("GHUC-026","Compression de log audit","GHUC","GHUC-002",
        domains=["compression","log"],
        examples=["logs anciens compressés en summaries"],
        equations=["compress_log(t<T) = aggregated"],
        description="Compression des logs d'audit anciens en summaries pour storage.",
        S_local=0.83,S_global=0.72,weight=0.61,
        frames=f(["logs t<T"],
                 fr_inter(("meso","GHUC"),("macro","stockage long terme")),
                 ["politique stockage globale"],
                 ["aggregation par fenêtre"],
                 ["perte de granularité"])),
    law("WP12-034","Critère d'alignement avec spec","WP12","WP12-001",
        domains=["alignement","spec"],
        examples=["loi conforme à sa spec déclarée"],
        equations=["align(L, L.spec) ⟺ behavior(L) ⊆ spec_allowed"],
        description="Loi alignée avec sa spec déclarée (comportement ⊆ spec autorisée).",
        S_local=0.86,S_global=0.75,weight=0.65,
        frames=f(["loi L et sa spec"],
                 fr_inter(("meso","WP12"),("macro","contract programming")),
                 ["spec globale du système"],
                 ["test conformité"],
                 ["spec souvent informelle"])),
    law("PAL-017","Cycle de vie palieronique","PAL","PAL-001",
        domains=["lifecycle","palieronique"],
        palieronic=True,
        examples=["loi : sandbox → canonical → fractal_demonstrated"],
        equations=["lifecycle = [sandbox, review, canonical, μ1, μ0]"],
        description="Cycle de vie d'une loi traversant les paliers sandbox → μ0.",
        S_local=0.85,S_global=0.74,weight=0.64,
        frames=f(["loi et état courant"],
                 fr_inter(("meso","PAL"),("macro","gouvernance")),
                 ["distribution lifecycle globale"],
                 ["timeline + état courant"],
                 ["beaucoup de lois bloquées en review"])),
    law("WP11-034","Métrique de progression structurelle","WP11","WP11-007",
        domains=["progression","métrique"],
        examples=["évolution HS par version graph"],
        equations=["progression = HS(v_n) - HS(v_0)"],
        description="Métrique de progression structurelle entre versions du graph.",
        S_local=0.87,S_global=0.77,weight=0.67,
        frames=f(["versions historique"],
                 fr_inter(("meso","WP11"),("macro","monitoring")),
                 ["trend HS global"],
                 ["diff HS entre versions"],
                 ["progression non-monotone possible"])),
    law("GHUC-027","Refactor batch sécurisé","GHUC","GHUC-007",
        domains=["refactor","batch"],
        examples=["refactor de N lois avec rollback en cas d'échec"],
        equations=["refactor(batch) ∨ rollback_full(batch)"],
        description="Refactor par batch avec rollback complet si échec d'un seul élément.",
        S_local=0.88,S_global=0.78,weight=0.69,
        frames=f(["batch de lois"],
                 fr_inter(("meso","GHUC"),("systémique","gouvernance")),
                 ["politique refactor globale"],
                 ["transaction-like"],
                 ["coût rollback sur grand batch"])),
    law("WP12-035","Critère de degradation gracieuse","WP12","WP12-001",
        domains=["degradation","gracieuse"],
        examples=["réponse partielle plutôt qu'erreur 500"],
        equations=["if error ⇒ partial_response(available_data)"],
        description="Préférence pour degradation gracieuse plutôt qu'échec brutal.",
        S_local=0.87,S_global=0.77,weight=0.67,
        frames=f(["erreur survenue"],
                 fr_inter(("meso","WP12"),("macro","UX")),
                 ["politique UX systémique"],
                 ["partial_response_handler"],
                 ["risque de masquer des problèmes critiques"])),

    # ────── LLM COGNITIF RAFFINEMENT (10) ──────
    law("ULG-021","Embedding compositionnel additif","ULG","ULG-010",
        domains=["embedding","compositionnel"],
        examples=["emb(king)-emb(man)+emb(woman) ≈ emb(queen)"],
        equations=["emb(compose(t1,t2)) ≈ f(emb(t1),emb(t2))"],
        description="Compositionnalité additive approximative des embeddings.",
        S_local=0.83,S_global=0.72,weight=0.61,
        frames=f(["paire de tokens"],
                 fr_inter(("meso","ULG"),("macro","représentations distribuées")),
                 ["espace global d'embeddings"],
                 ["test analogies"],
                 ["compositionnalité incomplète"])),
    law("SDE-023","Self-attention multi-tête","SDE","SDE-008",
        domains=["attention","multi-tête"],
        examples=["8 heads parallèles avec patterns distincts"],
        equations=["attn = ⊕_h attn_head_h"],
        description="Mécanisme d'attention multi-tête concatenant patterns parallèles.",
        S_local=0.84,S_global=0.73,weight=0.62,
        frames=f(["séquence d'inputs"],
                 fr_inter(("meso","SDE"),("macro","Transformer architecture")),
                 ["champ global d'attention"],
                 ["dot-product softmax"],
                 ["coût quadratique en longueur"])),
    law("ULG-022","Continuation latente","ULG","ULG-009",
        domains=["continuation","latente"],
        examples=["next-token prediction à partir d'embedding"],
        equations=["next(t1...tn) = decode(emb(t1...tn))"],
        description="Prédiction du token suivant via décodage d'embedding contextualisé.",
        S_local=0.85,S_global=0.74,weight=0.63,
        frames=f(["séquence + embedding contextualisé"],
                 fr_inter(("meso","ULG"),("macro","autoregression")),
                 ["distribution next-token globale"],
                 ["softmax sur vocab"],
                 ["biais de fréquence sur vocab"])),
    law("ULG-023","Beam search anti-collapse","ULG","ULG-022",
        domains=["beam","anti-collapse"],
        examples=["maintenir K beams divers durant génération"],
        equations=["beams(t+1) = top_K diverse(extend(beams(t)))"],
        description="Beam search avec maintien de diversité (anti-mode-collapse).",
        S_local=0.83,S_global=0.72,weight=0.61,
        frames=f(["beams courants"],
                 fr_inter(("meso","ULG"),("macro","sampling strategies")),
                 ["politique diversité globale"],
                 ["mesure diversité par paire"],
                 ["coût computation × K"])),
    law("SDE-024","Position embedding","SDE","SDE-008",
        domains=["position","embedding"],
        examples=["RoPE, ALiBi, learned positional"],
        equations=["pos_emb(i) ∈ R^d"],
        description="Encodage positionnel pour mécanisme d'attention.",
        S_local=0.82,S_global=0.71,weight=0.60,
        frames=f(["position i"],
                 fr_inter(("meso","SDE"),("macro","architecture LLM")),
                 ["champ positionnel global"],
                 ["RoPE/ALiBi/learned"],
                 ["limite à context_length max"])),
    law("ULG-024","Tokenization invariante","ULG","ULG-013",
        domains=["tokenization","invariance"],
        examples=["BPE/SentencePiece stable cross-modèle"],
        equations=["tokenize(x) déterministe"],
        description="Tokenisation déterministe et stable cross-modèle (BPE/SP).",
        S_local=0.85,S_global=0.74,weight=0.63,
        frames=f(["chaîne x"],
                 fr_inter(("meso","ULG"),("macro","préprocessing LLM")),
                 ["vocab global cross-modèle"],
                 ["BPE/SentencePiece"],
                 ["vocab fixe — OOV problème"])),
    law("UDE-036","Retrieval augmenté generation (RAG)","UDE","UDE-009",
        domains=["RAG","retrieval"],
        examples=["query → retrieve docs → generate avec docs"],
        equations=["response = generate(query | retrieve(query))"],
        description="Retrieval-Augmented Generation : génération conditionnée à des docs récupérés.",
        S_local=0.92,S_global=0.82,weight=0.74,
        frames=f(["query"],
                 fr_inter(("meso","UDE"),("macro","RAG"),("systémique","anti-hallucination")),
                 ["docs corpus global"],
                 ["pipeline retrieve→gen"],
                 ["dépend qualité retriever"])),
    law("SDE-025","Chain-of-thought prompting","SDE","SDE-009",
        domains=["CoT","raisonnement"],
        examples=["« step by step » améliore raisonnement"],
        equations=["response_quality(CoT prompt) > response_quality(direct)"],
        description="Prompting par chain-of-thought améliore qualité raisonnement.",
        S_local=0.86,S_global=0.75,weight=0.65,
        frames=f(["query"],
                 fr_inter(("meso","SDE"),("macro","prompt engineering")),
                 ["politique prompting globale"],
                 ["benchmark CoT vs direct"],
                 ["coût latence × N steps"])),
    law("ULG-025","Distillation de modèle","ULG","ULG-012",
        domains=["distillation","modèle"],
        examples=["modèle léger imitant modèle large"],
        equations=["small(x) ≈ large(x) sur distrib P"],
        description="Distillation : modèle léger appris pour imiter modèle large.",
        S_local=0.84,S_global=0.73,weight=0.62,
        frames=f(["paire (small, large)"],
                 fr_inter(("meso","ULG"),("macro","compression modèle")),
                 ["distribution P globale"],
                 ["loss KL divergence"],
                 ["dégradation sur distrib OOD"])),
    law("DVE-022","Few-shot variant generation","DVE","DVE-001",
        domains=["few-shot","variant"],
        examples=["3 exemples in-context guident génération"],
        equations=["gen(x | examples) better than gen(x)"],
        description="Génération guidée par few-shot examples in-context.",
        S_local=0.85,S_global=0.74,weight=0.64,
        frames=f(["query + few-shot examples"],
                 fr_inter(("meso","DVE"),("macro","in-context learning")),
                 ["champ d'examples globaux"],
                 ["selection examples relevant"],
                 ["context window limit"])),

    # ────── USER / ÉTHIQUE (8) ──────
    law("WP12-036","Critère d'explicabilité user","WP12","WP12-019",
        domains=["explicabilité","user"],
        examples=["réponse expliquée en termes accessibles"],
        equations=["explain(response, user_level)"],
        description="Réponse adaptée au niveau d'expertise user (explicabilité gradée).",
        S_local=0.86,S_global=0.75,weight=0.65,
        frames=f(["réponse + profil user"],
                 fr_inter(("meso","WP12"),("macro","UX cognitive")),
                 ["politique d'explicabilité globale"],
                 ["modèle level user"],
                 ["mauvaise modélisation user → mauvaise adaptation"])),
    law("WP12-037","Critère de non-manipulation","WP12","WP12-021",
        domains=["non-manipulation","éthique"],
        examples=["pas de dark patterns, pas de pression user"],
        equations=["¬manipulate(response, user_choice)"],
        description="Refus de toute manipulation cognitive de l'utilisateur (dark patterns).",
        S_local=0.93,S_global=0.83,weight=0.76,
        frames=f(["réponse + impact user"],
                 fr_inter(("meso","WP12"),("macro","éthique IA")),
                 ["politique éthique systémique"],
                 ["audit pattern manipulation"],
                 ["frontière éthique contextuelle"])),
    law("WP12-038","Critère de respect user-time","WP12","WP12-035",
        domains=["respect","temps"],
        examples=["réponse concise sauf demande explicite"],
        equations=["len(response) ≤ minimum_useful"],
        description="Respect du temps utilisateur : réponses concises par défaut.",
        S_local=0.84,S_global=0.73,weight=0.62,
        frames=f(["réponse"],
                 fr_inter(("meso","WP12"),("macro","UX")),
                 ["politique conciseness globale"],
                 ["mesure longueur vs nécessité"],
                 ["risque sous-information"])),
    law("WP12-039","Critère d'opt-out","WP12","WP12-020",
        domains=["opt-out","user"],
        examples=["user peut refuser tracking et continuer à utiliser"],
        equations=["service(user) reste fonctionnel sans consent_optional"],
        description="Service runtime reste fonctionnel même si user refuse consent optionnel.",
        S_local=0.88,S_global=0.78,weight=0.68,
        frames=f(["user et opt-out"],
                 fr_inter(("meso","WP12"),("macro","RGPD")),
                 ["politique opt-out systémique"],
                 ["check service availability sans consent"],
                 ["features réduites possibles"])),
    law("SDE-026","Adaptation au niveau cognitif user","SDE","SDE-014",
        domains=["adaptation","cognitif"],
        examples=["vocabulaire ajusté à expertise user"],
        equations=["vocab(response) ⊆ vocab_familier(user)"],
        description="Adaptation du vocabulaire et concepts au niveau cognitif user.",
        S_local=0.85,S_global=0.74,weight=0.64,
        frames=f(["réponse + profil user"],
                 fr_inter(("meso","SDE"),("macro","ToM")),
                 ["politique adaptation systémique"],
                 ["modèle cognitif user"],
                 ["modélisation imparfaite"])),
    law("WP12-040","Critère d'audit user-initiable","WP12","WP12-019",
        domains=["audit","user"],
        examples=["user lance audit sur 1 réponse particulière"],
        equations=["user.request_audit(response) → full_trace"],
        description="L'utilisateur peut initier un audit complet sur n'importe quelle réponse.",
        S_local=0.87,S_global=0.77,weight=0.67,
        frames=f(["demande d'audit user"],
                 fr_inter(("meso","WP12"),("macro","ZenRuntime"),("systémique","transparence")),
                 ["politique audit user systémique"],
                 ["log + replay"],
                 ["coût audit on-demand"])),
    law("WP12-041","Critère de vie privée par défaut","WP12","WP12-027",
        domains=["privacy","default"],
        examples=["aucune mémoire persistante par défaut user"],
        equations=["default(privacy) = strict"],
        description="Vie privée stricte par défaut ; opt-in pour features mémoire.",
        S_local=0.91,S_global=0.81,weight=0.73,
        frames=f(["nouveau user"],
                 fr_inter(("meso","WP12"),("macro","privacy by default")),
                 ["politique privacy globale"],
                 ["check defaults"],
                 ["UX peut souffrir de la privacy stricte"])),
    law("WP11-035","Mesure de satisfaction user","WP11","WP11-001",
        domains=["satisfaction","user"],
        examples=["score satisfaction post-interaction"],
        equations=["sat = user_rating"],
        description="Mesure de satisfaction user post-interaction (signal de calibration).",
        S_local=0.81,S_global=0.69,weight=0.58,
        frames=f(["interaction"],
                 fr_inter(("meso","WP11"),("macro","UX metrics")),
                 ["distribution satisfaction globale"],
                 ["rating explicite ou implicite"],
                 ["bias par self-selection"])),

    # ────── TRANSVERSE / ISO (14) ──────
    law("GHUC-028","Méta-règle d'orthogonalité familiale","GHUC","GHUC-016",
        domains=["méta","orthogonalité"],
        examples=["familles canoniques restent conceptuellement distinctes"],
        equations=["overlap(F1,F2) ≤ θ_orth"],
        description="Méta-règle : les 8 familles canoniques restent orthogonales.",
        S_local=0.89,S_global=0.79,weight=0.70,
        frames=f(["paire de familles"],
                 fr_inter(("meso","GHUC"),("macro","R-CORE-11")),
                 ["matrice orthogonalité globale"],
                 ["overlap mesuré"],
                 ["seuil θ_orth subjectif"])),
    law("GHUC-029","Audit de cohérence des compositions","GHUC","GHUC-007",
        domains=["audit","compositions"],
        examples=["chaque composition a invariants explicites"],
        equations=["each composition.preserved ≠ ∅"],
        description="Audit que chaque composition a au moins un invariant préservé déclaré.",
        S_local=0.91,S_global=0.81,weight=0.73,
        frames=f(["liste compositions"],
                 fr_inter(("meso","GHUC"),("macro","R-CORE-3")),
                 ["registre global compositions"],
                 ["scan compositions[]"],
                 ["invariants vagues passent test"])),
    law("WP11-036","Score d'unification cross-famille","WP11","WP11-007",
        domains=["unification","cross-famille"],
        examples=["nombre d'iso edges entre familles"],
        equations=["unify_score = |iso_edges| / C(n_fam, 2)"],
        description="Score d'unification mesuré par densité d'iso edges cross-famille.",
        S_local=0.85,S_global=0.74,weight=0.64,
        frames=f(["graphe + iso edges"],
                 fr_inter(("meso","WP11"),("macro","topologie graphe")),
                 ["unification globale"],
                 ["count iso / pairs"],
                 ["seuil θ"])),
    law("UDE-037","Découverte par bridge iso","UDE","UDE-001",
        domains=["découverte","iso"],
        examples=["nouvelle loi via bridge iso entre familles"],
        equations=["L_new = bridge(F1.L1, F2.L2) avec invariants"],
        description="Découverte de loi par construction de bridge iso entre familles.",
        S_local=0.86,S_global=0.75,weight=0.65,
        frames=f(["paire (L1,L2)"],
                 fr_inter(("meso","UDE"),("macro","unification")),
                 ["politique découverte iso globale"],
                 ["candidate bridges automatique"],
                 ["bridge sans invariant inadmissible"])),
    law("SDE-027","Skopein observationnel composé","SDE","SDE-006",
        domains=["Skopein","observation"],
        examples=["chaîne d'observations préservant invariant"],
        equations=["⟨S_obs1∘S_obs2∘...⟩ Skopein-cohérent"],
        description="Composition d'observations préservant l'invariant Skopein global.",
        S_local=0.83,S_global=0.72,weight=0.61,
        frames=f(["chaîne d'observations"],
                 fr_inter(("meso","SDE")),
                 ["semigroupe global"],
                 ["test invariance"],
                 ["instabilité au-delà 4 termes"])),
    law("PAL-018","Cycle palieronique calibration","PAL","PAL-008",
        domains=["cycle","calibration"],
        palieronic=True,
        examples=["calibration périodique selon cycles d'usage"],
        equations=["calibrate every T_cycle"],
        description="Calibration périodique (palieronique) selon cycles d'usage observés.",
        S_local=0.82,S_global=0.71,weight=0.60,
        frames=f(["historique usage"],
                 fr_inter(("meso","PAL"),("macro","Adaptive")),
                 ["politique cycle globale"],
                 ["timer + audit"],
                 ["cycle T arbitraire"])),
    law("DVE-023","Variant fingerprinting","DVE","DVE-013",
        domains=["fingerprint","variant"],
        examples=["hash unique par variante générée"],
        equations=["fp(v) = SHA256(canonical(v))"],
        description="Fingerprint hash de chaque variante générée pour détection doublons.",
        S_local=0.84,S_global=0.73,weight=0.62,
        frames=f(["variante v"],
                 fr_inter(("meso","DVE")),
                 ["registre fingerprints globaux"],
                 ["SHA256"],
                 ["coût stockage"])),
    law("WP12-042","Critère de conservation des invariants","WP12","WP12-015",
        domains=["conservation","invariants"],
        examples=["modification ne casse aucun invariant"],
        equations=["modif(L) ⇒ ∀ inv : preserved"],
        description="Toute modification doit préserver tous les invariants déjà démontrés.",
        S_local=0.92,S_global=0.82,weight=0.74,
        frames=f(["modification proposée"],
                 fr_inter(("meso","WP12"),("macro","R-CORE-6")),
                 ["politique conservation systémique"],
                 ["check invariant par invariant"],
                 ["coût croissant avec |invariants|"])),
    law("UDE-038","Mémoire collective inter-session","UDE","UDE-014",
        domains=["mémoire","collective"],
        examples=["leçons apprises traversant les sessions"],
        equations=["mem_coll = ⋃_session distill(mem_session)"],
        description="Mémoire collective constitutuée des distillations inter-sessions.",
        S_local=0.83,S_global=0.72,weight=0.61,
        frames=f(["historique sessions"],
                 fr_inter(("meso","UDE"),("macro","apprentissage continu")),
                 ["mémoire systémique globale"],
                 ["aggregation"],
                 ["bias accumulation"])),
    law("ULG-026","Robustesse multi-modèles cross-validation","ULG","ULG-008",
        domains=["robustesse","cross-modèles"],
        examples=["loi validée sur 3 modèles distincts"],
        equations=["valid(L) ⟺ valid_M1(L) ∧ valid_M2(L) ∧ valid_M3(L)"],
        description="Validation cross-modèles : loi acceptée si robuste sur ≥3 modèles.",
        S_local=0.86,S_global=0.75,weight=0.65,
        frames=f(["loi + modèles test"],
                 fr_inter(("meso","ULG"),("macro","WP-12 admissibilité")),
                 ["politique validation systémique"],
                 ["test sur ensemble modèles"],
                 ["coût × N modèles"])),
    law("SDE-028","Attention auto-régulée","SDE","SDE-008",
        domains=["attention","auto-régulation"],
        examples=["attention diminue sur tokens à faible score"],
        equations=["attn(t) → 0 si score(t) < θ"],
        description="Auto-régulation de l'attention : ignore tokens à faible score.",
        S_local=0.83,S_global=0.72,weight=0.61,
        frames=f(["distribution attention"],
                 fr_inter(("meso","SDE"))
                 ,["politique attention globale"],
                 ["seuil dynamique"],
                 ["tokens importants peuvent être manqués"])),
    law("WP11-037","Score d'adaptabilité Adaptive","WP11","WP11-001",
        domains=["adaptabilité","Adaptive"],
        examples=["fréquence de calibration coefficients"],
        equations=["adapt_score = N_calibrations / Δt"],
        description="Score d'adaptabilité de l'OracleAdaptive (taux de recalibration).",
        S_local=0.84,S_global=0.73,weight=0.62,
        frames=f(["historique calibrations"],
                 fr_inter(("meso","WP11"),("macro","Adaptive")),
                 ["adaptabilité globale"],
                 ["compteur calibrations"],
                 ["sur-adaptation = thrashing"])),
    law("GHUC-030","Méta-fractalité de la consolidation","GHUC","GHUC-001",
        domains=["méta","fractalité"],
        examples=["consolidation à plusieurs échelles itérée"],
        equations=["consolidate_n(graph) = consolidate(consolidate_{n-1}(graph))"],
        description="Méta-fractalité : consolidation itérée à plusieurs échelles donne motif fractal.",
        S_local=0.86,S_global=0.75,weight=0.65,
        frames=f(["graphe et nombre d'itérations"],
                 fr_inter(("meso","GHUC"),("macro","R-CORE-3 composition")),
                 ["méta-graphe global"],
                 ["fixed-point analysis"],
                 ["convergence non garantie"])),
    law("PAL-019","Saut palieronique méta-cohérent","PAL","PAL-001",
        domains=["saut","méta"],
        palieronic=True,
        examples=["promotion μ1→μ0 d'une racine canonique"],
        equations=["promote_tier(L, μ_n+1) ⟺ Core_OK ∧ HS↑"],
        description="Saut palieronique de promotion de tier (μ1→μ0) sous validation Core.",
        S_local=0.87,S_global=0.77,weight=0.67,
        frames=f(["loi candidate à promotion tier"],
                 fr_inter(("meso","PAL"),("macro","Oracle Core"),("systémique","gouvernance")),
                 ["pipeline promotion globale"],
                 ["check Core + HS"],
                 ["promotion irréversible — audit"])),
]


NEW_EDGES_TYPED = [
    {"source":"WP11-020","target":"WP12-011","kind":"iso",
     "invariants":["typage strict frames ↔ typage strict edges (R-CORE-8)"],"weight":0.70},
    {"source":"DVE-018","target":"SDE-016","kind":"iso",
     "invariants":["refus génératif ↔ refus structuré sur lacune"],"weight":0.70},
    {"source":"DVE-020","target":"WP12-029","kind":"iso",
     "invariants":["anti-fabrication citations ↔ citation obligatoire en réponse"],"weight":0.72},
    {"source":"UDE-036","target":"WP11-011","kind":"iso",
     "invariants":["RAG ↔ audit hallucination par composition (vérification grounding)"],"weight":0.70},
    {"source":"GHUC-022","target":"GHUC-023","kind":"iso",
     "invariants":["promotion auto ↔ démotion auto — pipeline gouvernance"],"weight":0.72},
    {"source":"WP12-041","target":"WP12-020","kind":"iso",
     "invariants":["privacy by default ↔ critère consentement"],"weight":0.70},

    # quelques contradicts pour calibration
    {"source":"DVE-019","target":"DVE-020","kind":"contradicts","weight":0.50,
     "domain":"confiance générative vs anti-fabrication stricte (trade-off)"},
    {"source":"DVE-020","target":"DVE-019","kind":"contradicts","weight":0.50,
     "domain":"confiance générative vs anti-fabrication stricte (trade-off)"},
]


NEW_COMPOSITIONS = [
    {"pair":["DVE-018","SDE-016"],"operator":"DVE-018 ∘ SDE-016",
     "preserved":["refus génératif + refus structuré : double-protection anti-hallu runtime"],
     "test_input":"query manquante de lois support",
     "test_output":"refus avec citation des lois manquantes + suggestion exploration",
     "delta_S_global":0.02,"status":"admissible"},
    {"pair":["DVE-020","WP12-029"],"operator":"DVE-020 ∘ WP12-029",
     "preserved":["anti-fabrication + citation obligatoire : pipeline citation honnête"],
     "test_input":"réponse contenant une citation",
     "test_output":"citation vérifiée présente dans CanonicalGraph",
     "delta_S_global":0.02,"status":"admissible"},
    {"pair":["UDE-036","WP11-011"],"operator":"UDE-036 ∘ WP11-011",
     "preserved":["RAG + audit hallucination : grounding vérifié"],
     "test_input":"query → docs récupérés → réponse",
     "test_output":"réponse 100% grounded sur docs cités",
     "delta_S_global":0.02,"status":"admissible"},
    {"pair":["GHUC-022","GHUC-023"],"operator":"GHUC-022 ⊕ GHUC-023",
     "preserved":["promotion auto + démotion auto — équilibre dynamique"],
     "test_input":"sandbox + canonical en évolution",
     "test_output":"flux contrôlé lois entre couches",
     "delta_S_global":0.01,"status":"admissible"},
    {"pair":["WP11-024","WP11-026"],"operator":"WP11-024 ∘ WP11-026",
     "preserved":["audit incrémental + réplication : audit performant ET vérifié"],
     "test_input":"diff sur graph + 2 Oracles",
     "test_output":"verdict identique sur les 2 Oracles avec coût réduit",
     "delta_S_global":0.01,"status":"admissible"},
    {"pair":["UDE-024","UDE-029"],"operator":"UDE-024 ∘ UDE-029",
     "preserved":["WM bornée + compression LT : architecture mémoire tractable"],
     "test_input":"flux d'événements continus",
     "test_output":"mémoire stable bornée avec retention long-terme",
     "delta_S_global":0.0,"status":"admissible"},
    {"pair":["WP12-038","WP12-035"],"operator":"WP12-038 ∘ WP12-035",
     "preserved":["respect user-time + degradation gracieuse : UX honnête sous contrainte"],
     "test_input":"erreur serveur",
     "test_output":"réponse partielle concise",
     "delta_S_global":0.01,"status":"admissible"},
]


def existing_ids(d): return {n["id"] for n in d["nodes"]}


def parents_of(g, nid):
    return [e["target"] for e in g["edges"] if e["kind"]=="parent" and e["source"]==nid]


def children_of(g, nid):
    return [e["source"] for e in g["edges"] if e["kind"]=="parent" and e["target"]==nid]


def count_compositions_for(law_id, data, planned, new_edges, new_comps):
    composes = set()
    cand = next((c for c in planned if c["id"] == law_id), None)
    if cand and cand.get("parent"):
        composes.add(cand["parent"])
        parent_id = cand["parent"]
        parent_cand = next((c for c in planned if c["id"] == parent_id), None)
        if parent_cand and parent_cand.get("parent"):
            composes.add(parent_cand["parent"])
        else:
            composes.update(parents_of(data, parent_id))
        for other in planned:
            if other["id"] != law_id and other.get("parent") == cand["parent"]:
                composes.add(other["id"])
        for sib in children_of(data, cand["parent"]):
            if sib != law_id: composes.add(sib)
    for other in planned:
        if other.get("parent") == law_id: composes.add(other["id"])
    for child in children_of(data, law_id): composes.add(child)
    for e in data["edges"]:
        if e["kind"] == "parent":
            if e["source"] == law_id: composes.add(e["target"])
            if e["target"] == law_id: composes.add(e["source"])
        elif e["kind"] in ("iso","contradicts","related","absorbed_into","depends"):
            if e["source"] == law_id: composes.add(e["target"])
            if e["target"] == law_id: composes.add(e["source"])
    for e in new_edges:
        if e["source"] == law_id: composes.add(e["target"])
        if e["target"] == law_id: composes.add(e["source"])
    for c in new_comps:
        if law_id in c["pair"]:
            for p in c["pair"]:
                if p != law_id: composes.add(p)
    for c in data.get("compositions", []):
        if law_id in c.get("pair", []):
            for p in c["pair"]:
                if p != law_id: composes.add(p)
    composes.discard(law_id)
    return composes


def run():
    data = json.loads(DATA.read_text(encoding="utf-8"))
    by_id = existing_ids(data)
    quarantine = []
    integrated = []
    integration_log = []

    for cand in CANDIDATES:
        cid = cand["id"]
        if cand["family"] not in CANONICAL_FAMILIES:
            quarantine.append({"id":cid,"reason":"family not canonical","phase":1}); continue
        f_ = cand["frames"]
        ok2 = True
        for k in ("local","intermediate","global","proxies","limits"):
            if k not in f_:
                quarantine.append({"id":cid,"reason":f"frames.{k} missing","phase":2}); ok2=False; break
        if not ok2: continue
        if not f_["intermediate"]:
            quarantine.append({"id":cid,"reason":"intermediate empty","phase":2}); continue
        if not f_["limits"]:
            quarantine.append({"id":cid,"reason":"limits empty","phase":2}); continue
        if any(e["level"] not in INTERMEDIATE_LEVELS for e in f_["intermediate"]):
            quarantine.append({"id":cid,"reason":"level invalid","phase":2}); continue

        if len(cand["html_description"]) < 40:
            quarantine.append({"id":cid,"reason":"description short","phase":3}); continue
        if not (cand["equations"] or cand["examples"]):
            quarantine.append({"id":cid,"reason":"no grounding","phase":3}); continue

        comps = count_compositions_for(cid, data, CANDIDATES, NEW_EDGES_TYPED, NEW_COMPOSITIONS)
        if len(comps) < 3:
            quarantine.append({"id":cid,"reason":f"comps {len(comps)}<3","phase":4,"found":list(comps)}); continue

        integrated.append(cand)
        integration_log.append({"id":cid,"family":cand["family"],"parent":cand["parent"],
                                "compositions_count":len(comps),
                                "S_local":cand["S_local"],"S_global":cand["S_global"],
                                "weight":cand["weight"]})

    new_nodes = []
    new_parent_edges = []
    for cand in integrated:
        if cand["id"] in by_id: continue
        node = {
            "id":cand["id"],"title":cand["title"],
            "canonical":cand["canonical"],"palieronic":cand["palieronic"],
            "family":cand["family"],"attractor_tier":None,
            "domains":cand["domains"],"examples":cand["examples"],
            "html_description":cand["html_description"],"equations":cand["equations"],
            "S_local":cand["S_local"],"S_global":cand["S_global"],
            "stability":cand["stability"],"weight":cand["weight"],
            "frames":cand["frames"],"runtime_admissible":True,
        }
        new_nodes.append(node)
        new_parent_edges.append({"source":cand["id"],"target":cand["parent"],"kind":"parent"})

    data["nodes"].extend(new_nodes)
    data["edges"].extend(new_parent_edges)
    data["edges"].extend(NEW_EDGES_TYPED)
    data.setdefault("compositions",[]).extend(NEW_COMPOSITIONS)

    data["p0_5_meta"] = data.get("p0_5_meta", {})
    data["p0_5_meta"]["p3_integrated_count"] = len(integrated)
    data["p0_5_meta"]["p3_quarantined_count"] = len(quarantine)
    data["p0_5_meta"]["p3_timestamp"] = "2026-05-15T20:50:00+02:00"
    data["p0_5_meta"]["p3_mission_id"] = "ZORAN_P3_DEMONSTRATED_EXPANSION_100_LAWS_20260515"
    data["p0_5_meta"]["compositions_demonstrated"] = len(data["compositions"])

    DATA.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    QUARANTINE.parent.mkdir(parents=True, exist_ok=True)
    QUARANTINE.write_text(json.dumps({
        "mission_id":"ZORAN_P3_DEMONSTRATED_EXPANSION_100_LAWS_20260515",
        "candidates_total":len(CANDIDATES),
        "integrated_count":len(integrated),
        "quarantined_count":len(quarantine),
        "quarantined":quarantine
    }, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    INTEGRATION.write_text(json.dumps({
        "mission_id":"ZORAN_P3_DEMONSTRATED_EXPANSION_100_LAWS_20260515",
        "integrated":integration_log
    }, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    print(f"P3 candidates : {len(CANDIDATES)}")
    print(f"Integrated    : {len(integrated)}")
    print(f"Quarantined   : {len(quarantine)}")
    print(f"New nodes     : {len(new_nodes)}")
    print(f"New edges     : {len(new_parent_edges)+len(NEW_EDGES_TYPED)}")
    print(f"New comps     : {len(NEW_COMPOSITIONS)}")
    print(f"Total comps   : {len(data['compositions'])}")


if __name__ == "__main__":
    run()
