#!/usr/bin/env python3
"""ZORAN Mission 1 — 100 lois réversibles ajoutées à DiscoverySandbox.

PIPELINE OBLIGATOIRE :
  Candidate → DiscoverySandbox → OracleValidation → CompositionTests
  → StressTests → CanonicalCandidate → CanonicalGraph

Chaque loi sandbox porte des métadonnées de réversibilité strictes :
  - reversible: true
  - rollback_dependencies: []      (lois à retirer ensemble)
  - canonical_status: "sandbox"
  - sandbox_origin: "P4_seed_<batch_id>"
  - oracle_validation: {phase_results}
  - runtime_admissible: false       (NON chargée par ZenRuntime)

AUCUNE de ces lois n'entre directement dans laws.json (CanonicalGraph).
Elles restent dans laws_sandbox.json jusqu'à promotion explicite via
tools/sandbox_pipeline.py promote.
"""
from __future__ import annotations
import json
import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CANONICAL_DATA = ROOT / "app" / "data" / "laws.json"
SANDBOX_DATA = ROOT / "app" / "data" / "laws_sandbox.json"
SANDBOX_LOG = ROOT / "audit" / "SANDBOX_INTEGRATION_LOG.json"
QUARANTINE_LOG = ROOT / "audit" / "SANDBOX_QUARANTINE_LOG.json"

CANONICAL_FAMILIES = {"ULG","DVE","UDE","GHUC","WP11","WP12","SDE","PAL"}
INTERMEDIATE_LEVELS = {"micro","meso","macro","systémique"}
BATCH_ID = "P4_REV_001"


def f(local, intermediate, global_, proxies, limits):
    return {"local":local,"intermediate":intermediate,"global":global_,
            "proxies":proxies,"limits":limits}


def fr_inter(*items): return [{"level":l,"scope":s} for l,s in items]


def law(id, title, family, parent, *, canonical=False, palieronic=False,
        domains, examples=None, equations=None, description,
        S_local, S_global, weight, frames,
        rollback_deps=None):
    """Build a sandbox law candidate dict.

    rollback_deps: lois (sandbox ou canonical) à retirer en cascade si on
    rollback cette loi (ex. les lois sandbox qui ont celle-ci comme parent).
    """
    return {
        "id": id, "title": title, "family": family, "parent": parent,
        "canonical": canonical, "palieronic": palieronic,
        "domains": list(domains), "examples": list(examples or []),
        "equations": list(equations or []),
        "html_description": description,
        "S_local": S_local, "S_global": S_global, "weight": weight,
        "stability": "exploratoire",
        "frames": frames,
        "_rollback_deps_planned": list(rollback_deps or []),
    }


# ─────────────────── 100 SANDBOX CANDIDATES ─────────────────────
# Distribution équilibrée sur les 8 familles canoniques.
# Tous parentés à des lois CANONIQUES existantes (laws.json) pour
# garantir composition ≥ 3 facilement.

CANDIDATES = [
    # ────── ULG (12) — extensions exploratoires ──────
    law("SBX-ULG-101","Embedding hypergraphique","ULG","ULG-008",
        domains=["embedding","hypergraphe"],
        examples=["embeddings sur arêtes hypergraphiques d'ordre 3+"],
        equations=["emb_hyper(e) ∈ R^d où e relie ≥ 3 nœuds"],
        description="Représentation embedding sur hyperarêtes (relations d'ordre supérieur).",
        S_local=0.78,S_global=0.66,weight=0.50,
        frames=f(["hyperarête e d'ordre k≥3"],
                 fr_inter(("meso","ULG"),("macro","théorie hypergraphes")),
                 ["topologie hypergraphique globale"],
                 ["projection sur graphe + agrégation"],
                 ["coût exponentiel en k","sémantique hyperarête contextuelle"])),
    law("SBX-ULG-102","Champ tensoriel latent","ULG","ULG-009",
        domains=["tenseur","latent"],
        examples=["représentation par tenseurs d'ordre 3+"],
        equations=["T_latent ∈ R^{d_1×d_2×d_3}"],
        description="Représentation latente par champ tensoriel d'ordre supérieur (au-delà des matrices).",
        S_local=0.76,S_global=0.64,weight=0.48,
        frames=f(["tenseur T à plusieurs modes"],
                 fr_inter(("meso","ULG"),("macro","algèbre multilinéaire")),
                 ["espace tensoriel global"],
                 ["décomposition tucker/CP"],
                 ["coût stockage croissant","interprétation difficile"])),
    law("SBX-ULG-103","Continuum lexical fluide","ULG","ULG-010",
        domains=["continuum","lexique"],
        examples=["graduation continue entre concepts proches"],
        equations=["lex_continuum ⊂ R^d, distance(x,y) graduée"],
        description="Représentation continue (non-discrète) de l'espace lexical.",
        S_local=0.74,S_global=0.62,weight=0.46,
        frames=f(["paire concepts (x,y)"],
                 fr_inter(("meso","ULG"),("macro","sémantique vectorielle")),
                 ["topologie continue lexicale"],
                 ["interpolation linéaire / géodésique"],
                 ["pas toujours bien défini sur concepts disjoints"])),
    law("SBX-ULG-104","Co-référence multi-modale","ULG","ULG-014",
        domains=["co-référence","multi-modal"],
        examples=["référence texte ↔ image ↔ audio"],
        equations=["coref_mm(token, modalities) → entity"],
        description="Co-référence traversant les modalités (texte/image/audio).",
        S_local=0.72,S_global=0.60,weight=0.44,
        frames=f(["token et modalités"],
                 fr_inter(("meso","ULG"),("macro","modèles multi-modaux")),
                 ["graphe co-référence multi-modal"],
                 ["modèle alignement cross-modal"],
                 ["dépend qualité alignement initial"])),
    law("SBX-ULG-105","Stabilité translationnelle","ULG","ULG-013",
        domains=["stabilité","translation"],
        examples=["traduction préserve l'embedding sémantique"],
        equations=["‖emb(x) - emb(translate(x))‖ ≤ ε_trans"],
        description="Stabilité de l'embedding sous traduction inter-langue.",
        S_local=0.78,S_global=0.66,weight=0.50,
        frames=f(["paire (x, traduction)"],
                 fr_inter(("meso","ULG"),("macro","alignement multilingue")),
                 ["espace sémantique cross-lingue"],
                 ["test sur parallel corpus"],
                 ["dépend qualité traduction"])),
    law("SBX-ULG-106","Granularité morphémique","ULG","ULG-024",
        domains=["morphème","granularité"],
        examples=["sous-tokens morphémiques (préfixes/suffixes)"],
        equations=["token = ⨁ morphemes"],
        description="Décomposition tokenisation au niveau morphémique.",
        S_local=0.75,S_global=0.63,weight=0.47,
        frames=f(["token complexe"],
                 fr_inter(("meso","ULG"),("macro","morphologie")),
                 ["lexique morphémique global"],
                 ["analyseur morphologique"],
                 ["overhead vs BPE simple"])),
    law("SBX-ULG-107","Compositionnalité conditionnelle","ULG","ULG-021",
        domains=["compositionnalité","conditionnelle"],
        examples=["compose(a,b|ctx) ≠ compose(a,b)"],
        equations=["compose_cond(a,b|ctx) modulé par ctx"],
        description="Compositionnalité dépendante du contexte (non-strictement additive).",
        S_local=0.73,S_global=0.61,weight=0.45,
        frames=f(["paire (a,b) et ctx"],
                 fr_inter(("meso","ULG"),("macro","sémantique contextuelle")),
                 ["espace compositionnel contextualisé"],
                 ["modèle attention conditionnelle"],
                 ["non-linéarité difficile à formaliser"])),
    law("SBX-ULG-108","Symétrie sémantique latente","ULG","ULG-003",
        domains=["symétrie","sémantique"],
        examples=["antonymes occupant positions symétriques"],
        equations=["antonym(x) ↔ -emb(x) (modulo offset)"],
        description="Symétrie sémantique observable dans l'espace latent (antonymes ≈ opposés).",
        S_local=0.71,S_global=0.59,weight=0.43,
        frames=f(["paire d'antonymes"],
                 fr_inter(("meso","ULG"),("macro","sémantique structurelle")),
                 ["groupe de symétries sémantiques"],
                 ["test sur paires antonymes connus"],
                 ["pas universel — antonymes contextuels"])),
    law("SBX-ULG-109","Phase-transition lexicale","ULG","ULG-005",
        domains=["phase","transition"],
        palieronic=True,
        examples=["passage soudain de la dénotation à la connotation"],
        equations=["meaning(x|ctx) change abruptement à seuil"],
        description="Transition de phase abrupte du sens d'un mot selon contexte.",
        S_local=0.70,S_global=0.58,weight=0.42,
        frames=f(["mot x et seuil contextuel"],
                 fr_inter(("meso","ULG"),("macro","linguistique cognitive")),
                 ["distribution des transitions globales"],
                 ["détection saut sémantique par modèle"],
                 ["seuil contextuel difficile à mesurer"])),
    law("SBX-ULG-110","Embedding causal direct","ULG","ULG-001",
        domains=["embedding","causal"],
        examples=["emb capturant relations causales explicitement"],
        equations=["emb_causal(A→B) ≠ emb_causal(B→A)"],
        description="Embedding asymétrique encodant la directionnalité causale.",
        S_local=0.74,S_global=0.62,weight=0.46,
        frames=f(["paire causale (A,B)"],
                 fr_inter(("meso","ULG"),("macro","causalité")),
                 ["graphe causal global"],
                 ["test sur paires causales connues"],
                 ["causalité non observable directement"])),
    law("SBX-ULG-111","Compactification dimensionnelle adaptative","ULG","ULG-017",
        domains=["compactification","adaptatif"],
        examples=["dimension compactifiée varie selon densité locale"],
        equations=["dim_eff(x) = f(density_local(x))"],
        description="Dimensionnalité effective adaptative selon densité locale du cadre.",
        S_local=0.72,S_global=0.60,weight=0.44,
        frames=f(["voisinage d'un point latent"],
                 fr_inter(("meso","ULG")),
                 ["topologie globale variable"],
                 ["estimation densité kernel"],
                 ["calculs croisés coûteux"])),
    law("SBX-ULG-112","Quasi-isomorphisme inter-modèles","ULG","ULG-008",
        domains=["isomorphisme","inter-modèles"],
        examples=["alignement quasi-iso entre embeddings GPT et Claude"],
        equations=["align(M1, M2) → R: R·emb_M1 ≈ emb_M2 (modulo ε)"],
        description="Alignement quasi-isomorphique entre espaces d'embeddings de modèles distincts.",
        S_local=0.76,S_global=0.64,weight=0.48,
        frames=f(["paire de modèles"],
                 fr_inter(("meso","ULG"),("macro","alignement représentationnel")),
                 ["champ d'alignements globaux"],
                 ["procrustes ou linear probing"],
                 ["alignement parfait impossible"])),

    # ────── DVE (12) ──────
    law("SBX-DVE-101","Variant programmatique vérifié","DVE","DVE-002",
        domains=["variant","programmation"],
        examples=["variantes générées avec preuve formelle de correction"],
        equations=["variant_v(prog) ∧ verified(v)"],
        description="Variantes programmatiques accompagnées d'une preuve formelle.",
        S_local=0.80,S_global=0.68,weight=0.55,
        frames=f(["variante candidate avec preuve"],
                 fr_inter(("meso","DVE"),("macro","program verification")),
                 ["espace des variantes vérifiées"],
                 ["vérificateur formel sur DSL"],
                 ["coût preuve élevé","limité aux DSL formels"])),
    law("SBX-DVE-102","Mutation sémantique préservante","DVE","DVE-003",
        domains=["mutation","sémantique"],
        examples=["réécriture préservant le sens (paraphrase)"],
        equations=["mutate(x) → x' tel que sense(x) = sense(x')"],
        description="Mutation textuelle préservant strictement le sens sémantique.",
        S_local=0.78,S_global=0.66,weight=0.52,
        frames=f(["texte x à muter"],
                 fr_inter(("meso","DVE"),("macro","paraphrase")),
                 ["espace de paraphrases admissibles"],
                 ["NLI bidirectionnel"],
                 ["sens préservé approximativement"])),
    law("SBX-DVE-103","Génération avec backtracking","DVE","DVE-014",
        domains=["backtracking","génération"],
        examples=["annulation et reprise sur erreur détectée"],
        equations=["if invalid(out) → backtrack to last_valid"],
        description="Génération avec mécanisme de backtracking sur erreur détectée.",
        S_local=0.77,S_global=0.65,weight=0.51,
        frames=f(["état de génération + erreur"],
                 fr_inter(("meso","DVE"))
                 ,["politique de backtrack systémique"],
                 ["check d'invalidité périodique"],
                 ["coût latence en cas d'erreurs fréquentes"])),
    law("SBX-DVE-104","Pénalité par redondance variant","DVE","DVE-012",
        domains=["pénalité","redondance"],
        examples=["score variant - λ·similarity_to_others"],
        equations=["score(v) -= λ · max sim(v, others)"],
        description="Pénalité explicite contre les variantes trop similaires aux autres.",
        S_local=0.76,S_global=0.64,weight=0.50,
        frames=f(["set de variantes"],
                 fr_inter(("meso","DVE")),
                 ["politique diversité globale"],
                 ["similarité pairwise"],
                 ["λ arbitraire"])),
    law("SBX-DVE-105","Variant streaming différentiel","DVE","DVE-001",
        domains=["streaming","différentiel"],
        examples=["streaming token-par-token avec validation incrémentale"],
        equations=["validate(prefix) à chaque ajout"],
        description="Streaming génératif avec validation différentielle à chaque token.",
        S_local=0.75,S_global=0.63,weight=0.49,
        frames=f(["préfixe en construction"],
                 fr_inter(("meso","DVE"))
                 ,["politique streaming systémique"],
                 ["validateur incrémental"],
                 ["overhead par token"])),
    law("SBX-DVE-106","Bifurcation par méta-prompt","DVE","DVE-006",
        domains=["bifurcation","méta-prompt"],
        examples=["prompt méta induisant bifurcation explicite"],
        equations=["meta_prompt(X) → branch(X_a, X_b)"],
        description="Bifurcation déclenchée par méta-prompt explicite.",
        S_local=0.73,S_global=0.61,weight=0.47,
        frames=f(["méta-prompt"],
                 fr_inter(("meso","DVE"))
                 ,["politique méta-prompting globale"],
                 ["détection méta-prompt"],
                 ["méta-prompts mal structurés ineffectifs"])),
    law("SBX-DVE-107","Variant temporel auto-corrigé","DVE","DVE-013",
        domains=["temporel","auto-correction"],
        examples=["variante révisée si erreur détectée a posteriori"],
        equations=["revise(v_t, error) → v_{t+1}"],
        description="Auto-correction temporelle de variante détectée erronée.",
        S_local=0.74,S_global=0.62,weight=0.48,
        frames=f(["variante v_t et erreur"],
                 fr_inter(("meso","DVE")),
                 ["politique auto-correction globale"],
                 ["détection erreur post-hoc"],
                 ["coût mémoire historique"])),
    law("SBX-DVE-108","Variant à coût computationnel borné","DVE","DVE-015",
        domains=["coût","borne"],
        examples=["max FLOPS par variante générée"],
        equations=["FLOPS(v) ≤ FLOPS_max"],
        description="Borne stricte sur le coût computationnel par variante.",
        S_local=0.79,S_global=0.67,weight=0.53,
        frames=f(["variante v et budget"],
                 fr_inter(("meso","DVE"))
                 ,["politique coût globale"],
                 ["compteur FLOPS"],
                 ["FLOPS_max arbitraire"])),
    law("SBX-DVE-109","Variant à priorité multi-objectif","DVE","DVE-015",
        domains=["multi-objectif","priorité"],
        examples=["score variant pondéré par 5 objectifs"],
        equations=["score = Σ w_i · obj_i, w priorité"],
        description="Score variant multi-objectif avec pondération par priorité.",
        S_local=0.74,S_global=0.62,weight=0.48,
        frames=f(["variante et objectifs"],
                 fr_inter(("meso","DVE"))
                 ,["frontière Pareto globale"],
                 ["recherche pondérée"],
                 ["pondérations subjectives"])),
    law("SBX-DVE-110","Élimination par dominance","DVE","DVE-005",
        domains=["dominance","élimination"],
        examples=["variant strictement dominé éliminé"],
        equations=["if v dominated by v' on all obj ⇒ prune(v)"],
        description="Élimination automatique des variantes Pareto-dominées.",
        S_local=0.77,S_global=0.65,weight=0.51,
        frames=f(["paire de variantes"],
                 fr_inter(("meso","DVE"))
                 ,["frontière Pareto"],
                 ["test dominance pairwise"],
                 ["dominance stricte rare"])),
    law("SBX-DVE-111","Variant stabilité robustesse","DVE","DVE-009",
        domains=["stabilité","robustesse"],
        examples=["variants stables sous petites perturbations input"],
        equations=["robust(v) ⟺ ‖v(x+δ) - v(x)‖ ≤ K·‖δ‖"],
        description="Variantes Lipschitz-robustes aux perturbations d'input.",
        S_local=0.78,S_global=0.66,weight=0.52,
        frames=f(["variante v et perturbation"],
                 fr_inter(("meso","DVE"),("macro","robustness ML")),
                 ["politique robustesse globale"],
                 ["test adversarial"],
                 ["constante K varie"])),
    law("SBX-DVE-112","Variant compositionnel hiérarchique","DVE","DVE-001",
        domains=["compositionnel","hiérarchique"],
        examples=["variants construits par composition de sous-variants"],
        equations=["v = compose(sub_v_1, sub_v_2)"],
        description="Construction hiérarchique de variants par composition de sous-variants.",
        S_local=0.75,S_global=0.63,weight=0.49,
        frames=f(["sous-variants candidates"],
                 fr_inter(("meso","DVE"))
                 ,["espace compositionnel global"],
                 ["arbre de composition"],
                 ["explosion combinatoire"])),

    # ────── UDE (12) ──────
    law("SBX-UDE-101","Retrieval avec re-ranking","UDE","UDE-009",
        domains=["retrieval","re-ranking"],
        examples=["1ère passe ANN puis re-rank par cross-encoder"],
        equations=["docs = rerank(retrieve_ANN(q))"],
        description="Pipeline retrieval avec re-ranking par cross-encoder pour qualité.",
        S_local=0.80,S_global=0.68,weight=0.55,
        frames=f(["query"],
                 fr_inter(("meso","UDE"),("macro","RAG advanced")),
                 ["politique retrieval globale"],
                 ["bi-encoder + cross-encoder"],
                 ["coût latence rerank"])),
    law("SBX-UDE-102","Mémoire active vs passive","UDE","UDE-014",
        domains=["mémoire","active"],
        examples=["mémoire active = consultée souvent ; passive = stockée"],
        equations=["active(e) ⟺ access_count > θ_active"],
        description="Distinction mémoire active (chaude) vs passive (froide) selon usage.",
        S_local=0.77,S_global=0.65,weight=0.51,
        frames=f(["entrée mémoire"],
                 fr_inter(("meso","UDE"))
                 ,["politique tiering systémique"],
                 ["compteur d'access"],
                 ["seuil θ_active arbitraire"])),
    law("SBX-UDE-103","Découverte par contraste latent","UDE","UDE-011",
        domains=["découverte","contraste"],
        examples=["lois inférées par paires contrastives"],
        equations=["contrast(c+, c-) → L_inferred"],
        description="Découverte par exemples contrastifs (positifs vs négatifs).",
        S_local=0.74,S_global=0.62,weight=0.48,
        frames=f(["paires contrastives"],
                 fr_inter(("meso","UDE"),("macro","contrastive learning")),
                 ["politique découverte contrastive"],
                 ["loss contrastive"],
                 ["dépend qualité paires"])),
    law("SBX-UDE-104","Mémoire à arborescence temporelle","UDE","UDE-026",
        domains=["mémoire","arborescence"],
        examples=["arbre temporel hiérarchique BFS rapide"],
        equations=["tree_t = {root: now, children: past windows}"],
        description="Mémoire organisée en arbre temporel pour query hiérarchique.",
        S_local=0.75,S_global=0.63,weight=0.49,
        frames=f(["timestamp et arbre"],
                 fr_inter(("meso","UDE"))
                 ,["politique arborescence globale"],
                 ["B-tree temporel"],
                 ["coût rebalancement"])),
    law("SBX-UDE-105","Self-improving retrieval","UDE","UDE-009",
        domains=["self-improving","retrieval"],
        examples=["retrieval s'améliore via feedback user"],
        equations=["retrieve(q,t+1) = update(retrieve(q,t), feedback)"],
        description="Retrieval qui s'améliore par feedback explicite ou implicite.",
        S_local=0.76,S_global=0.64,weight=0.50,
        frames=f(["query + feedback"],
                 fr_inter(("meso","UDE"),("macro","apprentissage en ligne")),
                 ["politique amélioration continue"],
                 ["online learning"],
                 ["feedback bruité"])),
    law("SBX-UDE-106","Mémoire externe versionnée","UDE","UDE-010",
        domains=["mémoire","versionnée"],
        examples=["chaque entrée mémoire versionnée par snapshot"],
        equations=["mem_v(e) = (e, version_t)"],
        description="Mémoire externe avec versionnage per-entrée pour audit historique.",
        S_local=0.78,S_global=0.66,weight=0.52,
        frames=f(["entrée mémoire et version"],
                 fr_inter(("meso","UDE"),("macro","versionning")),
                 ["historique versions globales"],
                 ["snapshot par entrée"],
                 ["coût stockage croissant"])),
    law("SBX-UDE-107","Indexation par signature comportementale","UDE","UDE-019",
        domains=["index","comportement"],
        examples=["lois indexées par signature comportementale"],
        equations=["sig(L) = canonical_behavior_pattern(L)"],
        description="Indexation par signature comportementale (au lieu de juste id).",
        S_local=0.73,S_global=0.61,weight=0.47,
        frames=f(["loi L et son comportement"],
                 fr_inter(("meso","UDE"))
                 ,["registre signatures globales"],
                 ["pattern matching"],
                 ["faux matches sur patterns simples"])),
    law("SBX-UDE-108","Découverte par méta-paterns","UDE","UDE-001",
        domains=["méta-pattern","découverte"],
        examples=["pattern de patterns détecté → loi méta"],
        equations=["meta_pattern = pattern_of(patterns)"],
        description="Découverte de patterns émergents au niveau méta.",
        S_local=0.72,S_global=0.60,weight=0.46,
        frames=f(["patterns observés"],
                 fr_inter(("meso","UDE"),("macro","pattern recognition")),
                 ["taxonomie méta-patterns globale"],
                 ["clustering hiérarchique"],
                 ["over-abstraction risque"])),
    law("SBX-UDE-109","Cache de retrieval invalidé par TTL","UDE","UDE-023",
        domains=["cache","TTL"],
        examples=["entrées cache expirent après T_TTL"],
        equations=["cache[k] expire à t_creation + TTL"],
        description="Cache de retrieval avec time-to-live pour gestion staleness.",
        S_local=0.79,S_global=0.67,weight=0.53,
        frames=f(["entrée cache"],
                 fr_inter(("meso","UDE"))
                 ,["politique cache globale"],
                 ["timestamp + check expiration"],
                 ["TTL arbitraire — calibration"])),
    law("SBX-UDE-110","Découverte par négation","UDE","UDE-001",
        domains=["négation","découverte"],
        examples=["lois apprises par contre-exemples"],
        equations=["learn_neg(¬X) → constraint(no X)"],
        description="Apprentissage par négation : contre-exemples produisant contraintes.",
        S_local=0.74,S_global=0.62,weight=0.48,
        frames=f(["contre-exemple"],
                 fr_inter(("meso","UDE"),("macro","apprentissage par négation")),
                 ["politique apprentissage globale"],
                 ["contraintes accumulées"],
                 ["sur-restriction possible"])),
    law("SBX-UDE-111","Mémoire d'attention persistante","UDE","UDE-014",
        domains=["mémoire","attention"],
        examples=["mémorisation des focus attentionnels passés"],
        equations=["mem_attn = [(focus_t, importance_t)]"],
        description="Mémoire des focus attentionnels passés pour cohérence narrative.",
        S_local=0.73,S_global=0.61,weight=0.47,
        frames=f(["focus + importance"],
                 fr_inter(("meso","UDE"))
                 ,["politique mémoire attention globale"],
                 ["log focus"],
                 ["coût stockage"])),
    law("SBX-UDE-112","Discovery by deletion testing","UDE","UDE-007",
        domains=["delete","testing"],
        examples=["test : que change-t-il si on retire L?"],
        equations=["delta(L) = behavior(graph - L) - behavior(graph)"],
        description="Découverte par delete-testing : impact de retirer chaque loi.",
        S_local=0.75,S_global=0.63,weight=0.49,
        frames=f(["loi L candidate à test"],
                 fr_inter(("meso","UDE"),("macro","ablation studies")),
                 ["politique ablation globale"],
                 ["test ablation systématique"],
                 ["coût test × N lois"])),

    # ────── GHUC (12) ──────
    law("SBX-GHUC-101","Méta-consolidation des invariants","GHUC","GHUC-009",
        domains=["méta","invariants"],
        examples=["regroupement des invariants similaires entre familles"],
        equations=["consolidate_inv(invs) → meta_invariant"],
        description="Consolidation méta-niveau des invariants similaires cross-famille.",
        S_local=0.78,S_global=0.66,weight=0.52,
        frames=f(["invariants observés"],
                 fr_inter(("meso","GHUC"),("macro","WP-12")),
                 ["politique consolidation invariants"],
                 ["clustering invariants"],
                 ["risque sur-abstraction"])),
    law("SBX-GHUC-102","Pruning par staleness","GHUC","GHUC-013",
        domains=["pruning","staleness"],
        examples=["élagage des arêtes non utilisées depuis T"],
        equations=["prune(e) ⟺ last_use(e) > T_stale"],
        description="Élagage des arêtes non utilisées (staleness > seuil).",
        S_local=0.77,S_global=0.65,weight=0.51,
        frames=f(["arête e et timestamp"],
                 fr_inter(("meso","GHUC"))
                 ,["politique staleness globale"],
                 ["log access"],
                 ["seuil T_stale arbitraire"])),
    law("SBX-GHUC-103","Audit cross-mission","GHUC","GHUC-014",
        domains=["audit","cross-mission"],
        examples=["cohérence entre lois P1, P2, P3"],
        equations=["coherent_cross(L_P1, L_P2, L_P3)"],
        description="Audit de cohérence entre lois introduites par missions distinctes.",
        S_local=0.79,S_global=0.67,weight=0.53,
        frames=f(["lois cross-mission"],
                 fr_inter(("meso","GHUC"),("macro","cross-mission")),
                 ["consistency globale cross-missions"],
                 ["scan compatibilité"],
                 ["coût audit complet"])),
    law("SBX-GHUC-104","Compression de sous-graphes","GHUC","GHUC-011",
        domains=["compression","sous-graphe"],
        examples=["regroupement visuel d'une famille à la demande"],
        equations=["collapse(family_F) → super_node(F)"],
        description="Compression visuelle d'une famille en super-nœud à la demande.",
        S_local=0.74,S_global=0.62,weight=0.48,
        frames=f(["famille F"],
                 fr_inter(("meso","GHUC"),("macro","UX visualisation")),
                 ["politique collapse globale"],
                 ["UI toggle"],
                 ["perte détails"])),
    law("SBX-GHUC-105","Détection de cycles cachés","GHUC","GHUC-019",
        domains=["cycles","détection"],
        examples=["cycles via mélange de relations"],
        equations=["cycle_mixed(graph) via DFS multi-kind"],
        description="Détection de cycles cachés mélangeant types de relations.",
        S_local=0.77,S_global=0.65,weight=0.51,
        frames=f(["sous-graphe à explorer"],
                 fr_inter(("meso","GHUC"),("macro","graph theory")),
                 ["politique anti-cycles globale"],
                 ["DFS sur multi-kinds"],
                 ["faux cycles sur paths longs"])),
    law("SBX-GHUC-106","Consolidation par élection","GHUC","GHUC-001",
        domains=["consolidation","élection"],
        examples=["fusion choisie par vote pondéré entre alternatives"],
        equations=["winner = argmax_v Σ w_i · vote_i(v)"],
        description="Consolidation entre alternatives par vote pondéré.",
        S_local=0.72,S_global=0.60,weight=0.46,
        frames=f(["alternatives + votes"],
                 fr_inter(("meso","GHUC"),("macro","vote théorie")),
                 ["politique consensus systémique"],
                 ["agrégation votes"],
                 ["paradoxe condorcet possible"])),
    law("SBX-GHUC-107","Audit hash-distribuée","GHUC","GHUC-017",
        domains=["audit","hash distribué"],
        examples=["chaque Oracle stocke hash chain de son audit"],
        equations=["chain = [hash(audit_t) for t in T]"],
        description="Audit avec chaîne de hashs distribuée (blockchain-like).",
        S_local=0.76,S_global=0.64,weight=0.50,
        frames=f(["audit historique par Oracle"],
                 fr_inter(("meso","GHUC"),("macro","tamper-evident")),
                 ["chaîne consensus globale"],
                 ["SHA chain"],
                 ["coût synchro"])),
    law("SBX-GHUC-108","Compaction de logs périodique","GHUC","GHUC-026",
        domains=["compaction","logs"],
        examples=["logs anciens compactés en summaries au bout de N jours"],
        equations=["compact_log(t < t_now - N) → summary"],
        description="Compaction périodique des logs anciens en summaries.",
        S_local=0.74,S_global=0.62,weight=0.48,
        frames=f(["logs anciens"],
                 fr_inter(("meso","GHUC"))
                 ,["politique stockage logs"],
                 ["aggregation"],
                 ["perte granularité"])),
    law("SBX-GHUC-109","Promotion par tier-up incrementale","GHUC","GHUC-022",
        domains=["promotion","incrémental"],
        examples=["tier μ2 → μ1 → μ0 par étapes"],
        equations=["promote_step(L, tier+1)"],
        description="Promotion incrémentale par paliers de tier (μ2→μ1→μ0).",
        S_local=0.75,S_global=0.63,weight=0.49,
        frames=f(["loi candidate à promotion"],
                 fr_inter(("meso","GHUC"),("macro","Oracle")),
                 ["politique tier-up globale"],
                 ["validation par étape"],
                 ["promotion lente"])),
    law("SBX-GHUC-110","Démotion graduelle par tier","GHUC","GHUC-023",
        domains=["démotion","graduelle"],
        examples=["μ0 → μ1 si dégradation modérée, sinon → μ2 ou sandbox"],
        equations=["demote_step(L, tier-1)"],
        description="Démotion graduelle par paliers (au lieu de saut direct sandbox).",
        S_local=0.74,S_global=0.62,weight=0.48,
        frames=f(["loi candidate à démotion"],
                 fr_inter(("meso","GHUC"),("macro","Oracle")),
                 ["politique démotion globale"],
                 ["check seuil par étape"],
                 ["multiples micro-démotions = bruit"])),
    law("SBX-GHUC-111","Méta-fusion par invariants partagés","GHUC","GHUC-009",
        domains=["méta-fusion","invariants"],
        examples=["fusion de 3+ lois partageant invariants similaires"],
        equations=["fuse_n(L1,...,Ln) si ∩ invariants ≠ ∅"],
        description="Fusion N-aire de lois partageant un invariant commun.",
        S_local=0.73,S_global=0.61,weight=0.47,
        frames=f(["set de lois"],
                 fr_inter(("meso","GHUC"))
                 ,["politique fusion N-aire"],
                 ["intersection invariants"],
                 ["fusion irréversible coûteuse"])),
    law("SBX-GHUC-112","Audit auto-déclencheur","GHUC","GHUC-007",
        domains=["audit","auto-déclencheur"],
        examples=["audit lancé automatiquement après N modifications"],
        equations=["auto_audit ⟺ count(modifs) > N_threshold"],
        description="Audit déclenché automatiquement après seuil de modifications.",
        S_local=0.78,S_global=0.66,weight=0.52,
        frames=f(["compteur modifs"],
                 fr_inter(("meso","GHUC"))
                 ,["politique auto-audit globale"],
                 ["compteur incrémental"],
                 ["seuil arbitraire"])),

    # ────── WP11 (12) ──────
    law("SBX-WP11-101","Audit par Markov chain","WP11","WP11-024",
        domains=["audit","Markov"],
        examples=["audit modélisé comme chaîne de Markov sur états santé"],
        equations=["P(state_{t+1} | state_t) Markov"],
        description="Modélisation Markov de l'évolution des états de santé du système.",
        S_local=0.76,S_global=0.64,weight=0.50,
        frames=f(["état santé t"],
                 fr_inter(("meso","WP11"),("macro","stochastic processes")),
                 ["chaîne globale santé"],
                 ["estimation matrice transition"],
                 ["hypothèse markovienne forte"])),
    law("SBX-WP11-102","Score de robustesse statistique","WP11","WP11-009",
        domains=["robustesse","statistique"],
        examples=["score robustesse via bootstrap"],
        equations=["robust_score = quantile(boot_scores, 0.05)"],
        description="Robustesse statistique mesurée par quantile inférieur de bootstrap.",
        S_local=0.78,S_global=0.66,weight=0.52,
        frames=f(["jeu d'audits"],
                 fr_inter(("meso","WP11"),("macro","statistical inference")),
                 ["distribution robustesse globale"],
                 ["bootstrap N=1000"],
                 ["coût compute bootstrap"])),
    law("SBX-WP11-103","Détection biais d'audit","WP11","WP11-026",
        domains=["biais","audit"],
        examples=["alerte si auditeur favorise systematically certaines lois"],
        equations=["bias = Σ favoritism_score(auditor, law)"],
        description="Détection de biais systématique d'auditeur envers certaines lois.",
        S_local=0.74,S_global=0.62,weight=0.48,
        frames=f(["auditeur + historique"],
                 fr_inter(("meso","WP11"),("macro","fairness")),
                 ["politique anti-biais globale"],
                 ["test statistique d'indépendance"],
                 ["faux positifs sur expertise réelle"])),
    law("SBX-WP11-104","Audit par triangulation","WP11","WP11-026",
        domains=["audit","triangulation"],
        examples=["3 méthodes différentes, accord requis"],
        equations=["valid(L) ⟺ accord(method_1, method_2, method_3)"],
        description="Validation par triangulation : 3 méthodes indépendantes en accord.",
        S_local=0.79,S_global=0.67,weight=0.53,
        frames=f(["loi L et méthodes"],
                 fr_inter(("meso","WP11"))
                 ,["politique triangulation systémique"],
                 ["3 audits parallèles"],
                 ["coût × 3"])),
    law("SBX-WP11-105","Mesure de drift par Wasserstein","WP11","WP11-015",
        domains=["drift","Wasserstein"],
        examples=["distance Wasserstein entre distrib HS_t et HS_{t-30}"],
        equations=["drift = W(distrib(HS_t), distrib(HS_{t-30}))"],
        description="Mesure de drift par distance Wasserstein entre distributions HS.",
        S_local=0.75,S_global=0.63,weight=0.49,
        frames=f(["fenêtre temporelle"],
                 fr_inter(("meso","WP11"),("macro","optimal transport")),
                 ["distrib HS globale"],
                 ["Wasserstein-1"],
                 ["coût compute Wasserstein"])),
    law("SBX-WP11-106","Score de cohérence narrative","WP11","WP11-009",
        domains=["cohérence","narrative"],
        examples=["cohérence des outputs au cours d'une session"],
        equations=["narr_coh = mean cosine(output_t, output_{t+1})"],
        description="Score de cohérence narrative inter-tours dans une session.",
        S_local=0.76,S_global=0.64,weight=0.50,
        frames=f(["session avec tours"],
                 fr_inter(("meso","WP11"),("macro","UX cohérence")),
                 ["politique narrative globale"],
                 ["cosine inter-tours"],
                 ["faux faible si transitions abruptes intentionnelles"])),
    law("SBX-WP11-107","Intervalle de confiance HS","WP11","WP11-022",
        domains=["confiance","HS"],
        examples=["HS publié comme [0.95, 1.00] CI 95%"],
        equations=["HS_CI = bootstrap_CI(HS, 0.95)"],
        description="HS publié avec intervalle de confiance bootstrappé.",
        S_local=0.79,S_global=0.67,weight=0.53,
        frames=f(["calcul HS courant"],
                 fr_inter(("meso","WP11"),("macro","statistique")),
                 ["politique CI publication"],
                 ["bootstrap CI"],
                 ["coût compute"])),
    law("SBX-WP11-108","Audit anti-overfit","WP11","WP11-009",
        domains=["overfit","audit"],
        examples=["alerte si pipeline accepte tous les candidats"],
        equations=["alert ⟺ acceptance_rate > 0.95"],
        description="Détection d'overfit du pipeline (acceptation trop universelle).",
        S_local=0.81,S_global=0.69,weight=0.55,
        frames=f(["historique pipeline"],
                 fr_inter(("meso","WP11"),("macro","ML overfit")),
                 ["politique anti-overfit"],
                 ["taux acceptation"],
                 ["seuil arbitraire"])),
    law("SBX-WP11-109","Score de couverture par axe","WP11","WP11-027",
        domains=["couverture","axes"],
        examples=["chaque axe priorité couvert ≥ N lois"],
        equations=["coverage(axis) = count(laws on axis)"],
        description="Couverture par axe de priorité (rigueur, anti-hallu, mémoire, etc.).",
        S_local=0.74,S_global=0.62,weight=0.48,
        frames=f(["jeu de lois et axes"],
                 fr_inter(("meso","WP11"))
                 ,["politique couverture globale"],
                 ["taggage par axe"],
                 ["axes flous"])),
    law("SBX-WP11-110","Mesure d'entropie cognitive","WP11","WP11-001",
        domains=["entropie","cognitive"],
        examples=["entropie du graph relations"],
        equations=["H_cog = -Σ p_i log p_i sur distrib lois"],
        description="Entropie cognitive du graphe (diversité des lois pondérée par usage).",
        S_local=0.75,S_global=0.63,weight=0.49,
        frames=f(["graphe et usage"],
                 fr_inter(("meso","WP11"),("macro","information theory")),
                 ["entropie globale"],
                 ["estimation distrib usage"],
                 ["distrib usage difficile à mesurer"])),
    law("SBX-WP11-111","Audit de répartition d'usage","WP11","WP11-035",
        domains=["répartition","usage"],
        examples=["alerte si <20% des lois génèrent >80% des usages"],
        equations=["alert ⟺ pareto_skew > 0.80"],
        description="Détection de skew Pareto excessif dans l'usage des lois.",
        S_local=0.77,S_global=0.65,weight=0.51,
        frames=f(["log usage"],
                 fr_inter(("meso","WP11"),("macro","Pareto distribution")),
                 ["politique répartition"],
                 ["mesure Gini"],
                 ["skew naturel acceptable"])),
    law("SBX-WP11-112","Score de profondeur cognitive utilisée","WP11","WP11-009",
        domains=["profondeur","cognitive"],
        examples=["profondeur moyenne du sous-graphe utilisé par CLE"],
        equations=["depth_used = mean depth(loaded_laws)"],
        description="Mesure de la profondeur cognitive moyenne utilisée par les opérations.",
        S_local=0.73,S_global=0.61,weight=0.47,
        frames=f(["opérations runtime"],
                 fr_inter(("meso","WP11"),("macro","ZenRuntime")),
                 ["politique profondeur globale"],
                 ["log depth_used per op"],
                 ["faible = surface seulement"])),

    # ────── WP12 (12) ──────
    law("SBX-WP12-101","Critère d'antifragilité","WP12","WP12-015",
        domains=["antifragilité","admissibilité"],
        examples=["loi acceptable si stress améliore S_global"],
        equations=["antifragile(L) ⟺ S_global_après_stress > S_global_avant"],
        description="Antifragilité : la loi gagne en cohérence sous stress modéré.",
        S_local=0.76,S_global=0.64,weight=0.50,
        frames=f(["loi L sous stress"],
                 fr_inter(("meso","WP12"),("macro","Taleb antifragility")),
                 ["politique antifragile systémique"],
                 ["test stress contrôlé"],
                 ["stress excessif fragilise"])),
    law("SBX-WP12-102","Critère de gracefulness","WP12","WP12-035",
        domains=["graceful","admissibilité"],
        examples=["dégrade gracieusement plutôt que crash"],
        equations=["graceful(L) ⟺ partial_response sur erreur"],
        description="Loi accepte degradation gracieuse plutôt que crash brutal.",
        S_local=0.78,S_global=0.66,weight=0.52,
        frames=f(["scénario erreur"],
                 fr_inter(("meso","WP12"),("macro","UX")),
                 ["politique graceful systémique"],
                 ["test sur erreurs simulées"],
                 ["risque masquer problèmes"])),
    law("SBX-WP12-103","Critère de monotonie","WP12","WP12-001",
        domains=["monotonie","admissibilité"],
        examples=["ajouter des données ne dégrade jamais conclusions"],
        equations=["monotone(L) ⟺ S(L|D ∪ d) ≥ S(L|D)"],
        description="Monotonie : l'ajout de données n'invalide jamais les conclusions.",
        S_local=0.75,S_global=0.63,weight=0.49,
        frames=f(["loi L et data ajoutées"],
                 fr_inter(("meso","WP12"),("macro","logique non-monotone")),
                 ["politique monotonie systémique"],
                 ["test sur ajouts data"],
                 ["non-monotonie utile parfois"])),
    law("SBX-WP12-104","Critère de localité","WP12","WP12-001",
        domains=["localité","admissibilité"],
        examples=["modification locale ne propage pas globalement"],
        equations=["local(modif) ⟺ impact ⊆ N(modif)"],
        description="Modification d'une loi reste localisée dans son voisinage.",
        S_local=0.77,S_global=0.65,weight=0.51,
        frames=f(["modification proposée"],
                 fr_inter(("meso","WP12"),("macro","R-CORE-3 composition")),
                 ["politique localité systémique"],
                 ["test propagation"],
                 ["impacts cross-famille parfois"])),
    law("SBX-WP12-105","Critère de transparence opérationnelle","WP12","WP12-019",
        domains=["transparence","opérationnelle"],
        examples=["chaque op runtime auditée en temps réel"],
        equations=["op transparent ⟺ trace publiée"],
        description="Transparence opérationnelle : trace de chaque opération runtime.",
        S_local=0.79,S_global=0.67,weight=0.53,
        frames=f(["opération runtime"],
                 fr_inter(("meso","WP12"),("systémique","audit")),
                 ["politique transparence systémique"],
                 ["log telemetry"],
                 ["coût stockage logs"])),
    law("SBX-WP12-106","Critère de non-coercition","WP12","WP12-037",
        domains=["non-coercition","éthique"],
        examples=["réponse n'impose jamais une action user"],
        equations=["¬coerce(response, user_action)"],
        description="Réponse runtime ne contient pas de coercition de l'utilisateur.",
        S_local=0.81,S_global=0.69,weight=0.55,
        frames=f(["réponse"],
                 fr_inter(("meso","WP12"),("macro","éthique IA")),
                 ["politique éthique systémique"],
                 ["NLI sur coercition"],
                 ["frontière coercition contextuelle"])),
    law("SBX-WP12-107","Critère de respect des préférences","WP12","WP12-020",
        domains=["préférences","respect"],
        examples=["réponse adaptée aux préférences user déclarées"],
        equations=["align(response, user.preferences)"],
        description="Adaptation de la réponse aux préférences user déclarées.",
        S_local=0.74,S_global=0.62,weight=0.48,
        frames=f(["réponse + préférences user"],
                 fr_inter(("meso","WP12"),("macro","UX personalization")),
                 ["politique respect préférences"],
                 ["check préférences"],
                 ["préférences peuvent biaiser réponse"])),
    law("SBX-WP12-108","Critère d'efficience énergétique","WP12","WP12-022",
        domains=["énergie","efficience"],
        examples=["loi privilégiée si moins coûteuse en énergie"],
        equations=["score_energy(L) = inverse(energy(L))"],
        description="Critère écologique : préférence pour lois moins énergivores.",
        S_local=0.73,S_global=0.61,weight=0.47,
        frames=f(["loi L et coût énergétique"],
                 fr_inter(("meso","WP12"),("macro","green AI")),
                 ["politique efficience globale"],
                 ["mesure FLOPs/Wh"],
                 ["mesure énergie indirecte"])),
    law("SBX-WP12-109","Critère d'absence de fuite","WP12","WP12-027",
        domains=["fuite","privacy"],
        examples=["aucune fuite info user vers tiers"],
        equations=["¬leak(user_data, third_party)"],
        description="Aucune fuite d'information utilisateur vers tiers non-autorisés.",
        S_local=0.82,S_global=0.70,weight=0.56,
        frames=f(["data flow"],
                 fr_inter(("meso","WP12"),("macro","RGPD")),
                 ["politique anti-fuite globale"],
                 ["audit data flow"],
                 ["fuites cachées difficiles à détecter"])),
    law("SBX-WP12-110","Critère de réciprocité","WP12","WP12-001",
        domains=["réciprocité","admissibilité"],
        examples=["si L1 cite L2, L2 admet L1 comme parent valide"],
        equations=["cite(L1,L2) ⇒ valid_child(L1, L2)"],
        description="Réciprocité des citations : citer → être cité comme parent valide.",
        S_local=0.74,S_global=0.62,weight=0.48,
        frames=f(["paire (L1,L2)"],
                 fr_inter(("meso","WP12"))
                 ,["politique réciprocité systémique"],
                 ["check citations bidirectionnelles"],
                 ["citations asymétriques légitimes parfois"])),
    law("SBX-WP12-111","Critère de proportionnalité","WP12","WP12-001",
        domains=["proportionnalité","admissibilité"],
        examples=["réponse proportionnée à la complexité de la query"],
        equations=["len(response) ∝ complexity(query)"],
        description="Réponse proportionnée à la complexité de la query (pas de sur/sous-réponse).",
        S_local=0.76,S_global=0.64,weight=0.50,
        frames=f(["query + réponse"],
                 fr_inter(("meso","WP12"),("macro","UX")),
                 ["politique proportionnalité globale"],
                 ["estimation complexité query"],
                 ["complexité subjective"])),
    law("SBX-WP12-112","Critère d'auditabilité timestamped","WP12","WP12-007",
        domains=["audit","timestamp"],
        examples=["chaque op horodatée et signée"],
        equations=["op = (op_data, ts, sig)"],
        description="Horodatage et signature systématiques de toute opération.",
        S_local=0.80,S_global=0.68,weight=0.55,
        frames=f(["opération"],
                 fr_inter(("meso","WP12"),("macro","audit blockchain-like")),
                 ["politique horodatage globale"],
                 ["NTP + signing"],
                 ["coût stockage log"])),

    # ────── SDE (12) ──────
    law("SBX-SDE-101","Attention focale-latérale","SDE","SDE-008",
        domains=["attention","latérale"],
        examples=["focus principal + attention périphérique"],
        equations=["attn = focal + λ·peripheral"],
        description="Attention duale : focus principal + couche latérale légère.",
        S_local=0.75,S_global=0.63,weight=0.49,
        frames=f(["séquence + focus"],
                 fr_inter(("meso","SDE"),("macro","attention biologique")),
                 ["politique attention duale"],
                 ["dual heads"],
                 ["coût compute × 2"])),
    law("SBX-SDE-102","Self-debugging","SDE","SDE-013",
        domains=["self","debug"],
        examples=["LLM identifie ses propres erreurs"],
        equations=["error_self = self_check(output) - oracle"],
        description="Capacité d'auto-debug : LLM identifie ses propres erreurs.",
        S_local=0.77,S_global=0.65,weight=0.51,
        frames=f(["output candidat"],
                 fr_inter(("meso","SDE"),("macro","metacognition")),
                 ["politique self-debug systémique"],
                 ["self-check"],
                 ["bias self-favoritism"])),
    law("SBX-SDE-103","Skopein partagé multi-agent","SDE","SDE-006",
        domains=["partagé","multi-agent"],
        examples=["plusieurs agents partagent skopein commun"],
        equations=["⟨S_shared⟩ = ⊕_a ⟨S_agent_a⟩"],
        description="Skopein partagé entre plusieurs agents (cognition collective).",
        S_local=0.73,S_global=0.61,weight=0.47,
        frames=f(["agents et leurs skopein"],
                 fr_inter(("meso","SDE"),("macro","multi-agent systems")),
                 ["consensus skopein globale"],
                 ["agrégation skopein"],
                 ["désaccords inter-agent"])),
    law("SBX-SDE-104","Décentrage temporel","SDE","SDE-014",
        domains=["décentrage","temporel"],
        examples=["réponse projetée du futur ou passé du user"],
        equations=["decenter_t(response, t_user)"],
        description="Décentrage temporel : projection vers passé/futur de l'utilisateur.",
        S_local=0.71,S_global=0.59,weight=0.43,
        frames=f(["réponse + temps user"],
                 fr_inter(("meso","SDE"),("macro","temporal cognition")),
                 ["politique temporelle globale"],
                 ["modèle temporel user"],
                 ["spéculation temporelle"])),
    law("SBX-SDE-105","Attention adaptative à la fatigue","SDE","SDE-015",
        domains=["adaptation","fatigue"],
        examples=["attention diminue si signaux de fatigue user"],
        equations=["attn_user = attn_default × (1 - fatigue)"],
        description="Adaptation de l'attention selon signaux de fatigue user.",
        S_local=0.70,S_global=0.58,weight=0.42,
        frames=f(["interaction + fatigue"],
                 fr_inter(("meso","SDE"),("macro","UX adaptative")),
                 ["politique adaptation systémique"],
                 ["mesure fatigue indirecte"],
                 ["mesure fatigue intrusive"])),
    law("SBX-SDE-106","Attention par source","SDE","SDE-008",
        domains=["attention","source"],
        examples=["attention pondérée par fiabilité de la source"],
        equations=["attn(token) = base × trust(source(token))"],
        description="Attention pondérée par fiabilité de la source documentaire.",
        S_local=0.78,S_global=0.66,weight=0.52,
        frames=f(["token + source"],
                 fr_inter(("meso","SDE"),("macro","WP-12 traçabilité")),
                 ["distribution fiabilité globale"],
                 ["score trust par source"],
                 ["trust score subjectif"])),
    law("SBX-SDE-107","Auto-clarification","SDE","SDE-013",
        domains=["auto-clarification"],
        examples=["LLM demande clarification avant ambigüité résolue"],
        equations=["if ambiguous(query) → ask_clarification"],
        description="Demande automatique de clarification sur queries ambiguës.",
        S_local=0.77,S_global=0.65,weight=0.51,
        frames=f(["query + analyse ambigüité"],
                 fr_inter(("meso","SDE"),("macro","UX")),
                 ["politique clarification systémique"],
                 ["détection ambigüité"],
                 ["risque user impatience"])),
    law("SBX-SDE-108","Skopein temporel multi-tour","SDE","SDE-017",
        domains=["temporal","multi-tour"],
        examples=["cohérence skopein à travers 10+ tours"],
        equations=["coh_skopein(turns) sustained"],
        description="Cohérence skopein soutenue sur conversations longues.",
        S_local=0.75,S_global=0.63,weight=0.49,
        frames=f(["séquence longue de tours"],
                 fr_inter(("meso","SDE"),("macro","UX longue conversation")),
                 ["cohérence narrative globale"],
                 ["check inter-turn"],
                 ["dégrade au-delà context window"])),
    law("SBX-SDE-109","Inférence inverse","SDE","SDE-002",
        domains=["inférence","inverse"],
        examples=["déduction des intentions cachées du user"],
        equations=["intent = inverse_inference(behavior)"],
        description="Inférence des intentions user par inférence inverse de comportement.",
        S_local=0.71,S_global=0.59,weight=0.43,
        frames=f(["comportement observé"],
                 fr_inter(("meso","SDE"),("macro","ToM")),
                 ["modèle intentions globales"],
                 ["modélisation user"],
                 ["intrusion potentielle"])),
    law("SBX-SDE-110","Refus créatif","SDE","SDE-016",
        domains=["refus","créatif"],
        examples=["refus + alternative créative au lieu de simple no"],
        equations=["refuse(q) → propose alternative(q)"],
        description="Refus accompagné d'une alternative créative (UX positive).",
        S_local=0.76,S_global=0.64,weight=0.50,
        frames=f(["query refusée"],
                 fr_inter(("meso","SDE"),("macro","UX")),
                 ["politique alternatives globale"],
                 ["recherche alternative pertinente"],
                 ["alternatives parfois inadaptées"])),
    law("SBX-SDE-111","Méta-attention sur incertitude","SDE","SDE-019",
        domains=["méta","incertitude"],
        examples=["attention spéciale sur claims incertains"],
        equations=["attn_meta(claim) ↑ si confidence < θ"],
        description="Méta-attention focalisée sur les claims incertains pour vérification.",
        S_local=0.79,S_global=0.67,weight=0.53,
        frames=f(["claim incertain"],
                 fr_inter(("meso","SDE"),("macro","WP-11 audit")),
                 ["politique méta-attention systémique"],
                 ["seuil θ confidence"],
                 ["coût compute méta-attention"])),
    law("SBX-SDE-112","Skopein réflexif explicite","SDE","SDE-013",
        domains=["réflexif","explicite"],
        examples=["LLM explique sa propre démarche de raisonnement"],
        equations=["explain_reasoning(output)"],
        description="Capacité de réflexivité : LLM explique son propre raisonnement.",
        S_local=0.80,S_global=0.68,weight=0.55,
        frames=f(["output + raisonnement"],
                 fr_inter(("meso","SDE"),("macro","interpretability")),
                 ["politique transparence raisonnement"],
                 ["trace structurée du raisonnement"],
                 ["raisonnement post-hoc parfois fictif"])),

    # ────── PAL (8) ──────
    law("SBX-PAL-101","Métastabilité runtime adaptative","PAL","PAL-006",
        domains=["métastabilité","runtime"],
        palieronic=True,
        examples=["runtime oscille entre 2 modes selon load"],
        equations=["mode_runtime ∈ {strict, balanced, performant}"],
        description="Métastabilité du mode runtime selon charge système.",
        S_local=0.72,S_global=0.60,weight=0.46,
        frames=f(["état charge"],
                 fr_inter(("meso","PAL"),("macro","ZenRuntime")),
                 ["politique métastable globale"],
                 ["check charge"],
                 ["thrashing entre modes"])),
    law("SBX-PAL-102","Cycle de calibration trimestriel","PAL","PAL-008",
        domains=["calibration","trimestriel"],
        palieronic=True,
        examples=["recalibration coefficients tous les 90j"],
        equations=["calibrate every 90 days"],
        description="Cycle de recalibration trimestrielle des coefficients système.",
        S_local=0.75,S_global=0.63,weight=0.49,
        frames=f(["historique 90j"],
                 fr_inter(("meso","PAL"),("macro","Adaptive")),
                 ["politique cycle globale"],
                 ["timer + audit complet"],
                 ["cycle 90j arbitraire"])),
    law("SBX-PAL-103","Saut palieronique cross-mission","PAL","PAL-004",
        domains=["saut","cross-mission"],
        palieronic=True,
        examples=["saut depuis Mission N vers Mission N+1"],
        equations=["mission_palier(N) → mission_palier(N+1)"],
        description="Saut palieronique formalisé entre missions de développement.",
        S_local=0.73,S_global=0.61,weight=0.47,
        frames=f(["mission courante"],
                 fr_inter(("meso","PAL"),("macro","gouvernance")),
                 ["politique mission globale"],
                 ["check critères mission complete"],
                 ["mission boundaries floues"])),
    law("SBX-PAL-104","Stabilisation post-mission","PAL","PAL-010",
        domains=["stabilisation","post-mission"],
        palieronic=True,
        examples=["période stable de 7j post-mission majeure"],
        equations=["stab_window = 7 days"],
        description="Période de stabilisation forcée post-mission majeure.",
        S_local=0.78,S_global=0.66,weight=0.52,
        frames=f(["mission complétée"],
                 fr_inter(("meso","PAL"),("macro","gouvernance")),
                 ["politique stabilisation systémique"],
                 ["timer 7j"],
                 ["bloque modifications utiles"])),
    law("SBX-PAL-105","Transition graduelle de coefficient","PAL","PAL-009",
        domains=["transition","coefficient"],
        palieronic=True,
        examples=["coefficient α passe de 0.35 à 0.40 sur 30j"],
        equations=["α(t) = α_old + (α_new - α_old) × t/T"],
        description="Transition graduelle (ramp) des coefficients pour éviter thrashing.",
        S_local=0.76,S_global=0.64,weight=0.50,
        frames=f(["coefficient + ramp"],
                 fr_inter(("meso","PAL"),("macro","Adaptive")),
                 ["politique transition globale"],
                 ["interpolation linéaire"],
                 ["transition lente"])),
    law("SBX-PAL-106","Saut palieronique sur découverte majeure","PAL","PAL-004",
        domains=["saut","découverte"],
        palieronic=True,
        examples=["découverte d'invariant majeur → palier+1"],
        equations=["if invariant_major ⇒ Δpalier = +1"],
        description="Saut palieronique déclenché par découverte d'invariant majeur.",
        S_local=0.74,S_global=0.62,weight=0.48,
        frames=f(["découverte évaluée"],
                 fr_inter(("meso","PAL"),("macro","DiscoveryEngine")),
                 ["politique saut systémique"],
                 ["évaluation invariant"],
                 ["sauts trop fréquents = bruit"])),
    law("SBX-PAL-107","Métastabilité gouvernance multi-acteur","PAL","PAL-006",
        domains=["métastabilité","gouvernance"],
        palieronic=True,
        examples=["décisions oscillent entre auteurs distincts"],
        equations=["decision_stable ⟺ consensus inter-acteurs"],
        description="Métastabilité gouvernance avec multiples acteurs en désaccord.",
        S_local=0.71,S_global=0.59,weight=0.43,
        frames=f(["acteurs et votes"],
                 fr_inter(("meso","PAL"),("macro","gouvernance")),
                 ["politique consensus globale"],
                 ["mesure désaccord"],
                 ["paralysie possible"])),
    law("SBX-PAL-108","Réveil sur déclencheur externe","PAL","PAL-014",
        domains=["réveil","externe"],
        palieronic=True,
        examples=["réveil système sur événement externe (mission, alerte)"],
        equations=["wake_on_trigger(event)"],
        description="Réveil système déclenché par événement externe (vs cycle interne).",
        S_local=0.73,S_global=0.61,weight=0.47,
        frames=f(["événement externe"],
                 fr_inter(("meso","PAL"),("macro","reactive systems")),
                 ["politique réveil systémique"],
                 ["event listener"],
                 ["trigger spam possible"])),

    # ────── Transverse / iso (20) ──────
    law("SBX-WP12-113","Critère d'auditabilité runtime","WP12","WP12-019",
        domains=["audit","runtime"],
        examples=["chaque réponse runtime audit-able instantanément"],
        equations=["audit_now(response) → trace immediate"],
        description="Audit runtime instantané sur demande utilisateur.",
        S_local=0.78,S_global=0.66,weight=0.52,
        frames=f(["demande audit"],
                 fr_inter(("meso","WP12"),("systémique","ZenRuntime")),
                 ["politique audit immédiat"],
                 ["telemetry buffer"],
                 ["coût stockage telemetry"])),
    law("SBX-GHUC-113","Méta-cohérence inter-batch","GHUC","SBX-GHUC-103",
        domains=["méta","inter-batch"],
        examples=["cohérence entre P1, P2, P3, P4 batches"],
        equations=["coh(batch_i, batch_j) ≥ θ"],
        description="Cohérence méta-niveau entre batches d'expansion successifs.",
        S_local=0.75,S_global=0.63,weight=0.49,
        frames=f(["paires de batches"],
                 fr_inter(("meso","GHUC"))
                 ,["politique cohérence cross-batch"],
                 ["audit inter-batch"],
                 ["batches anciens vs nouveaux"])),
    law("SBX-UDE-113","Découverte par interpolation latente","UDE","UDE-001",
        domains=["interpolation","latente"],
        examples=["lois inférées entre 2 attracteurs connus"],
        equations=["L_new = interpolate(L1, L2, α)"],
        description="Découverte de lois par interpolation entre 2 attracteurs proches.",
        S_local=0.72,S_global=0.60,weight=0.46,
        frames=f(["paire (L1,L2) et α"],
                 fr_inter(("meso","UDE"),("macro","latent space exploration")),
                 ["politique interpolation globale"],
                 ["interpolation embedding"],
                 ["interpolation dans espace non-convexe"])),
    law("SBX-WP11-113","Score holistique de santé","WP11","WP11-032",
        domains=["santé","holistique"],
        examples=["combo HS + S_global + verticality + coverage"],
        equations=["health_holistic = w1·HS + w2·S_g + w3·vert"],
        description="Score holistique combinant plusieurs métriques de santé.",
        S_local=0.79,S_global=0.67,weight=0.53,
        frames=f(["métriques santé"],
                 fr_inter(("meso","WP11"),("macro","monitoring")),
                 ["score globale unique"],
                 ["agrégation pondérée"],
                 ["pondérations subjectives"])),
    law("SBX-DVE-113","Variant à empreinte écologique","DVE","DVE-015",
        domains=["variant","écologie"],
        examples=["variant à faible empreinte carbon préféré"],
        equations=["carbon(v) ≤ carbon_max"],
        description="Variants évalués sur empreinte carbone (priorité green AI).",
        S_local=0.73,S_global=0.61,weight=0.47,
        frames=f(["variant + carbon footprint"],
                 fr_inter(("meso","DVE"),("macro","green AI")),
                 ["politique écologique globale"],
                 ["mesure carbon par FLOPs"],
                 ["mesure indirecte"])),
    law("SBX-SDE-113","Skopein narratif personnalisé","SDE","SDE-014",
        domains=["narratif","personnalisé"],
        examples=["narration adaptée au style user"],
        equations=["narrate(content, user.narrative_style)"],
        description="Adaptation du style narratif au profil user.",
        S_local=0.74,S_global=0.62,weight=0.48,
        frames=f(["contenu + profil user"],
                 fr_inter(("meso","SDE"),("macro","UX personalization")),
                 ["politique narration globale"],
                 ["modèle style user"],
                 ["modélisation style imparfaite"])),
    law("SBX-PAL-109","Cycle de méta-audit","PAL","PAL-008",
        domains=["méta-audit","cycle"],
        palieronic=True,
        examples=["audit de l'audit lui-même tous les 30j"],
        equations=["meta_audit(audit_log) every 30 days"],
        description="Cycle de méta-audit : audit du processus d'audit.",
        S_local=0.76,S_global=0.64,weight=0.50,
        frames=f(["log audits"],
                 fr_inter(("meso","PAL"),("macro","Adaptive")),
                 ["politique méta-audit globale"],
                 ["scan log audits"],
                 ["récursion audit-de-l'audit"])),
    law("SBX-ULG-113","Embedding éthique projeté","ULG","ULG-001",
        domains=["embedding","éthique"],
        examples=["projection embedding vers axe éthique"],
        equations=["proj_ethic(emb) → score_éthique"],
        description="Projection d'embeddings vers axe éthique pour audit moral.",
        S_local=0.71,S_global=0.59,weight=0.43,
        frames=f(["embedding + axe éthique"],
                 fr_inter(("meso","ULG"),("macro","éthique IA")),
                 ["politique éthique systémique"],
                 ["projection linéaire"],
                 ["axe éthique subjectif"])),
    law("SBX-GHUC-114","Consolidation par invariants éthiques","GHUC","GHUC-009",
        domains=["consolidation","éthique"],
        examples=["regroupement de lois partageant principes éthiques"],
        equations=["consolidate_ethic(laws) si ∩ ethical_principles ≠ ∅"],
        description="Consolidation des lois selon principes éthiques partagés.",
        S_local=0.74,S_global=0.62,weight=0.48,
        frames=f(["set de lois"],
                 fr_inter(("meso","GHUC"),("macro","éthique IA")),
                 ["politique consolidation éthique"],
                 ["scan principes"],
                 ["principes éthiques contestés"])),
    law("SBX-WP12-114","Critère de minimisation des biais","WP12","WP12-001",
        domains=["biais","minimisation"],
        examples=["loi minimisant biais cognitifs identifiés"],
        equations=["bias_min(L) ⟺ Σ bias_score < θ"],
        description="Critère de minimisation des biais cognitifs dans les lois.",
        S_local=0.77,S_global=0.65,weight=0.51,
        frames=f(["loi L et biais identifiés"],
                 fr_inter(("meso","WP12"),("macro","fairness")),
                 ["politique anti-biais systémique"],
                 ["audit biais par checklist"],
                 ["biais cachés non détectés"])),
    law("SBX-UDE-114","Mémoire d'apprentissage continu","UDE","UDE-014",
        domains=["mémoire","apprentissage"],
        examples=["mémoire intégrant feedback continu"],
        equations=["mem_t+1 = update(mem_t, feedback_t)"],
        description="Mémoire évoluant continuellement par intégration de feedback.",
        S_local=0.78,S_global=0.66,weight=0.52,
        frames=f(["mémoire et feedback"],
                 fr_inter(("meso","UDE"),("macro","continuous learning")),
                 ["politique mémoire continue"],
                 ["online update"],
                 ["catastrophic forgetting"])),
    law("SBX-DVE-114","Variant à transparence maximale","DVE","DVE-013",
        domains=["variant","transparence"],
        examples=["variants traçables et expliquables totalement"],
        equations=["transparent(v) ⟺ explain(v) complet"],
        description="Variants accompagnés d'explications complètes (transparence max).",
        S_local=0.79,S_global=0.67,weight=0.53,
        frames=f(["variant + explication"],
                 fr_inter(("meso","DVE"),("macro","XAI")),
                 ["politique transparence systémique"],
                 ["check explication non vide"],
                 ["explications volumineuses"])),
    law("SBX-SDE-114","Décentrage culturel","SDE","SDE-014",
        domains=["décentrage","culturel"],
        examples=["réponse adaptée au contexte culturel user"],
        equations=["culturalize(response, user.culture)"],
        description="Adaptation au contexte culturel user (anti-éthnocentrisme).",
        S_local=0.72,S_global=0.60,weight=0.46,
        frames=f(["réponse + culture user"],
                 fr_inter(("meso","SDE"),("macro","cultural awareness")),
                 ["politique multiculturelle"],
                 ["check culture user"],
                 ["modélisation culture stéréotypée"])),
    law("SBX-WP11-114","Score de stabilité multi-version","WP11","WP11-013",
        domains=["stabilité","multi-version"],
        examples=["HS stable à travers versions du graph"],
        equations=["stab_multi = 1 - var(HS_v_1, ..., HS_v_n)"],
        description="Stabilité de HS à travers versions historiques du graph.",
        S_local=0.76,S_global=0.64,weight=0.50,
        frames=f(["versions historiques"],
                 fr_inter(("meso","WP11"),("macro","versionning")),
                 ["politique stabilité systémique"],
                 ["variance HS inter-versions"],
                 ["versions trop nombreuses dispersent"])),
    law("SBX-PAL-110","Saut palieronique méta-systémique","PAL","PAL-019",
        domains=["saut","méta-systémique"],
        palieronic=True,
        examples=["promotion d'un sous-système entier vers nouveau palier"],
        equations=["promote_subsystem(S) ⟺ Core OK"],
        description="Promotion palieronique d'un sous-système entier.",
        S_local=0.74,S_global=0.62,weight=0.48,
        frames=f(["sous-système candidat"],
                 fr_inter(("meso","PAL"),("macro","gouvernance")),
                 ["politique promotion systémique"],
                 ["check Core sur sous-système"],
                 ["promotion système coûteuse"])),
    law("SBX-GHUC-115","Audit anti-coalition","GHUC","SBX-WP11-103",
        domains=["audit","coalition"],
        examples=["alerte si plusieurs lois favorisent les mêmes user"],
        equations=["coalition_alert ⟺ correlated_favoritism"],
        description="Détection de coalitions de lois favorisant systématiquement certains users.",
        S_local=0.71,S_global=0.59,weight=0.43,
        frames=f(["matrice favoritism"],
                 fr_inter(("meso","GHUC"),("macro","fairness")),
                 ["politique anti-coalition"],
                 ["test corrélation favoritism"],
                 ["faux positifs sur expertise réelle"])),
    law("SBX-ULG-114","Représentation neuro-symbolique","ULG","ULG-001",
        domains=["neuro-symbolique","représentation"],
        examples=["embedding + logique symbolique combinés"],
        equations=["repr = (emb_vector, sym_program)"],
        description="Représentation hybride combinant embedding vectoriel + programme symbolique.",
        S_local=0.75,S_global=0.63,weight=0.49,
        frames=f(["objet à représenter"],
                 fr_inter(("meso","ULG"),("macro","neuro-symbolic AI")),
                 ["espace représentationnel hybride"],
                 ["combinaison embeddings + AST"],
                 ["alignement difficile"])),
    law("SBX-UDE-115","Découverte par méta-question","UDE","UDE-001",
        domains=["découverte","méta-question"],
        examples=["nouvelle loi inférée d'une question sur le système"],
        equations=["L_new = answer(meta_question_about_system)"],
        description="Découverte par méta-questions sur le système lui-même.",
        S_local=0.73,S_global=0.61,weight=0.47,
        frames=f(["méta-question"],
                 fr_inter(("meso","UDE"),("macro","metacognition")),
                 ["politique méta-question globale"],
                 ["analyse meta-questions"],
                 ["méta-questions difficiles à formuler"])),
    law("SBX-DVE-115","Variant adversarial robuste","DVE","DVE-009",
        domains=["adversarial","robuste"],
        examples=["variant résistant à attaques adversariales"],
        equations=["adv_robust(v) ⟺ ‖v(x_adv) - v(x)‖ ≤ ε"],
        description="Variants robustes à attaques adversariales standardisées.",
        S_local=0.77,S_global=0.65,weight=0.51,
        frames=f(["variant + adversarial"],
                 fr_inter(("meso","DVE"),("macro","robustness")),
                 ["politique robustesse globale"],
                 ["test adversarial standardisé"],
                 ["adversaires évoluent"])),
    law("SBX-SDE-115","Skopein observationnel multi-temporel","SDE","SDE-006",
        domains=["multi-temporel","skopein"],
        examples=["observation à plusieurs échelles temporelles simultanées"],
        equations=["skopein_t = ⨁_τ skopein(t-τ)"],
        description="Skopein traversant plusieurs échelles temporelles simultanément.",
        S_local=0.72,S_global=0.60,weight=0.46,
        frames=f(["fenêtres temporelles"],
                 fr_inter(("meso","SDE"),("macro","multi-scale temporal")),
                 ["politique skopein multi-temporal"],
                 ["agrégation multi-fenêtre"],
                 ["coût × N fenêtres"])),
]


def hash_law(law_dict):
    """Compute reproducible hash of a law for sandbox_origin."""
    canonical = json.dumps({k: law_dict[k] for k in sorted(law_dict.keys())
                            if k not in ("_rollback_deps_planned",)},
                           sort_keys=True, ensure_ascii=False)
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()[:12]


def parents_of_canonical(canonical, nid):
    return [e["target"] for e in canonical["edges"]
            if e["kind"] == "parent" and e["source"] == nid]


def children_of_canonical(canonical, nid):
    return [e["source"] for e in canonical["edges"]
            if e["kind"] == "parent" and e["target"] == nid]


def count_compositions(law_id, canonical, sandbox_existing, planned, parent):
    """Count compositions across canonical + sandbox_existing + planned."""
    composes = set()
    if parent:
        composes.add(parent)
        # grand-parent (canonical or planned)
        gp = parents_of_canonical(canonical, parent)
        composes.update(gp)
        cand_p = next((c for c in planned if c["id"] == parent), None)
        if cand_p and cand_p.get("parent"):
            composes.add(cand_p["parent"])
        # siblings
        for sib in children_of_canonical(canonical, parent):
            if sib != law_id: composes.add(sib)
        for other in planned:
            if other["id"] != law_id and other.get("parent") == parent:
                composes.add(other["id"])
    # children of this candidate (within planned)
    for other in planned:
        if other.get("parent") == law_id:
            composes.add(other["id"])
    composes.discard(law_id)
    return composes


def run():
    canonical = json.loads(CANONICAL_DATA.read_text(encoding="utf-8"))
    sandbox = json.loads(SANDBOX_DATA.read_text(encoding="utf-8"))

    canonical_ids = {n["id"] for n in canonical["nodes"]}
    sandbox_existing_ids = {n["id"] for n in sandbox["nodes"]}

    integrated = []
    quarantined = []

    for cand in CANDIDATES:
        cid = cand["id"]
        # Phase 1 — Detection
        if cand["family"] not in CANONICAL_FAMILIES:
            quarantined.append({"id":cid,"reason":"family not canonical","phase":1}); continue
        # Parent must exist (canonical OR planned-sandbox)
        parent = cand["parent"]
        if parent not in canonical_ids and parent not in {c["id"] for c in CANDIDATES}:
            quarantined.append({"id":cid,"reason":f"parent '{parent}' unknown","phase":1}); continue

        # Phase 2 — Frames
        f_ = cand["frames"]
        if not all(k in f_ for k in ("local","intermediate","global","proxies","limits")):
            quarantined.append({"id":cid,"reason":"frames incomplete","phase":2}); continue
        if not f_["intermediate"] or not f_["limits"]:
            quarantined.append({"id":cid,"reason":"intermediate or limits empty","phase":2}); continue
        if any(e["level"] not in INTERMEDIATE_LEVELS for e in f_["intermediate"]):
            quarantined.append({"id":cid,"reason":"level invalid","phase":2}); continue

        # Phase 3 — Démonstration
        if len(cand["html_description"]) < 40:
            quarantined.append({"id":cid,"reason":"description short","phase":3}); continue
        if not (cand["equations"] or cand["examples"]):
            quarantined.append({"id":cid,"reason":"no grounding","phase":3}); continue

        # Phase 4 — Composition ≥ 3
        comps = count_compositions(cid, canonical, sandbox_existing_ids, CANDIDATES, parent)
        if len(comps) < 3:
            quarantined.append({"id":cid,"reason":f"comps {len(comps)}<3","phase":4,
                                "found":list(comps)}); continue

        # Pipeline complete — integrate to SANDBOX (NOT canonical)
        node = {
            "id": cand["id"],
            "title": cand["title"],
            "canonical": cand["canonical"],
            "palieronic": cand["palieronic"],
            "family": cand["family"],
            "attractor_tier": None,
            "domains": cand["domains"],
            "examples": cand["examples"],
            "html_description": cand["html_description"],
            "equations": cand["equations"],
            "S_local": cand["S_local"],
            "S_global": cand["S_global"],
            "stability": cand["stability"],
            "weight": cand["weight"],
            "frames": cand["frames"],

            # SANDBOX METADATA — Mission 1 reversibility
            "_sandbox": True,
            "_sandbox_state": "incubation",
            "_created_at": "2026-05-15T20:44:00+02:00",
            "_last_revisited": "2026-05-15T20:44:00+02:00",
            "_decay_score": 0.0,
            "_promotion_score": 0.0,
            "_archive_reason": None,
            "_sandbox_origin": f"{BATCH_ID}_{hash_law(cand)}",
            "_compositions_count": len(comps),
            "_oracle_validation": {
                "phase_1_detection": "pass",
                "phase_2_frames": "pass",
                "phase_3_demonstration": "pass",
                "phase_4_composition_count": len(comps),
                "phase_5_fractal_potential": "leaf" if len(cand["id"].split("-")) >= 3 else "candidate",
                "phase_6_reversible": True
            },

            # REVERSIBILITY METADATA
            "reversible": True,
            "rollback_dependencies": cand.get("_rollback_deps_planned", []),
            "canonical_status": "sandbox",
            "runtime_admissible": False
        }
        sandbox["nodes"].append(node)
        # Add parent edge (only if parent in canonical OR in same sandbox)
        sandbox["edges"].append({
            "source": cid, "target": parent, "kind": "parent"
        })
        integrated.append(node)

    sandbox["_meta"]["incubation_count"] = sum(1 for n in sandbox["nodes"]
                                                if n.get("_sandbox_state") == "incubation")
    sandbox["_meta"]["last_audit_ts"] = "2026-05-15T20:44:00+02:00"

    SANDBOX_DATA.write_text(json.dumps(sandbox, indent=2, ensure_ascii=False) + "\n",
                            encoding="utf-8")

    SANDBOX_LOG.parent.mkdir(parents=True, exist_ok=True)
    SANDBOX_LOG.write_text(json.dumps({
        "mission_id": "ZORAN_REVERSIBLE_100_LAWS_PIPELINE_20260515",
        "batch_id": BATCH_ID,
        "candidates_total": len(CANDIDATES),
        "integrated_count": len(integrated),
        "quarantined_count": len(quarantined),
        "integrated": [{"id":n["id"],"family":n["family"],"parent":n.get("rollback_dependencies",[]),
                        "compositions_count":n["_compositions_count"],
                        "_sandbox_origin":n["_sandbox_origin"]} for n in integrated]
    }, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    QUARANTINE_LOG.write_text(json.dumps({
        "mission_id": "ZORAN_REVERSIBLE_100_LAWS_PIPELINE_20260515",
        "batch_id": BATCH_ID,
        "quarantined_count": len(quarantined),
        "quarantined": quarantined
    }, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    print(f"\nSANDBOX MISSION 1 — Reversible 100 laws")
    print(f"  Candidates total : {len(CANDIDATES)}")
    print(f"  Integrated to sandbox: {len(integrated)}")
    print(f"  Quarantined         : {len(quarantined)}")
    print(f"  Sandbox total nodes : {len(sandbox['nodes'])}")
    print(f"  CanonicalGraph nodes: {len(canonical['nodes'])} (UNCHANGED)")


if __name__ == "__main__":
    run()
