#!/usr/bin/env python3
"""ZORAN P2 — 100 lois prioritisées Zoran>LLM>mémoire>calcul>rigueur>anti-hallu>user.

Pipeline 6-phases identique à add_p1_laws.py.
Ajoute aussi runtime_admissible=True à chaque ajout intégré.

Distribution cible :
  ULG  : ~10 lois (LLM cognitif — embeddings, grammaire latente)
  DVE  : ~8 lois (variantes contrôlées, anti-hallucination)
  UDE  : ~12 lois (découverte, retrieval, mémoire externe)
  GHUC : ~12 lois (consolidation Oracle, calibration)
  WP11 : ~12 lois (rigueur métriques, audit compositionnel)
  WP12 : ~12 lois (admissibilité, anti-hallucination, traçabilité)
  SDE  : ~10 lois (attention/focus/explainability LLM)
  PAL  : ~10 lois (transitions cognitives, calibration runtime)
  Transverse : ~14 (iso bridges, compositions, cross-axes)
  Total : ~100
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "app" / "data" / "laws.json"
QUARANTINE = ROOT / "audit" / "QUARANTINE_LOG_P2.json"
INTEGRATION = ROOT / "audit" / "INTEGRATION_LOG_P2.json"

CANONICAL_FAMILIES = {"ULG", "DVE", "UDE", "GHUC", "WP11", "WP12", "SDE", "PAL"}
INTERMEDIATE_LEVELS = {"micro", "meso", "macro", "systémique"}


def f(local, intermediate, global_, proxies, limits):
    return {"local": local, "intermediate": intermediate, "global": global_,
            "proxies": proxies, "limits": limits}


def law(id, title, family, parent, *, canonical=False, palieronic=False,
        domains, examples=None, equations=None, description,
        S_local, S_global, weight, stability="stable", frames):
    return {
        "id": id, "title": title, "family": family, "parent": parent,
        "canonical": canonical, "palieronic": palieronic,
        "domains": list(domains), "examples": list(examples or []),
        "equations": list(equations or []),
        "html_description": description,
        "S_local": S_local, "S_global": S_global, "weight": weight,
        "stability": stability, "frames": frames,
    }


def fr_local(scope): return [scope]
def fr_inter(*items): return [{"level": l, "scope": s} for l, s in items]


CANDIDATES = [
    # ─────────── ULG (LLM cognitif — embeddings, grammaire latente) ───────────
    law("ULG-008", "Embedding cross-modèle invariant", "ULG", "ULG-001",
        domains=["embeddings", "cross-modèle"],
        examples=["Alignement entre embeddings GPT/Claude/Gemini sur même invariant"],
        equations=["sim(emb_M1(x), emb_M2(x)) ≥ θ"],
        description="Mesure d'invariance d'embedding cross-modèle ; les modèles distincts produisent des représentations alignées sur les invariants ULG.",
        S_local=0.84, S_global=0.74, weight=0.65,
        frames=f(fr_local("paire de modèles M1, M2"),
                 fr_inter(("meso","ULG"), ("macro","modèles d'embeddings contemporains")),
                 ["alignement universel des invariants morphologiques"],
                 ["cosine cross-modèle θ ≥ 0.85"],
                 ["dépend du choix de θ ; modèles très différents peuvent diverger"])),
    law("ULG-009", "Latence représentationnelle", "ULG", "ULG-001",
        domains=["latence", "représentation"],
        examples=["Délai entre input symbolique et stabilisation de l'embedding"],
        equations=["τ_lat = inf{ t : ‖emb(t) − emb(∞)‖ < ε }"],
        description="Temps caractéristique de stabilisation d'une représentation latente après input.",
        S_local=0.82, S_global=0.71, weight=0.60,
        frames=f(fr_local("input x et trajectoire emb(t)"),
                 fr_inter(("meso","ULG"), ("macro","systèmes représentationnels dynamiques")),
                 ["distribution globale des τ_lat"],
                 ["mesure expérimentale par sondage"],
                 ["dépend de l'architecture du modèle"])),
    law("ULG-010", "Grammaire compositionnelle locale", "ULG", "ULG-001",
        domains=["compositionnalité", "grammaire"],
        examples=["Combinaison locale de tokens préservant le sens"],
        equations=["compose(t1, t2) ∈ L_grammar"],
        description="Une combinaison locale de tokens reste dans la grammaire latente si chaque sous-combinaison y est.",
        S_local=0.86, S_global=0.75, weight=0.66,
        frames=f(fr_local("paire de tokens (t1, t2)"),
                 fr_inter(("meso","ULG"), ("macro","syntaxe latente émergente")),
                 ["clôture grammaticale globale"],
                 ["test d'admissibilité par sampling"],
                 ["compositionnalité non garantie pour > 5 tokens"])),
    law("ULG-011", "Désambiguïsation contextuelle", "ULG", "ULG-001",
        domains=["désambiguïsation", "contexte"],
        examples=["Résolution d'un mot polysémique selon le contexte"],
        equations=["disamb(w, ctx) = argmax_s P(s | w, ctx)"],
        description="Sélection du sens d'un token polysémique en maximisant la probabilité conditionnelle au contexte.",
        S_local=0.85, S_global=0.74, weight=0.65,
        frames=f(fr_local("token w et contexte ctx"),
                 fr_inter(("meso","ULG"), ("macro","sémantique distributionnelle")),
                 ["distribution globale des sens disponibles"],
                 ["P(s|w,ctx) estimée par modèle"],
                 ["dépend de la qualité de l'estimation P"])),
    law("ULG-012", "Compression représentationnelle", "ULG", "ULG-004",
        domains=["compression", "représentation"],
        examples=["Quantization d'embeddings sans perte de structure"],
        equations=["dim(emb_compressed) ≤ k ∧ I_struct préservé"],
        description="Une représentation peut être compressée à dim ≤ k tant que I_struct est préservé.",
        S_local=0.83, S_global=0.72, weight=0.62,
        frames=f(fr_local("embedding e à compresser"),
                 fr_inter(("meso","ULG"), ("macro","GHUC compression sémantique")),
                 ["taux de compression admissible global"],
                 ["test post-compression sur tâches downstream"],
                 ["compression agressive perd les nuances rares"])),
    law("ULG-013", "Stabilité sous perturbation lexicale", "ULG", "ULG-003",
        domains=["robustesse", "lexique"],
        examples=["Invariance sous synonymie ou faute de frappe mineure"],
        equations=["‖emb(x) − emb(perturb(x))‖ ≤ δ"],
        description="L'embedding est robuste à de petites perturbations lexicales (synonymie, typos).",
        S_local=0.84, S_global=0.73, weight=0.63,
        frames=f(fr_local("token x et perturbation"),
                 fr_inter(("meso","ULG"), ("macro","robustesse linguistique")),
                 ["ensemble des perturbations admissibles"],
                 ["mesure adversarial sur dataset"],
                 ["seuil δ subjectif"])),
    law("ULG-014", "Co-référence temporelle", "ULG", "ULG-002",
        domains=["co-référence", "temps"],
        examples=["« il » référant à une entité mentionnée précédemment"],
        equations=["coref(token_t, mentions_<t)"],
        description="Résolution de référence anaphorique vers les mentions antérieures.",
        S_local=0.81, S_global=0.69, weight=0.58,
        frames=f(fr_local("token courant et historique"),
                 fr_inter(("meso","ULG"), ("macro","traitement du discours")),
                 ["graphe de co-référence sur le document"],
                 ["modèle de co-référence statistique"],
                 ["échec sur ambiguïtés multiples"])),
    law("ULG-015", "Densité informationnelle ajustée", "ULG", "ULG-004",
        domains=["densité", "information"],
        examples=["Mesure d'entropie locale ajustée par contexte"],
        equations=["H_local(x | ctx) ≠ H_local(x)"],
        description="L'entropie informationnelle d'un token dépend du contexte, pas seulement de son occurrence.",
        S_local=0.82, S_global=0.71, weight=0.60,
        frames=f(fr_local("token x et son contexte"),
                 fr_inter(("meso","ULG")),
                 ["distribution conditionnelle globale"],
                 ["estimation H par maximum vraisemblance"],
                 ["estimation biaisée sur petit corpus"])),
    law("ULG-016", "Migration cross-langue d'invariant", "ULG", "ULG-003",
        domains=["multilingue", "invariant"],
        examples=["Invariant ULG préservé entre représentations EN/FR/JA"],
        equations=["Inv_ULG(emb_EN(x)) ≈ Inv_ULG(emb_FR(translation(x)))"],
        description="Les invariants morphologiques ULG sont préservés au passage cross-langue.",
        S_local=0.83, S_global=0.72, weight=0.62,
        frames=f(fr_local("paire (texte, traduction)"),
                 fr_inter(("meso","ULG"), ("macro","alignement multilingue")),
                 ["clôture des invariants sur toutes les langues"],
                 ["alignement par parallel corpus"],
                 ["dépend de la qualité de la traduction"])),
    law("ULG-017", "Compactification asymptotique", "ULG", "ULG-002",
        domains=["compactification", "asymptote"],
        examples=["Embedding tendant vers un sous-espace compact à grand échantillon"],
        equations=["lim_{n→∞} support(emb_corpus_n) ⊂ K compact"],
        description="Avec corpus suffisant, l'espace effectif des embeddings se concentre sur un compact.",
        S_local=0.80, S_global=0.69, weight=0.56,
        frames=f(fr_local("corpus de taille n"),
                 fr_inter(("meso","ULG"), ("macro","statistiques de modèles")),
                 ["compact limite global"],
                 ["mesure dimension intrinsèque"],
                 ["asymptote théorique non observable"])),

    # ─────────── DVE (variantes contrôlées + anti-hallucination) ───────────
    law("DVE-008", "Variant filtering anti-hallucination", "DVE", "DVE-005",
        domains=["filtrage", "anti-hallucination"],
        examples=["Élimination des variantes incohérentes par check WP-12"],
        equations=["filter_AH(v) = admissible_WP12(v) ∧ ¬contradicts(v, base)"],
        description="Filtrage des variantes pour éliminer celles qui hallucinent (contradiction avec base ou inadmissibles WP-12).",
        S_local=0.89, S_global=0.78, weight=0.70,
        frames=f(fr_local("variante v candidate"),
                 fr_inter(("meso","DVE"), ("macro","WP-12 admissibilité"), ("systémique","anti-hallucination")),
                 ["taux d'hallucination résiduel global"],
                 ["test sur jeu de prompts adversaires"],
                 ["dépend de la complétude de la base de référence"])),
    law("DVE-009", "Variance contrôlée multi-modèles", "DVE", "DVE-001",
        domains=["multi-modèles", "variance"],
        examples=["Génération par 3 modèles puis sélection par majorité"],
        equations=["select(M1(x), M2(x), M3(x)) = majority"],
        description="Génération de variantes par plusieurs modèles puis sélection par vote ou cohérence.",
        S_local=0.85, S_global=0.74, weight=0.65,
        frames=f(fr_local("input x et ensemble de modèles"),
                 fr_inter(("meso","DVE"), ("macro","ensemble methods")),
                 ["distribution des accords inter-modèles"],
                 ["mesure d'accord par paire"],
                 ["coût computationnel multiplié par |M|"])),
    law("DVE-010", "Bifurcation à seuil de risque", "DVE", "DVE-003",
        domains=["bifurcation", "risque"],
        examples=["Génération de la variante prudente si risque > τ"],
        equations=["if risk(x) > τ : output safe_variant(x)"],
        description="Activation d'une variante prudente quand le risque estimé dépasse un seuil.",
        S_local=0.87, S_global=0.76, weight=0.67,
        frames=f(fr_local("input x et estimation risk(x)"),
                 fr_inter(("meso","DVE"), ("macro","sécurité opérationnelle")),
                 ["politique globale de gestion des risques"],
                 ["estimation risk par modèle dédié"],
                 ["seuil τ contextuel"])),
    law("DVE-011", "Variant pruning par cohérence", "DVE", "DVE-005",
        domains=["pruning", "cohérence"],
        examples=["Élimination de variantes incohérentes avec contexte"],
        equations=["prune(v) ⟺ S_local(v|ctx) < θ"],
        description="Élimination des variantes dont la cohérence locale au contexte est sous le seuil.",
        S_local=0.86, S_global=0.75, weight=0.66,
        frames=f(fr_local("variante v et contexte ctx"),
                 fr_inter(("meso","DVE"), ("macro","WP-11 cohérence")),
                 ["taux global de pruning"],
                 ["S_local(v|ctx) calculé par WP11-002"],
                 ["seuil θ statique"])),
    law("DVE-012", "Diversité contrainte", "DVE", "DVE-001",
        domains=["diversité", "contrainte"],
        examples=["Génération de N variantes maximalement diverses sous contrainte cohérence"],
        equations=["max diversity({v_i}) s.c. cohérence(v_i) ≥ θ"],
        description="Maximisation de la diversité d'un set de variantes sous contrainte de cohérence individuelle.",
        S_local=0.84, S_global=0.73, weight=0.63,
        frames=f(fr_local("ensemble {v_i} candidat"),
                 fr_inter(("meso","DVE"), ("macro","exploration combinatoire")),
                 ["politique d'exploration globale"],
                 ["distance pairwise + score cohérence"],
                 ["trade-off diversité/cohérence non linéaire"])),
    law("DVE-013", "Trace de génération réversible", "DVE", "DVE-002",
        domains=["traçabilité", "réversibilité"],
        examples=["Log complet du chemin génératif"],
        equations=["replay(trace(gen(x))) = gen(x)"],
        description="La génération est traçable et reproductible étant donnée la trace.",
        S_local=0.90, S_global=0.79, weight=0.71,
        frames=f(fr_local("génération g et sa trace"),
                 fr_inter(("meso","DVE"), ("macro","WP-12 réversibilité"), ("systémique","audit")),
                 ["registre global des traces"],
                 ["test de replay sur jeu d'audit"],
                 ["coût de stockage proportionnel à |trace|"])),
    law("DVE-014", "Stop early sur convergence", "DVE", "DVE-003",
        domains=["arrêt", "convergence"],
        examples=["Arrêt génératif quand ΔS_local < ε"],
        equations=["stop_gen ⟺ ΔS_local(t) < ε"],
        description="Arrêt précoce de la génération dès que la cohérence locale converge sous un seuil.",
        S_local=0.85, S_global=0.74, weight=0.65,
        frames=f(fr_local("trajectoire de génération"),
                 fr_inter(("meso","DVE")),
                 ["politique globale d'arrêt"],
                 ["ΔS_local sur fenêtre glissante"],
                 ["faux arrêts si ε trop large"])),
    law("DVE-015", "Variant scoring multi-critère", "DVE", "DVE-001",
        domains=["scoring", "multi-critère"],
        examples=["Score combinant cohérence, diversité, coût"],
        equations=["score(v) = α·coh + β·div − γ·cost"],
        description="Évaluation multi-critère des variantes pondérant cohérence, diversité, coût.",
        S_local=0.84, S_global=0.73, weight=0.63,
        frames=f(fr_local("variante v"),
                 fr_inter(("meso","DVE"), ("macro","optimisation multi-objectif")),
                 ["frontière de Pareto globale"],
                 ["pondérations α,β,γ calibrées"],
                 ["pondérations dépendantes du domaine"])),

    # ─────────── UDE (découverte, retrieval, mémoire externe) ───────────
    law("UDE-009", "Retrieval augmenté par graphe", "UDE", "UDE-001",
        domains=["retrieval", "graphe"],
        examples=["Recherche de loi pertinente via BFS sur graphe ZORAN"],
        equations=["retrieve(q) = top_k(BFS_score(q, graph))"],
        description="Récupération de lois pertinentes par BFS bornée sur le graphe ZORAN (cf. CLE).",
        S_local=0.88, S_global=0.77, weight=0.70,
        frames=f(fr_local("query q et noeud ancre"),
                 fr_inter(("meso","UDE"), ("macro","CLE"), ("systémique","ZenRuntime")),
                 ["registre global des retrievals"],
                 ["budget BFS profondeur ≤ 2"],
                 ["fragilité aux fausses ancres"])),
    law("UDE-010", "Mémoire externe vectorielle", "UDE", "UDE-001",
        domains=["mémoire", "vectoriel"],
        examples=["Vector DB stockant embeddings + metadata"],
        equations=["query(v, k) = nearest_neighbors(v, store, k)"],
        description="Mémoire externe basée sur store vectoriel pour retrieval rapide.",
        S_local=0.86, S_global=0.75, weight=0.66,
        frames=f(fr_local("vecteur v et store"),
                 fr_inter(("meso","UDE"), ("macro","vector databases")),
                 ["index global"],
                 ["ANN avec rappel quantifié"],
                 ["dépend de la qualité de l'embedding"])),
    law("UDE-011", "Découverte par contraste", "UDE", "UDE-001",
        domains=["découverte", "contraste"],
        examples=["Comparaison entre 2 corpus pour identifier divergences"],
        equations=["diff(C1, C2) = C1 \\ C2 ∪ C2 \\ C1"],
        description="Identification de structures nouvelles par contraste entre deux corpus.",
        S_local=0.85, S_global=0.74, weight=0.65,
        frames=f(fr_local("paire de corpus (C1, C2)"),
                 fr_inter(("meso","UDE"), ("macro","analyse différentielle")),
                 ["distribution des différences sur tous corpus"],
                 ["mesure de différence sur features"],
                 ["faux positifs sur corpus disparates"])),
    law("UDE-012", "Découverte par déductibilité", "UDE", "UDE-001",
        domains=["découverte", "déduction"],
        examples=["Loi inférée par déduction depuis lois existantes"],
        equations=["L_new = deduce({L_i}_known)"],
        description="Découverte d'une loi par chaînage déductif depuis le corpus existant.",
        S_local=0.83, S_global=0.72, weight=0.62,
        frames=f(fr_local("ensemble de lois prémisses"),
                 fr_inter(("meso","UDE"), ("macro","logique formelle")),
                 ["base déductive complète"],
                 ["moteur déductif validé"],
                 ["limité aux relations formalisables"])),
    law("UDE-013", "Découverte abductive", "UDE", "UDE-001",
        domains=["découverte", "abduction"],
        examples=["Loi hypothétique meilleure explication d'observations"],
        equations=["L_abd = argmax_L P(observations | L) · prior(L)"],
        description="Découverte par abduction : la loi la plus plausible expliquant un set d'observations.",
        S_local=0.81, S_global=0.69, weight=0.58,
        frames=f(fr_local("set d'observations"),
                 fr_inter(("meso","UDE"), ("macro","statistiques bayésiennes")),
                 ["distribution a priori globale"],
                 ["modélisation P(obs|L) calibrée"],
                 ["sensible au choix du prior"])),
    law("UDE-014", "Mémoire épisodique", "UDE", "UDE-001",
        domains=["mémoire", "épisodique"],
        examples=["Stockage de séquences temporelles d'interactions"],
        equations=["memory_ep = [(t_i, event_i)]_i"],
        description="Mémoire épisodique conservant les séquences temporelles d'événements.",
        S_local=0.82, S_global=0.71, weight=0.60,
        frames=f(fr_local("événement e à temps t"),
                 fr_inter(("meso","UDE"), ("macro","mémoire à long terme")),
                 ["historique global des sessions"],
                 ["index temporel"],
                 ["coût mémoire croissant linéairement"])),
    law("UDE-015", "Mémoire procédurale", "UDE", "UDE-001",
        domains=["mémoire", "procédurale"],
        examples=["Cache de procédures fréquemment exécutées"],
        equations=["cache_proc[hash(proc)] = result"],
        description="Mémoire procédurale stockant les procédures et leurs résultats.",
        S_local=0.83, S_global=0.72, weight=0.61,
        frames=f(fr_local("procédure proc et arguments"),
                 fr_inter(("meso","UDE")),
                 ["politique globale de cache"],
                 ["LRU ou LFU"],
                 ["taille bornée — éviction"])),
    law("UDE-016", "Découverte par invariants", "UDE", "UDE-002",
        domains=["découverte", "invariants"],
        examples=["Identification de quantités préservées dans une dynamique"],
        equations=["Inv = {f : ∀ t, f(state(t)) = const}"],
        description="Découverte d'invariants par identification de quantités conservées sous dynamique.",
        S_local=0.85, S_global=0.74, weight=0.64,
        frames=f(fr_local("dynamique state(t)"),
                 fr_inter(("meso","UDE"), ("macro","mécanique des systèmes")),
                 ["espace de tous les invariants"],
                 ["régression sur quantités candidates"],
                 ["dépend du choix de dynamique observable"])),
    law("UDE-017", "Decay de pertinence mémoire", "UDE", "UDE-001",
        domains=["mémoire", "decay"],
        examples=["Pertinence d'un souvenir décroissant avec le temps"],
        equations=["pertinence(e, now) = exp(−λ·(now − t_e))"],
        description="Pertinence d'un événement mémorisé décroissant exponentiellement avec le temps.",
        S_local=0.81, S_global=0.69, weight=0.57,
        frames=f(fr_local("événement e"),
                 fr_inter(("meso","UDE")),
                 ["politique globale de decay"],
                 ["λ calibré par usage"],
                 ["events critiques peuvent décayer trop vite"])),
    law("UDE-018", "Refresh de mémoire par usage", "UDE", "UDE-001",
        domains=["mémoire", "renforcement"],
        examples=["Reset du timer de decay à chaque accès"],
        equations=["t_e ← now sur access(e)"],
        description="L'accès à un événement mémorisé renforce sa pertinence (reset decay).",
        S_local=0.82, S_global=0.71, weight=0.59,
        frames=f(fr_local("événement e accédé"),
                 fr_inter(("meso","UDE")),
                 ["distribution globale des access"],
                 ["log d'access"],
                 ["risque de bias sur events fréquents"])),
    law("UDE-019", "Index sémantique relationnel", "UDE", "UDE-001",
        domains=["index", "relationnel"],
        examples=["Index sur relations (parent, iso, ...) pour query rapide"],
        equations=["index[relation] = sorted(edges of that kind)"],
        description="Index sémantique permettant retrieval rapide selon types de relations.",
        S_local=0.84, S_global=0.73, weight=0.62,
        frames=f(fr_local("relation kind"),
                 fr_inter(("meso","UDE"), ("macro","databases relationnelles")),
                 ["index global"],
                 ["lookup en O(log N)"],
                 ["coût mise à jour à chaque ajout"])),

    # ─────────── GHUC (consolidation Oracle, calibration) ───────────
    law("GHUC-006", "Audit pré-prompt", "GHUC", "GHUC-005",
        domains=["audit", "prompt"],
        examples=["Vérification des contraintes runtime avant exécution prompt"],
        equations=["audit(prompt) ∧ admissible(prompt) ⇒ execute"],
        description="Tout prompt subit un audit pré-exécution validant ses contraintes runtime.",
        S_local=0.89, S_global=0.79, weight=0.70,
        frames=f(fr_local("prompt p"),
                 fr_inter(("meso","GHUC"), ("macro","Oracle"), ("systémique","ZenRuntime")),
                 ["politique globale d'audit"],
                 ["check Core rules + Adaptive rules"],
                 ["surcoût latence ~5-10ms"])),
    law("GHUC-007", "Consolidation post-batch", "GHUC", "GHUC-001",
        domains=["consolidation", "batch"],
        examples=["Audit consolidé après chaque batch d'ajouts"],
        equations=["consolidate(batch) ⇒ audit_global"],
        description="Audit complet de cohérence systémique exécuté après chaque batch d'ajouts.",
        S_local=0.90, S_global=0.80, weight=0.71,
        frames=f(fr_local("batch b ajouté"),
                 fr_inter(("meso","GHUC"), ("macro","Oracle audit"), ("systémique","HS evolution")),
                 ["historique HS"],
                 ["recalcul HS + S_global"],
                 ["coût computationnel proportionnel à |graph|"])),
    law("GHUC-008", "Rollback automatique sur HS↓", "GHUC", "GHUC-001",
        domains=["rollback", "HS"],
        examples=["Annulation auto si HS_après < HS_avant"],
        equations=["HS_after < HS_before ⇒ rollback"],
        description="Mécanisme de rollback automatique déclenché par dégradation de HS post-modification.",
        S_local=0.92, S_global=0.81, weight=0.74,
        frames=f(fr_local("modification m"),
                 fr_inter(("meso","GHUC"), ("macro","R-CORE-6"), ("systémique","gouvernance")),
                 ["protection systémique global"],
                 ["snapshot avant chaque modification"],
                 ["rollback partiel impossible — atomique"])),
    law("GHUC-009", "Consolidation des isomorphismes", "GHUC", "GHUC-004",
        domains=["consolidation", "iso"],
        examples=["Fusion de deux iso redondants en un seul"],
        equations=["iso_merge(e1, e2) si invariants(e1) ⊂ invariants(e2)"],
        description="Consolidation des arêtes iso redondantes par fusion d'invariants.",
        S_local=0.85, S_global=0.74, weight=0.64,
        frames=f(fr_local("paire iso (e1, e2)"),
                 fr_inter(("meso","GHUC")),
                 ["registre global des iso"],
                 ["test inclusion d'invariants"],
                 ["fusion irréversible — audit"])),
    law("GHUC-010", "Audit de quarantine", "GHUC", "GHUC-005",
        domains=["audit", "quarantine"],
        examples=["Revue périodique de la sandbox pour promotion candidate"],
        equations=["audit_sandbox(now) ⇒ promotions + decays"],
        description="Audit périodique de la DiscoverySandbox déclenchant promotions et decays.",
        S_local=0.87, S_global=0.77, weight=0.67,
        frames=f(fr_local("sandbox snapshot"),
                 fr_inter(("meso","GHUC"), ("macro","DiscoverySandbox")),
                 ["politique globale d'audit sandbox"],
                 ["fréquence calibrable"],
                 ["coût proportionnel à |sandbox|"])),
    law("GHUC-011", "Compression de graphe par clustering", "GHUC", "GHUC-002",
        domains=["compression", "clustering"],
        examples=["Regroupement de lois sœurs pour réduire la densité visible"],
        equations=["cluster(F) → super-nœud avec details détachés"],
        description="Compression visuelle par regroupement de lois d'une famille en super-nœud.",
        S_local=0.83, S_global=0.72, weight=0.62,
        frames=f(fr_local("famille F"),
                 fr_inter(("meso","GHUC"), ("macro","UX visualisation")),
                 ["politique de regroupement systémique"],
                 ["seuil |F| > 8 → compression"],
                 ["perte de détail visuel — détail à la demande"])),
    law("GHUC-012", "Détection de doublon sémantique", "GHUC", "GHUC-002",
        domains=["doublon", "sémantique"],
        examples=["Identification de deux lois exprimant la même idée différemment"],
        equations=["dup(L1, L2) ⟺ cosine_titles ≥ 0.92 ∧ cosine_descriptions ≥ 0.85"],
        description="Détection automatique de doublons sémantiques entre deux lois.",
        S_local=0.86, S_global=0.75, weight=0.65,
        frames=f(fr_local("paire (L1, L2)"),
                 fr_inter(("meso","GHUC")),
                 ["registre des doublons à fusionner"],
                 ["embeddings + cosine"],
                 ["seuils calibrables — risque faux positif"])),
    law("GHUC-013", "Pruning par redondance d'arêtes", "GHUC", "GHUC-003",
        domains=["pruning", "arêtes"],
        examples=["Suppression d'arêtes related dupliquant parent"],
        equations=["prune(e) si ∃ e' tel que kind(e') ≠ related ∧ endpoints égaux"],
        description="Suppression des arêtes related quand une arête plus structurante existe entre les mêmes nœuds.",
        S_local=0.88, S_global=0.78, weight=0.68,
        frames=f(fr_local("arête e candidate"),
                 fr_inter(("meso","GHUC")),
                 ["graphe global après pruning"],
                 ["scan paires (source, target)"],
                 ["ne traite pas les related justifiés"])),
    law("GHUC-014", "Audit historique d'admissibilité", "GHUC", "GHUC-005",
        domains=["audit", "histoire"],
        examples=["Revue rétroactive des admissions passées"],
        equations=["audit_retro(window) → re-evaluation"],
        description="Revue rétroactive des décisions d'admission passées avec critères à jour.",
        S_local=0.84, S_global=0.73, weight=0.63,
        frames=f(fr_local("fenêtre temporelle"),
                 fr_inter(("meso","GHUC"), ("macro","Oracle")),
                 ["historique d'audit"],
                 ["replay des décisions"],
                 ["coût proportionnel à |historique|"])),
    law("GHUC-015", "Calibration cross-batch", "GHUC", "GHUC-001",
        domains=["calibration", "cross-batch"],
        examples=["Ajustement seuils selon performance batch précédent"],
        equations=["thresholds(t+1) = update(thresholds(t), feedback(batch_t))"],
        description="Calibration adaptative des seuils selon le retour du batch précédent.",
        S_local=0.87, S_global=0.76, weight=0.66,
        frames=f(fr_local("batch t et performance"),
                 fr_inter(("meso","GHUC"), ("macro","Adaptive"), ("systémique","Oracle")),
                 ["historique des seuils"],
                 ["update via Adaptive"],
                 ["risque oscillation si feedback bruité"])),

    # ─────────── WP11 (rigueur métriques, audit compositionnel) ───────────
    law("WP11-008", "Décomposition stricte de S_global", "WP11", "WP11-003",
        domains=["décomposition", "S_global"],
        examples=["S_global = α·C_struct + β·C_comp + γ·C_iso − δ·contradictions"],
        equations=["S_global = 0.35·C_struct + 0.40·C_comp + 0.15·C_iso − 0.10·contr_density"],
        description="S_global se décompose strictement en 4 composantes pondérées, jamais en moyenne S_local.",
        S_local=0.94, S_global=0.84, weight=0.78,
        frames=f(fr_local("calcul de S_global"),
                 fr_inter(("meso","WP11"), ("macro","R-CORE-2"), ("systémique","Oracle Core")),
                 ["formule globale invariante"],
                 ["coefficients calibrables (Adaptive)"],
                 ["dépend de la définition de C_comp"])),
    law("WP11-009", "Score de rigueur épistémique", "WP11", "WP11-001",
        domains=["rigueur", "épistémologie"],
        examples=["Score combinant grounding + composition + tests"],
        equations=["rigor = w1·grounding + w2·comp + w3·tests"],
        description="Mesure de rigueur épistémique d'une loi combinant grounding (eq/ex), compositions, et tests.",
        S_local=0.89, S_global=0.79, weight=0.72,
        frames=f(fr_local("loi L"),
                 fr_inter(("meso","WP11"), ("macro","WP12 admissibilité")),
                 ["distribution globale des scores"],
                 ["audit programmatique"],
                 ["pondérations subjectives à calibrer"])),
    law("WP11-010", "Audit de non-circularité", "WP11", "WP11-005",
        domains=["audit", "circularité"],
        examples=["Détection de chaînes circulaires d'inférence"],
        equations=["circular(chain) ⟺ ∃ cycle dans graph(chain)"],
        description="Détection des chaînes d'inférence circulaires (auto-référentielles).",
        S_local=0.88, S_global=0.78, weight=0.69,
        frames=f(fr_local("chaîne d'inférence"),
                 fr_inter(("meso","WP11")),
                 ["graphe global des inférences"],
                 ["DFS détection de cycles"],
                 ["circularités utiles parfois (ex. récursion fractal)"])),
    law("WP11-011", "Audit de hallucination par composition", "WP11", "WP11-005",
        domains=["audit", "hallucination"],
        examples=["Détection de réponse non supportée par lois chargées"],
        equations=["hallucination ⟺ claim ∉ closure(loaded_laws)"],
        description="Détection de hallucination par vérification que toute affirmation provient des lois chargées.",
        S_local=0.93, S_global=0.83, weight=0.76,
        frames=f(fr_local("réponse runtime"),
                 fr_inter(("meso","WP11"), ("macro","ZenRuntime"), ("systémique","anti-hallucination")),
                 ["taux global d'hallucination"],
                 ["NLI ou pattern matching"],
                 ["faux positifs sur paraphrases"])),
    law("WP11-012", "Calibration de coefficients par audit", "WP11", "WP11-006",
        domains=["calibration", "audit"],
        examples=["Recalibration α,β,γ,δ sur jeu d'audits"],
        equations=["argmin_coef Σ |S_global_pred − S_global_real|"],
        description="Calibration des coefficients de S_global par minimisation de l'écart prédit/réel sur audits.",
        S_local=0.86, S_global=0.76, weight=0.66,
        frames=f(fr_local("jeu de coefficients candidats"),
                 fr_inter(("meso","WP11"), ("macro","Adaptive")),
                 ["coefficients optimaux globaux"],
                 ["recherche par grille"],
                 ["dépend de la qualité des audits"])),
    law("WP11-013", "Mesure de stabilité temporelle", "WP11", "WP11-001",
        domains=["stabilité", "temps"],
        examples=["Variance de S_local sur fenêtre temporelle"],
        equations=["stab(L, T) = 1 − var_T(S_local(L, t))"],
        description="Stabilité temporelle d'une loi : faible variance de S_local sur la fenêtre.",
        S_local=0.87, S_global=0.77, weight=0.68,
        frames=f(fr_local("loi L et fenêtre T"),
                 fr_inter(("meso","WP11"), ("macro","analyse temporelle")),
                 ["distribution globale des stabilités"],
                 ["mesure sur historique d'audits"],
                 ["fenêtre T à choisir avec soin"])),
    law("WP11-014", "Audit cross-runtime", "WP11", "WP11-001",
        domains=["audit", "runtime"],
        examples=["Vérification cohérence entre 2 instances ZenRuntime"],
        equations=["audit_cross(R1, R2) → diff"],
        description="Audit de cohérence entre instances ZenRuntime distinctes (pour distribué).",
        S_local=0.83, S_global=0.72, weight=0.61,
        frames=f(fr_local("paire (R1, R2)"),
                 fr_inter(("meso","WP11"), ("macro","ZenRuntime distribué")),
                 ["registre global des incohérences"],
                 ["diff de réponses sur jeu test"],
                 ["coût communication inter-runtime"])),
    law("WP11-015", "Détection de drift de cohérence", "WP11", "WP11-005",
        domains=["drift", "cohérence"],
        examples=["Alerte si HS chute > 0.10 sur 10 audits"],
        equations=["drift_alert ⟺ var_T(HS) > θ"],
        description="Détection de drift par variance excessive de HS sur fenêtre temporelle.",
        S_local=0.88, S_global=0.78, weight=0.69,
        frames=f(fr_local("fenêtre T d'audits"),
                 fr_inter(("meso","WP11"), ("macro","Adaptive")),
                 ["seuil drift global"],
                 ["variance HS calculée"],
                 ["faux positifs sur transitions intentionnelles"])),
    law("WP11-016", "Audit compositionnel cumulatif", "WP11", "WP11-007",
        domains=["audit", "composition"],
        examples=["Score cumulé des compositions admissibles vs échouées"],
        equations=["S_comp_cum = Σ admissible − Σ failed"],
        description="Score cumulatif d'admissibilité des compositions, signal de santé compositionnelle.",
        S_local=0.86, S_global=0.76, weight=0.65,
        frames=f(fr_local("historique des compositions"),
                 fr_inter(("meso","WP11")),
                 ["bilan global"],
                 ["compteur incrémental"],
                 ["dépend de la qualité du label admissible/failed"])),
    law("WP11-017", "Mesure d'écart inter-cadres", "WP11", "WP11-002",
        domains=["écart", "cadres"],
        examples=["S_local local-fort vs S_local local-faible : écart"],
        equations=["gap_inter_frame(L) = max_F S_local(L, F) − min_F S_local(L, F)"],
        description="Écart de S_local d'une loi entre ses différents cadres d'évaluation.",
        S_local=0.85, S_global=0.74, weight=0.64,
        frames=f(fr_local("loi L et ses cadres"),
                 fr_inter(("meso","WP11")),
                 ["distribution des écarts globaux"],
                 ["calcul par cadre"],
                 ["écart faible peut masquer fragilité commune"])),
    law("WP11-018", "Validation Oracle multi-couche", "WP11", "WP11-001",
        domains=["validation", "Oracle"],
        examples=["Audit traversant Core + Adaptive + Sandbox"],
        equations=["valid_multi(L) = Core(L) ∧ Adaptive(L) ∧ Sandbox_check(L)"],
        description="Validation traversant les 3 couches de l'Oracle (Core, Adaptive, Sandbox).",
        S_local=0.91, S_global=0.81, weight=0.74,
        frames=f(fr_local("loi L à valider"),
                 fr_inter(("meso","WP11"), ("macro","Oracle"), ("systémique","gouvernance")),
                 ["politique d'admission systémique"],
                 ["validation séquentielle Core → Adaptive → Sandbox"],
                 ["3 sources de rejet possibles"])),

    # ─────────── WP12 (admissibilité, anti-hallucination, traçabilité) ─
    law("WP12-009", "Critère anti-hallucination", "WP12", "WP12-001",
        domains=["anti-hallucination", "admissibilité"],
        examples=["Loi admissible si toutes ses affirmations sont supportées"],
        equations=["antihall(L) ⟺ ∀ claim ∈ L : claim ∈ closure(L_dependencies)"],
        description="Une loi est admissible seulement si toutes ses affirmations sont déductibles de ses dépendances.",
        S_local=0.90, S_global=0.79, weight=0.71,
        frames=f(fr_local("loi L et ses dépendances"),
                 fr_inter(("meso","WP12"), ("macro","WP-11 cohérence"), ("systémique","anti-hallucination")),
                 ["politique systémique d'admission"],
                 ["NLI sur claims vs closure"],
                 ["dépend de la complétude des dépendances"])),
    law("WP12-010", "Critère de citation obligatoire", "WP12", "WP12-001",
        domains=["citation", "admissibilité"],
        examples=["Tout label fort doit citer sa loi de preuve"],
        equations=["valid_label(label) ⟺ ∃ proof_law: cite(label, proof_law)"],
        description="Tout usage public d'un label fort (« fractal », « attracteur ») doit citer la loi de preuve.",
        S_local=0.92, S_global=0.81, weight=0.74,
        frames=f(fr_local("usage de label fort"),
                 fr_inter(("meso","WP12"), ("macro","R-CORE-12")),
                 ["registre global des labels et preuves"],
                 ["scan textuel des claims"],
                 ["false positives sur usage générique"])),
    law("WP12-011", "Critère de typage strict", "WP12", "WP12-001",
        domains=["typage", "admissibilité"],
        examples=["Une arête iso doit avoir invariants[]"],
        equations=["valid_typing(e) ⟺ schema(e) respecté"],
        description="Toute arête doit respecter strictement le schéma de son kind (cf. EDGE_SYSTEM_SPEC).",
        S_local=0.93, S_global=0.83, weight=0.76,
        frames=f(fr_local("arête e"),
                 fr_inter(("meso","WP12"), ("macro","R-CORE-8")),
                 ["registre global des schémas"],
                 ["validation programmatique"],
                 ["schéma strict — pas de polymorphisme"])),
    law("WP12-012", "Critère de complétude des frames", "WP12", "WP12-001",
        domains=["frames", "complétude"],
        examples=["Une loi sans `limits` est inadmissible"],
        equations=["valid_frames(L) ⟺ tous les 5 champs présents et non vides"],
        description="Une loi est admissible seulement si ses 5 champs frames sont présents et non vides.",
        S_local=0.93, S_global=0.83, weight=0.77,
        frames=f(fr_local("loi L et ses frames"),
                 fr_inter(("meso","WP12"), ("macro","R-CORE-4")),
                 ["politique systémique d'admission"],
                 ["validation programmatique"],
                 ["champs vagues passent encore le test"])),
    law("WP12-013", "Critère de minimal API", "WP12", "WP12-001",
        domains=["api", "minimalité"],
        examples=["Une loi doit avoir surface API minimale"],
        equations=["surface(L) ≤ θ_min"],
        description="Une loi doit avoir une surface (nombre de paramètres / dépendances) sous le seuil minimal.",
        S_local=0.84, S_global=0.73, weight=0.63,
        frames=f(fr_local("loi L et sa surface"),
                 fr_inter(("meso","WP12"), ("macro","WP12-003 minimalité")),
                 ["politique de minimalité globale"],
                 ["compte des paramètres"],
                 ["en tension avec WP12-004 fertilité"])),
    law("WP12-014", "Critère d'orthogonalité", "WP12", "WP12-001",
        domains=["orthogonalité", "admissibilité"],
        examples=["Deux lois canoniques doivent être conceptuellement orthogonales"],
        equations=["orth(L1, L2) ⟺ overlap(L1.scope, L2.scope) ≤ θ"],
        description="Deux lois canoniques distinctes doivent avoir des scopes essentiellement orthogonaux.",
        S_local=0.86, S_global=0.75, weight=0.66,
        frames=f(fr_local("paire (L1, L2)"),
                 fr_inter(("meso","WP12"), ("macro","R-CORE-3 composition")),
                 ["matrice d'orthogonalité globale"],
                 ["overlap par embedding"],
                 ["seuil θ subjectif"])),
    law("WP12-015", "Critère de conservativité", "WP12", "WP12-001",
        domains=["conservativité", "admissibilité"],
        examples=["Modification ne doit pas casser les invariants existants"],
        equations=["conservative(modif) ⟺ ∀ inv : inv préservé"],
        description="Une modification est admissible si elle préserve tous les invariants déjà démontrés.",
        S_local=0.91, S_global=0.81, weight=0.73,
        frames=f(fr_local("modification m et invariants"),
                 fr_inter(("meso","WP12"), ("macro","R-CORE-6 rollback")),
                 ["registre global des invariants"],
                 ["test invariant par invariant"],
                 ["coût croissant avec |invariants|"])),
    law("WP12-016", "Critère de proxy explicite", "WP12", "WP12-001",
        domains=["proxy", "admissibilité"],
        examples=["S_global publié `proxy:0.89` tant que C_composition insuffisant"],
        equations=["publish_scalar(M) ⟺ R-S2 satisfaite ; sinon `proxy:`"],
        description="Toute métrique publiée comme scalar doit satisfaire les gates ; sinon marquage `proxy:` obligatoire.",
        S_local=0.90, S_global=0.80, weight=0.71,
        frames=f(fr_local("métrique M à publier"),
                 fr_inter(("meso","WP12"), ("macro","R-S2")),
                 ["politique d'affichage systémique"],
                 ["check gate R-S2"],
                 ["risque d'over-marking proxy"])),
    law("WP12-017", "Critère de lifecycle traçable", "WP12", "WP12-007",
        domains=["lifecycle", "traçabilité"],
        examples=["Création → modification → archivage avec horodatage"],
        equations=["history(L) = [(t_i, action_i, hash_i)]"],
        description="Toute loi a un historique de cycle de vie horodaté et hash-traçable.",
        S_local=0.89, S_global=0.79, weight=0.69,
        frames=f(fr_local("loi L et son historique"),
                 fr_inter(("meso","WP12"), ("macro","gouvernance"), ("systémique","audit")),
                 ["registre global des lifecycles"],
                 ["log append-only"],
                 ["coût stockage croissant"])),
    law("WP12-018", "Critère de réfutabilité", "WP12", "WP12-001",
        domains=["réfutabilité", "admissibilité"],
        examples=["Loi admissible si une expérience peut la réfuter"],
        equations=["refutable(L) ⟺ ∃ test_T : T(L) = false possible"],
        description="Une loi est admissible seulement si elle est en principe réfutable (popperien).",
        S_local=0.87, S_global=0.77, weight=0.68,
        frames=f(fr_local("loi L et tests possibles"),
                 fr_inter(("meso","WP12"), ("macro","épistémologie scientifique")),
                 ["espace des tests admissibles"],
                 ["énumération des tests"],
                 ["lois trop générales non réfutables"])),
    law("WP12-019", "Critère d'auditabilité user", "WP12", "WP12-007",
        domains=["audit", "user"],
        examples=["Utilisateur peut requérir l'audit complet d'une réponse"],
        equations=["audit_user_request(response) → trace + lois utilisées"],
        description="Toute réponse runtime peut être auditée par l'utilisateur (transparence).",
        S_local=0.88, S_global=0.78, weight=0.69,
        frames=f(fr_local("réponse runtime"),
                 fr_inter(("meso","WP12"), ("macro","ZenRuntime"), ("systémique","user trust")),
                 ["politique de transparence systémique"],
                 ["log telemetry runtime"],
                 ["coût latence audit"])),
    law("WP12-020", "Critère de consentement", "WP12", "WP12-001",
        domains=["consentement", "user"],
        examples=["Toute mémoire user doit avoir consentement explicite"],
        equations=["store(user_data) ⟺ consent(user, store)"],
        description="Toute mémoire portant sur l'utilisateur exige son consentement explicite préalable.",
        S_local=0.91, S_global=0.81, weight=0.73,
        frames=f(fr_local("opération sur user data"),
                 fr_inter(("meso","WP12"), ("macro","éthique data"), ("systémique","RGPD/AI Act")),
                 ["politique systémique de consentement"],
                 ["check consent store"],
                 ["consent peut être révoqué — à gérer"])),

    # ─────────── SDE (attention/focus/explainability LLM) ───────────
    law("SDE-008", "Attention sélective contextuelle", "SDE", "SDE-003",
        domains=["attention", "contexte"],
        examples=["Focus sur sous-prompt pertinent dans une longue conversation"],
        equations=["focus(ctx) = top_k(relevance(token_i, query) for token_i ∈ ctx)"],
        description="Sélection des tokens contextuels pertinents par scoring relevance.",
        S_local=0.86, S_global=0.75, weight=0.65,
        frames=f(fr_local("contexte ctx et query"),
                 fr_inter(("meso","SDE"), ("macro","attention mécanismes")),
                 ["distribution attention globale"],
                 ["scoring relevance par modèle"],
                 ["k arbitraire — calibration nécessaire"])),
    law("SDE-009", "Explainability par chaîne de raisonnement", "SDE", "SDE-001",
        domains=["explainability", "chain-of-thought"],
        examples=["Réponse accompagnée d'une trace de raisonnement"],
        equations=["explain(response) = ordered(steps)"],
        description="Chaque réponse runtime est accompagnée d'une trace ordonnée des étapes de raisonnement.",
        S_local=0.89, S_global=0.79, weight=0.70,
        frames=f(fr_local("réponse runtime"),
                 fr_inter(("meso","SDE"), ("macro","interprétabilité"), ("systémique","user trust")),
                 ["politique d'explication systémique"],
                 ["log structurel des étapes"],
                 ["coût latence pour générer trace"])),
    law("SDE-010", "Focus dual : query + contraintes", "SDE", "SDE-003",
        domains=["focus", "contraintes"],
        examples=["Focus simultané sur query utilisateur et contraintes système"],
        equations=["focus_dual = query_focus ⊕ constraint_focus"],
        description="Attention dualement répartie entre query utilisateur et contraintes Oracle.",
        S_local=0.85, S_global=0.74, weight=0.64,
        frames=f(fr_local("query + contraintes Oracle"),
                 fr_inter(("meso","SDE"), ("macro","R-CORE-1 séparation")),
                 ["bilan attention global"],
                 ["pondération calibrable"],
                 ["déséquilibre risque hallucination ou rigidité"])),
    law("SDE-011", "Mémoire de regard inversée", "SDE", "SDE-002",
        domains=["mémoire", "regard"],
        examples=["L'observateur garde mémoire d'avoir été observé"],
        equations=["memory(O, X) → memory(X, O)"],
        description="Mémoire bidirectionnelle des relations d'observation : (O→X) implique trace (X←O).",
        S_local=0.83, S_global=0.72, weight=0.61,
        frames=f(fr_local("paire (O, X) et leur historique"),
                 fr_inter(("meso","SDE"), ("macro","UDE mémoire")),
                 ["registre des observations mutuelles"],
                 ["log bidirectionnel"],
                 ["coût stockage doublé"])),
    law("SDE-012", "Décomposition focal multi-niveau", "SDE", "SDE-001",
        domains=["focal", "multi-niveau"],
        examples=["Focus zoom out (macro) puis zoom in (micro) successifs"],
        equations=["focal(x) = compose(macro_focus, micro_focus)"],
        description="Décomposition hiérarchique du focus de macro vers micro pour une compréhension graduée.",
        S_local=0.82, S_global=0.71, weight=0.60,
        frames=f(fr_local("objet x et niveaux de focus"),
                 fr_inter(("meso","SDE"), ("macro","cognition graduée")),
                 ["politique de focus systémique"],
                 ["budget par niveau"],
                 ["risque de perte d'information à chaque transition"])),
    law("SDE-013", "Self-observation contrôlée", "SDE", "SDE-002",
        domains=["self", "observation"],
        examples=["LLM observant ses propres outputs avant émission"],
        equations=["self_check(output) → admissible | reject"],
        description="Auto-observation des outputs avant émission pour vérification d'admissibilité.",
        S_local=0.88, S_global=0.78, weight=0.69,
        frames=f(fr_local("output candidat"),
                 fr_inter(("meso","SDE"), ("macro","WP12 admissibilité"), ("systémique","anti-hallucination")),
                 ["politique de self-check systémique"],
                 ["second-pass de validation"],
                 ["coût latence ~2x ; risque self-confirmation bias"])),
    law("SDE-014", "Décentrage cognitif", "SDE", "SDE-002",
        domains=["décentrage", "perspective"],
        examples=["Réponse depuis perspective utilisateur, pas système"],
        equations=["decenter(response, user_perspective)"],
        description="Reformulation de la réponse selon la perspective utilisateur (theory of mind).",
        S_local=0.84, S_global=0.73, weight=0.62,
        frames=f(fr_local("réponse + perspective user"),
                 fr_inter(("meso","SDE"), ("macro","ToM cognitive science")),
                 ["politique de communication user"],
                 ["modélisation user simplifiée"],
                 ["risque de mauvaise modélisation user"])),
    law("SDE-015", "Attention à la limite (limits awareness)", "SDE", "SDE-003",
        domains=["attention", "limites"],
        examples=["Réponse incluant les limites de la loi utilisée"],
        equations=["respond(L) ⇒ inclure L.frames.limits"],
        description="Toute réponse basée sur une loi inclut explicitement les limites de cette loi.",
        S_local=0.90, S_global=0.80, weight=0.71,
        frames=f(fr_local("réponse basée sur loi L"),
                 fr_inter(("meso","SDE"), ("macro","R-CORE-4 frames"), ("systémique","anti-hubris")),
                 ["politique d'inclusion des limits"],
                 ["lookup automatique L.frames.limits"],
                 ["réponse plus longue ; user peut vouloir version courte"])),
    law("SDE-016", "Refus structuré sur lacune", "SDE", "SDE-001",
        domains=["refus", "lacune"],
        examples=["Réponse `je ne sais pas` avec citation des lois manquantes"],
        equations=["refuse(query) si missing_laws ≠ ∅"],
        description="Refus structuré quand les lois nécessaires sont absentes du CanonicalGraph (anti-hallucination).",
        S_local=0.92, S_global=0.82, weight=0.74,
        frames=f(fr_local("query et lois disponibles"),
                 fr_inter(("meso","SDE"), ("macro","ZenRuntime"), ("systémique","anti-hallucination")),
                 ["politique systémique de refus"],
                 ["check missing_laws"],
                 ["frustration user si refus fréquent"])),
    law("SDE-017", "Skopein narratif", "SDE", "SDE-001",
        domains=["narratif", "Skopein"],
        examples=["Cohérence narrative à travers une longue conversation"],
        equations=["coherent_narrative(turn_1, ..., turn_n)"],
        description="Cohérence narrative préservée à travers les tours de conversation.",
        S_local=0.84, S_global=0.73, weight=0.62,
        frames=f(fr_local("séquence de tours de conversation"),
                 fr_inter(("meso","SDE"), ("macro","UDE mémoire épisodique")),
                 ["cohérence narrative globale"],
                 ["check inter-turn par modèle"],
                 ["dégrade au-delà d'un seuil de longueur"])),

    # ─────────── PAL (transitions cognitives, calibration runtime) ───
    law("PAL-007", "Transition mode user/system", "PAL", "PAL-001",
        domains=["transition", "modes"],
        palieronic=True,
        examples=["Bascule d'un mode conversationnel à un mode tâche"],
        equations=["mode(t) ∈ {user_chat, task_exec, audit, ...}"],
        description="Transition palieronique entre modes opérationnels distincts du runtime.",
        S_local=0.82, S_global=0.71, weight=0.60,
        frames=f(fr_local("état courant du runtime"),
                 fr_inter(("meso","PAL"), ("macro","ZenRuntime")),
                 ["spectre des modes possibles"],
                 ["state machine"],
                 ["transitions abruptes mal vécues par user"])),
    law("PAL-008", "Calibration runtime par feedback", "PAL", "PAL-001",
        domains=["calibration", "feedback"],
        palieronic=True,
        examples=["Ajustement du budget CLE selon retours utilisateur"],
        equations=["budget(t+1) = update(budget(t), user_feedback)"],
        description="Ajustement palieronique des paramètres runtime selon feedback (latence/satisfaction).",
        S_local=0.84, S_global=0.73, weight=0.63,
        frames=f(fr_local("paramètre + feedback"),
                 fr_inter(("meso","PAL"), ("macro","Adaptive")),
                 ["politique d'adaptation systémique"],
                 ["agrégation feedback"],
                 ["risque oscillation si feedback contradictoire"])),
    law("PAL-009", "Saut de raffinement contextuel", "PAL", "PAL-004",
        domains=["raffinement", "contexte"],
        palieronic=True,
        examples=["Saut soudain vers granularité plus fine quand détail nécessaire"],
        equations=["depth(t+1) = depth(t) + Δ if user_drill_down"],
        description="Saut palieronique vers une granularité de détail plus fine sur demande utilisateur.",
        S_local=0.83, S_global=0.72, weight=0.61,
        frames=f(fr_local("granularité courante + demande user"),
                 fr_inter(("meso","PAL"), ("macro","UX progressive disclosure")),
                 ["politique de granularité systémique"],
                 ["détection demande user"],
                 ["sauts trop fréquents fatiguent user"])),
    law("PAL-010", "Stabilisation post-modification", "PAL", "PAL-005",
        domains=["stabilisation", "modification"],
        palieronic=True,
        examples=["Période de stabilisation forcée après modification du graphe"],
        equations=["stabilize_window after modification(graph)"],
        description="Période de stabilisation forcée après toute modification du CanonicalGraph (anti-thrashing).",
        S_local=0.86, S_global=0.76, weight=0.66,
        frames=f(fr_local("modification récente"),
                 fr_inter(("meso","PAL"), ("macro","Oracle"), ("systémique","gouvernance")),
                 ["politique anti-thrashing systémique"],
                 ["timer T_stabilize"],
                 ["bloque modifications utiles aussi"])),
    law("PAL-011", "Métastabilité sandbox", "PAL", "PAL-006",
        domains=["métastabilité", "sandbox"],
        palieronic=True,
        examples=["Loi sandbox oscillant entre review et incubation"],
        equations=["state(L_sbx, t) ∈ {incubation, review} et oscille"],
        description="État métastable d'une loi sandbox oscillant sans converger vers promotion ou archive.",
        S_local=0.79, S_global=0.67, weight=0.55,
        frames=f(fr_local("loi sandbox L_sbx"),
                 fr_inter(("meso","PAL"), ("macro","DiscoverySandbox")),
                 ["distribution des métastabilités sandbox"],
                 ["historique d'état"],
                 ["risque de stagnation indéfinie"])),
    law("PAL-012", "Transition palieronique runtime", "PAL", "PAL-002",
        domains=["transition", "runtime"],
        palieronic=True,
        examples=["Bascule load_mode strict vs relaxé selon HS"],
        equations=["load_mode = strict if HS<θ else relaxed"],
        description="Bascule palieronique du mode de chargement runtime selon HS courant.",
        S_local=0.85, S_global=0.74, weight=0.64,
        frames=f(fr_local("HS courant"),
                 fr_inter(("meso","PAL"), ("macro","ZenRuntime")),
                 ["politique mode systémique"],
                 ["seuil θ adaptatif"],
                 ["thrashing si HS oscille autour de θ"])),
    law("PAL-013", "Saut catastrophique sur HS↓↓", "PAL", "PAL-002-b-ii",
        domains=["catastrophe", "HS"],
        palieronic=True,
        examples=["Mode emergency-only si HS<0.50"],
        equations=["if HS < 0.50 ⇒ mode = emergency"],
        description="Bascule palieronique catastrophique vers mode emergency quand HS chute critique.",
        S_local=0.81, S_global=0.70, weight=0.59,
        frames=f(fr_local("HS très bas"),
                 fr_inter(("meso","PAL"), ("macro","gouvernance"), ("systémique","R-CORE-6")),
                 ["procédures d'urgence systémiques"],
                 ["check seuil HS"],
                 ["mode emergency frustrant pour user"])),
    law("PAL-014", "Réveil progressif post-stabilisation", "PAL", "PAL-005",
        domains=["réveil", "post-stabilisation"],
        palieronic=True,
        examples=["Reprise graduelle des opérations après emergency"],
        equations=["resume(t) = ramp(0, full, T_resume)"],
        description="Reprise progressive (ramp) des opérations runtime après période d'urgence.",
        S_local=0.83, S_global=0.72, weight=0.61,
        frames=f(fr_local("temps depuis fin d'emergency"),
                 fr_inter(("meso","PAL"), ("macro","gouvernance")),
                 ["politique de reprise systémique"],
                 ["timer T_resume calibrable"],
                 ["latence prolongée pour user"])),

    # ─────────── Transverse — iso bridges + cross-axes (8) ───────────
    law("WP11-019", "Calibration HS_v2 robust", "WP11", "WP11-006",
        domains=["calibration", "HS"],
        examples=["HS_v2 incluant terme robustness sous perturbation"],
        equations=["HS_v2 = HS_v1_terms + 0.10·robustness"],
        description="Version 2 de HS incluant un terme de robustness sous perturbation aléatoire.",
        S_local=0.87, S_global=0.77, weight=0.67,
        frames=f(fr_local("formule HS courante"),
                 fr_inter(("meso","WP11"), ("macro","HS_EVOLUTION.md §5")),
                 ["formule globale invariante"],
                 ["calibration empirique"],
                 ["coefficient 0.10 arbitraire — à recalibrer"])),
    law("UDE-020", "Découverte par anomalie composée", "UDE", "UDE-001",
        domains=["découverte", "anomalie"],
        examples=["Anomalie détectée par composition de plusieurs détecteurs"],
        equations=["anomaly = ∨_i detector_i(x)"],
        description="Détection d'anomalie par composition (OR) de plusieurs détecteurs spécialisés.",
        S_local=0.83, S_global=0.72, weight=0.62,
        frames=f(fr_local("input x"),
                 fr_inter(("meso","UDE"), ("macro","ensemble methods")),
                 ["distribution des anomalies vs normales"],
                 ["combinaison logique de détecteurs"],
                 ["taux de faux positifs croissant avec |détecteurs|"])),
    law("GHUC-016", "Méta-consolidation cross-mission", "GHUC", "GHUC-001",
        domains=["méta", "cross-mission"],
        examples=["Consolidation traversant plusieurs missions Zoran"],
        equations=["consolidate_meta(missions) ⇒ canonical_meta_graph"],
        description="Consolidation méta-cross-mission produisant un graphe canonique stable.",
        S_local=0.88, S_global=0.78, weight=0.69,
        frames=f(fr_local("ensemble de missions"),
                 fr_inter(("meso","GHUC"), ("macro","gouvernance"), ("systémique","Oracle")),
                 ["graphe méta-canonique global"],
                 ["scan des outputs missions"],
                 ["coût computationnel cross-mission"])),
    law("WP12-021", "Critère d'éthique runtime", "WP12", "WP12-001",
        domains=["éthique", "runtime"],
        examples=["Refus de réponses contraires au principe de non-nuisance"],
        equations=["ethic_admissible(response) ⟺ no_harm ∧ no_deceit"],
        description="Critère éthique de runtime : pas de nuisance, pas de tromperie, transparence.",
        S_local=0.91, S_global=0.81, weight=0.73,
        frames=f(fr_local("réponse candidate"),
                 fr_inter(("meso","WP12"), ("macro","éthique IA"), ("systémique","ZenRuntime")),
                 ["politique éthique systémique"],
                 ["vérifications NLI sur principes"],
                 ["frontière éthique contextuelle"])),
    law("ULG-018", "Stabilité sous adversarial", "ULG", "ULG-013",
        domains=["adversarial", "robustesse"],
        examples=["Maintien de l'embedding sous attack adversarial"],
        equations=["‖emb(x) − emb(adv(x))‖ ≤ δ_adv"],
        description="Robustesse spécifique sous attaques adversariales contrôlées.",
        S_local=0.81, S_global=0.69, weight=0.57,
        frames=f(fr_local("input x et attaque adv"),
                 fr_inter(("meso","ULG"), ("macro","sécurité ML")),
                 ["distribution des robustesses"],
                 ["test adversarial standardisé"],
                 ["adversarial évolue avec les défenses"])),
    law("SDE-018", "Skopein contradictoire admissible", "SDE", "SDE-002",
        domains=["contradictoire", "admissible"],
        examples=["Maintien d'observations contradictoires sans collapse"],
        equations=["admit_contradiction(O1, O2) si tension_documented"],
        description="Admission de relations observationnelles contradictoires si la tension est documentée.",
        S_local=0.82, S_global=0.71, weight=0.60,
        frames=f(fr_local("paire (O1, O2) contradictoires"),
                 fr_inter(("meso","SDE"), ("macro","WP-12 admissibilité")),
                 ["politique de tolérance globale"],
                 ["tension explicitement documentée"],
                 ["risque de banalisation des contradictions"])),
    law("PAL-015", "Transition focus-context", "PAL", "PAL-002",
        domains=["transition", "focus"],
        palieronic=True,
        examples=["Bascule de focus serré vers contexte large"],
        equations=["context_width(t+1) > context_width(t) sur déclencheur"],
        description="Transition palieronique de focus serré vers contexte large sur déclencheur explicite.",
        S_local=0.83, S_global=0.72, weight=0.61,
        frames=f(fr_local("focus + déclencheur"),
                 fr_inter(("meso","PAL"), ("macro","SDE attention")),
                 ["politique d'élargissement systémique"],
                 ["détection déclencheur"],
                 ["élargissement coûteux en VRAM"])),
    law("DVE-016", "Variant ranking par anti-hallu", "DVE", "DVE-005",
        domains=["ranking", "anti-hallucination"],
        examples=["Top variantes triées par grounding aux lois canoniques"],
        equations=["rank(v) = grounding_score(v, CanonicalGraph)"],
        description="Tri des variantes par score de grounding aux lois CanonicalGraph (anti-hallucination).",
        S_local=0.88, S_global=0.78, weight=0.69,
        frames=f(fr_local("ensemble de variantes"),
                 fr_inter(("meso","DVE"), ("macro","ZenRuntime"), ("systémique","anti-hallucination")),
                 ["politique de ranking systémique"],
                 ["calcul grounding par citation"],
                 ["dépend complétude CanonicalGraph"])),
]


# ──────────── New typed edges (iso, contradicts, related) ──────────────
NEW_EDGES_TYPED = [
    # iso bridges
    {"source": "ULG-008", "target": "GHUC-002", "kind": "iso",
     "invariants": ["compression sémantique préservant invariants ULG embedding"],
     "weight": 0.65},
    {"source": "DVE-008", "target": "WP12-009", "kind": "iso",
     "invariants": ["filtrage anti-hallucination ↔ critère anti-hallucination admissibilité"],
     "weight": 0.70},
    {"source": "UDE-009", "target": "WP11-005", "kind": "iso",
     "invariants": ["retrieval contextuel ↔ détection de fausse cohérence par sous-graphe"],
     "weight": 0.65},
    {"source": "SDE-013", "target": "WP11-011", "kind": "iso",
     "invariants": ["self-observation ↔ audit hallucination — boucle cohérence"],
     "weight": 0.70},
    {"source": "GHUC-008", "target": "WP12-015", "kind": "iso",
     "invariants": ["rollback automatique ↔ critère de conservativité"],
     "weight": 0.68},

    # contradicts (calibration anti-hallu vs liberté générative)
    {"source": "DVE-008", "target": "DVE-012", "kind": "contradicts",
     "weight": 0.55,
     "domain": "anti-hallucination filtre vs diversité contrainte (trade-off rigueur/exploration)"},
    {"source": "DVE-012", "target": "DVE-008", "kind": "contradicts",
     "weight": 0.55,
     "domain": "anti-hallucination filtre vs diversité contrainte (trade-off rigueur/exploration)"},

    # related (minimal)
    {"source": "WP11-011", "target": "SDE-016", "kind": "related",
     "weight": 0.45,
     "reason": "détection hallucination + refus structuré : pipeline anti-hallu complet"},
    {"source": "GHUC-015", "target": "WP11-012", "kind": "related",
     "weight": 0.45,
     "reason": "calibration cross-batch + calibration coefficients — adaptive cohérent"},
]


NEW_COMPOSITIONS = [
    {"pair": ["WP11-011", "SDE-016"],
     "operator": "WP11-011 ∘ SDE-016",
     "preserved": ["pipeline anti-hallucination : détection + refus structuré"],
     "test_input": "réponse candidate avec affirmation non supportée",
     "test_output": "détection hallucination → refus avec citation des lois manquantes",
     "delta_S_global": 0.02, "status": "admissible"},
    {"pair": ["DVE-008", "WP12-009"],
     "operator": "DVE-008 ∘ WP12-009",
     "preserved": ["filtre variantes + critère admissibilité = double-filtre anti-hallu"],
     "test_input": "génération de N variantes",
     "test_output": "variantes survivantes = admissibles ∧ non hallucinantes",
     "delta_S_global": 0.01, "status": "admissible"},
    {"pair": ["UDE-009", "ULG-008"],
     "operator": "UDE-009 ∘ ULG-008",
     "preserved": ["retrieval contextuel + invariance embedding cross-modèle"],
     "test_input": "query sur 2 modèles distincts",
     "test_output": "lois retrieved cohérentes inter-modèles",
     "delta_S_global": 0.01, "status": "admissible"},
    {"pair": ["SDE-013", "WP11-011"],
     "operator": "SDE-013 ∘ WP11-011",
     "preserved": ["self-check + audit hallucination = double-validation runtime"],
     "test_input": "output candidat",
     "test_output": "rejet si hallucination détectée à l'auto-observation",
     "delta_S_global": 0.02, "status": "admissible"},
    {"pair": ["GHUC-008", "PAL-013"],
     "operator": "GHUC-008 ∘ PAL-013",
     "preserved": ["rollback automatique + saut catastrophique sur HS↓↓"],
     "test_input": "HS chute brutale",
     "test_output": "rollback + bascule mode emergency",
     "delta_S_global": 0.0, "status": "admissible"},
    {"pair": ["WP12-019", "SDE-009"],
     "operator": "WP12-019 ∘ SDE-009",
     "preserved": ["audit user + chain-of-thought = transparence complète"],
     "test_input": "demande d'audit user sur réponse",
     "test_output": "trace complète + lois utilisées + chain-of-thought",
     "delta_S_global": 0.01, "status": "admissible"},
    {"pair": ["UDE-014", "UDE-017"],
     "operator": "UDE-014 ∘ UDE-017",
     "preserved": ["mémoire épisodique + decay cohérents"],
     "test_input": "événements anciens",
     "test_output": "decay correct, événements pertinents gardés",
     "delta_S_global": 0.0, "status": "admissible"},
]


# ──────────── PIPELINE ────────────
def existing_ids(data): return {n["id"] for n in data["nodes"]}


def parents_of(graph, node_id):
    return [e["target"] for e in graph["edges"]
            if e["kind"] == "parent" and e["source"] == node_id]


def children_of(graph, node_id):
    return [e["source"] for e in graph["edges"]
            if e["kind"] == "parent" and e["target"] == node_id]


def count_compositions_for(law_id, data, planned_candidates, new_edges, new_compositions):
    composes = set()

    cand = next((c for c in planned_candidates if c["id"] == law_id), None)
    if cand and cand.get("parent"):
        composes.add(cand["parent"])

    parent_id = cand["parent"] if cand else None
    if parent_id:
        parent_cand = next((c for c in planned_candidates if c["id"] == parent_id), None)
        if parent_cand and parent_cand.get("parent"):
            composes.add(parent_cand["parent"])
        else:
            composes.update(parents_of(data, parent_id))

    if cand and cand["parent"]:
        for other in planned_candidates:
            if other["id"] != law_id and other.get("parent") == cand["parent"]:
                composes.add(other["id"])
        for sib in children_of(data, cand["parent"]):
            if sib != law_id: composes.add(sib)

    for other in planned_candidates:
        if other.get("parent") == law_id: composes.add(other["id"])
    for child in children_of(data, law_id): composes.add(child)

    for e in data.get("edges", []):
        if e.get("kind") == "parent":
            if e["source"] == law_id: composes.add(e["target"])
            if e["target"] == law_id: composes.add(e["source"])
        elif e.get("kind") in ("iso", "contradicts", "related", "absorbed_into", "depends"):
            if e["source"] == law_id: composes.add(e["target"])
            if e["target"] == law_id: composes.add(e["source"])

    for e in new_edges:
        if e["source"] == law_id: composes.add(e["target"])
        if e["target"] == law_id: composes.add(e["source"])

    for c in new_compositions:
        if law_id in c["pair"]:
            for p in c["pair"]:
                if p != law_id: composes.add(p)

    for c in data.get("compositions", []):
        if law_id in c.get("pair", []):
            for p in c["pair"]:
                if p != law_id: composes.add(p)

    composes.discard(law_id)
    return composes


def run_pipeline():
    data = json.loads(DATA.read_text(encoding="utf-8"))
    by_id = existing_ids(data)

    quarantine = []
    integrated = []
    integration_log = []

    for cand in CANDIDATES:
        cid = cand["id"]
        if cand["family"] not in CANONICAL_FAMILIES:
            quarantine.append({"id": cid, "reason": f"family '{cand['family']}' not canonical", "phase": 1})
            continue

        f_ = cand["frames"]
        ok2 = True
        for k in ("local","intermediate","global","proxies","limits"):
            if k not in f_:
                quarantine.append({"id": cid, "reason": f"frames.{k} missing", "phase": 2}); ok2 = False; break
        if not ok2: continue
        if not f_["intermediate"]:
            quarantine.append({"id": cid, "reason": "frames.intermediate empty", "phase": 2}); continue
        if not f_["limits"]:
            quarantine.append({"id": cid, "reason": "frames.limits empty", "phase": 2}); continue
        bad_level = next((e for e in f_["intermediate"] if e["level"] not in INTERMEDIATE_LEVELS), None)
        if bad_level:
            quarantine.append({"id": cid, "reason": f"intermediate level invalid", "phase": 2}); continue

        if len(cand["html_description"]) < 40:
            quarantine.append({"id": cid, "reason": "description < 40 chars", "phase": 3}); continue
        if not (cand["equations"] or cand["examples"]):
            quarantine.append({"id": cid, "reason": "no grounding", "phase": 3}); continue

        comps = count_compositions_for(cid, data, CANDIDATES, NEW_EDGES_TYPED, NEW_COMPOSITIONS)
        if len(comps) < 3:
            quarantine.append({"id": cid, "reason": f"compositions {len(comps)} < 3", "phase": 4, "found": list(comps)})
            continue

        integrated.append(cand)
        integration_log.append({
            "id": cid, "family": cand["family"], "parent": cand["parent"],
            "compositions_count": len(comps),
            "S_local": cand["S_local"], "S_global": cand["S_global"], "weight": cand["weight"]
        })

    new_nodes = []
    new_parent_edges = []
    for cand in integrated:
        if cand["id"] in by_id: continue
        node = {
            "id": cand["id"], "title": cand["title"],
            "canonical": cand["canonical"], "palieronic": cand["palieronic"],
            "family": cand["family"], "attractor_tier": None,
            "domains": cand["domains"], "examples": cand["examples"],
            "html_description": cand["html_description"], "equations": cand["equations"],
            "S_local": cand["S_local"], "S_global": cand["S_global"],
            "stability": cand["stability"], "weight": cand["weight"],
            "frames": cand["frames"], "runtime_admissible": True,
        }
        new_nodes.append(node)
        new_parent_edges.append({"source": cand["id"], "target": cand["parent"], "kind": "parent"})

    data["nodes"].extend(new_nodes)
    data["edges"].extend(new_parent_edges)
    data["edges"].extend(NEW_EDGES_TYPED)
    data.setdefault("compositions", []).extend(NEW_COMPOSITIONS)

    data["p0_5_meta"] = data.get("p0_5_meta", {})
    data["p0_5_meta"]["p2_integrated_count"] = len(integrated)
    data["p0_5_meta"]["p2_quarantined_count"] = len(quarantine)
    data["p0_5_meta"]["p2_timestamp"] = "2026-05-15T20:30:00+02:00"
    data["p0_5_meta"]["p2_mission_id"] = "ZORAN_P2_DEMONSTRATED_EXPANSION_100_LAWS_20260515"
    data["p0_5_meta"]["compositions_demonstrated"] = len(data["compositions"])

    DATA.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    QUARANTINE.parent.mkdir(parents=True, exist_ok=True)
    QUARANTINE.write_text(json.dumps({
        "mission_id": "ZORAN_P2_DEMONSTRATED_EXPANSION_100_LAWS_20260515",
        "candidates_total": len(CANDIDATES),
        "integrated_count": len(integrated),
        "quarantined_count": len(quarantine),
        "quarantined": quarantine
    }, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    INTEGRATION.write_text(json.dumps({
        "mission_id": "ZORAN_P2_DEMONSTRATED_EXPANSION_100_LAWS_20260515",
        "integrated": integration_log
    }, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    print(f"\nP2 candidates  : {len(CANDIDATES)}")
    print(f"Integrated     : {len(integrated)}")
    print(f"Quarantined    : {len(quarantine)}")
    print(f"New nodes      : {len(new_nodes)}")
    print(f"New edges      : {len(new_parent_edges) + len(NEW_EDGES_TYPED)}")
    print(f"New comps      : {len(NEW_COMPOSITIONS)}")
    print(f"Total comps    : {len(data['compositions'])}")


if __name__ == "__main__":
    run_pipeline()
